<?php

namespace Dof\ItemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemTemplateEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemTemplateEffectRepository extends EntityRepository
{
}
