<?php

namespace Dof\Bundle\GraphicsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuildLookRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildLookRepository extends EntityRepository
{
}
