<?php

namespace Dof\Bundle\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapPositionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapPositionRepository extends EntityRepository
{
}
