<?php

namespace Dof\Bundle\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuperAreaRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperAreaRepository extends EntityRepository
{
}
