imports:
    - { resource: importers/item.yml }
    - { resource: importers/quest.yml }
    - { resource: importers/spell.yml }
    - { resource: importers/map.yml }
    - { resource: importers/monster.yml }

services:
    dof_imp_exp.importer.game_importer:
        abstract: true
        arguments:
            - "@importer_dependencies"

    importer_dependencies:
        class: XN\DependencyInjection\ServiceArray
        arguments:
            - "@dof_imp_exp.game_data_provider"
            - "@doctrine.orm.entity_manager"

    # DofCharacterBundle:Breed
    dof_imp_exp.importer.breeds:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\BreedImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breeds, groups: "beta" }

    dof_imp_exp.importer.breed_default_colors:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\BreedDefaultColorsImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: breed_default_colors, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_default_colors, requires: beta_breeds, groups: "beta" }

    dof_imp_exp.importer.breed_lodef_skins:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\BreedLodefSkinsImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: breed_lodef_skins, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_lodef_skins, requires: beta_breeds, groups: "beta" }
    # DofCharacterBundle:Face
    dof_imp_exp.importer.breed_faces:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\FaceImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: breed_faces, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_faces, requires: beta_breeds, groups: "beta" }

    # DofCharacterBundle:SoftCap
    dof_imp_exp.importer.breed_soft_caps:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\SoftCapImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: breed_soft_caps, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_soft_caps, requires: beta_breeds, groups: "beta" }

    # DofItemBundle:Job
    dof_imp_exp.importer.jobs:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\JobImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: jobs }
            - { name: dof_imp_exp.importer, provides: beta_jobs, groups: "beta" }

    # DofCharacterBundle:EffectTemplate
    dof_imp_exp.importer.effect_templates:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\EffectTemplateImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: effect_templates }
            - { name: dof_imp_exp.importer, provides: beta_effect_templates, groups: "beta" }

    # DofCharacterBundle:State
    dof_imp_exp.importer.states:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\StateImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: states }
            - { name: dof_imp_exp.importer, provides: beta_states, groups: "beta" }

    # DofCharacterBundle:Emoticon
    dof_imp_exp.importer.emoticons:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\EmoticonImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: emoticons }
            - { name: dof_imp_exp.importer, provides: beta_emoticons, groups: "beta" }

    # DofCharacterBundle:Titles
    dof_imp_exp.importer.titles:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\TitleImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: titles }
            - { name: dof_imp_exp.importer, provides: beta_titles, groups: "beta" }

    # DofItemBundle:Document
    dof_imp_exp.importer.documents:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\DocumentImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: documents }
            - { name: dof_imp_exp.importer, provides: beta_documents, groups: "beta" }

    # DofCharacterBundle:AlignmentSide
    dof_imp_exp.importer.alignment_sides:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\AlignmentSideImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: alignment_sides, groups: alignments }
            - { name: dof_imp_exp.importer, provides: beta_alignment_sides, groups: "beta" }

    # DofMainBundle:Month
    dof_imp_exp.importer.months:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\MonthImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: months }

    # DofMainBundle:Server
    dof_imp_exp.importer.servers:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\ServerImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: servers }
