imports:
    - { resource: importers/item.yml }
    - { resource: importers/quest.yml }
    - { resource: importers/spell.yml }
    - { resource: importers/map.yml }
    - { resource: importers/monster.yml }

services:
    importer_dependencies:
        class: XN\DependencyInjection\ServiceArray
        arguments:
            - "@dof_imp_exp.game_data_provider"
            - "@doctrine.orm.entity_manager"

    # DofCharacterBundle:Breed
    dof_imp_exp.importer.breeds:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\BreedImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breeds, requires: breeds }
    dof_imp_exp.importer.breed_default_colors:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\BreedDefaultColorsImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_default_colors, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_default_colors, requires: beta_breeds }
    dof_imp_exp.importer.breed_lodef_skins:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\BreedLodefSkinsImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_lodef_skins, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_lodef_skins, requires: beta_breeds }
    # DofCharacterBundle:Face
    dof_imp_exp.importer.breed_faces:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\FaceImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_faces, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_faces, requires: beta_breeds }

    # DofCharacterBundle:SoftCap
    dof_imp_exp.importer.breed_soft_caps:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\SoftCapImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_soft_caps, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_soft_caps, requires: beta_breeds }

    # DofItemBundle:Job
    dof_imp_exp.importer.job:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\JobImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: job }
            - { name: dof_imp_exp.importer, provides: beta_job, requires: job }

    # DofCharacterBundle:EffectTemplate
    dof_imp_exp.importer.effect_templates:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\EffectTemplateImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: effect_templates }
            - { name: dof_imp_exp.importer, provides: beta_effect_templates }

    # DofCharacterBundle:State
    dof_imp_exp.importer.states:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\StateImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: states }
            - { name: dof_imp_exp.importer, provides: beta_states, requires: states }

    # DofCharacterBundle:Emoticon
    dof_imp_exp.importer.emoticons:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\EmoticonImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: emoticons }
            - { name: dof_imp_exp.importer, provides: beta_emoticons, requires: emoticons }

    # DofCharacterBundle:Titles
    dof_imp_exp.importer.titles:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\TitleImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: titles }
            - { name: dof_imp_exp.importer, provides: beta_titles, requires: titles }

    # DofItemBundle:Document
    dof_imp_exp.importer.documents:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\DocumentImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: documents }
            - { name: dof_imp_exp.importer, provides: beta_documents, requires: documents }

    # DofCharacterBundle:AlignmentSide
    dof_imp_exp.importer.alignment_sides:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\AlignmentSideImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: alignment_sides }
            - { name: dof_imp_exp.importer, provides: beta_alignment_sides, requires: alignment_sides }

    # DofMainBundle:Month
    dof_imp_exp.importer.months:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\MonthImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: months }

    # DofMainBundle:Server
    dof_imp_exp.importer.servers:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\ServerImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: servers }
