<?php

namespace Dof\GraphicsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterLookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterLookRepository extends EntityRepository
{
}
