<?php

namespace Dof\ArticlesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
	public function findArticlesWithLimits($is_news = false, $firstresult = 0, $maxresults=10)
	{

	    if($is_news)
	    	$boolean=1;
	    else
	    	$boolean=0;
	    $qb = $this->createQueryBuilder('a');

	    $qb->add('where', 'a.news= :boolean')
	       ->add('orderBy', 'a.dernmodif DESC')
	       ->setParameter('boolean', $boolean)
		   ->setFirstResult( $firstresult )
		   ->setMaxResults( $maxresults );

	    $result = $qb->getQuery()
	    			 ->setResultCacheDriver(new \Doctrine\Common\Cache\FilesystemCache('../bin/cache/'))
					 ->useResultCache(true, 3600, 'findArticlesWithLimits'.$firstresult.'-'.$maxresults)
					 ->getResult();

	    return $result;
	}
}
