parameters:
#    dof_message.example.class: Dof\MessageBundle\Example

services:
#    dof_message.example:
#        class: %dof_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
