<?php

namespace XN\UtilityBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * LoggedActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoggedActionRepository extends EntityRepository
{
    public function findLastActions(AdvancedUserInterface $user, $max = 20) {
        return $this
                  ->createQueryBuilder('a')
                  ->where('a.owner = :user')
                  ->orderBy('a.createdAt', 'DESC')
                  ->groupBy('a.key')
                  ->setMaxResults($max)
                  ->getQuery()
                  ->setParameter('user', $user)
                  ->getResult();
              ;
    }
}
