<?php

namespace Dof\CharactersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaceRepository extends EntityRepository
{
    public function findBySkinIds(array $skinIds)
    {
        $skins = array();
        foreach ($this->createQueryBuilder('f')
            ->where('f.id IN (:skinIds)')
            ->setParameter('skinIds', $skinIds)
            ->getQuery()
            ->getResult() as $skin)
            $skins[$skin->getId()] = $skin;
        ksort($skins);
        return $skins;
    }
}
