<?php

namespace Dof\CharactersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SoftCapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftCapRepository extends EntityRepository
{
}
