<?php

namespace Dof\CharactersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpellRepository extends EntityRepository
{
	public function findBySpellEffectParam($param)
	{
		return $this->findByObjectEffectParam('DofCharactersBundle:Spell', $param);
	}
	public function findByMonsterEffectParam($param)
	{
		return $this->findByObjectEffectParam('DofMonsterBundle:Monster', $param);
	}
	public function findByStateEffectParam($param)
	{
		return $this->findByObjectEffectParam('DofCharactersBundle:State', $param);
	}

	public function findByEffectTemplate($effectTemplate)
	{
		return $this->createQueryBuilder('s')
			->where(<<<'EOS'
s.id IN (
	SELECT sr.spell
	FROM DofCharactersBundle:SpellRank sr
	WHERE sr.id IN (
		SELECT sre.spellRank
		FROM DofCharactersBundle:SpellRankEffect sre
		WHERE sre.effectTemplate = :effectTemplate
	)
)
EOS
)
			->getQuery()
			->setParameter('effectTemplate', is_object($effectTemplate) ? $effectTemplate->getId() : $effectTemplate)
			->getResult();
	}

	public function findByObjectEffectParam($relationType, $param)
	{
		return $this->createQueryBuilder('s')
			->where(<<<'EOS'
s.id IN (
	SELECT sr.spell
	FROM DofCharactersBundle:SpellRank sr
	WHERE sr.id IN (
		SELECT sre.spellRank
		FROM DofCharactersBundle:SpellRankEffect sre
		JOIN sre.effectTemplate et
		JOIN et.relations etr WITH etr.targetEntity = :relationType AND (etr.column1 = 'id' OR etr.column2 = 'id' OR etr.column3 = 'id')
		WHERE etr.column1 = 'id' AND et.rawParam1 = :param OR etr.column2 = 'id' AND et.rawParam2 = :param OR etr.column3 = 'id' AND et.rawParam3 = :param
	)
)
EOS
)
			->getQuery()
			->setParameter('relationType', $relationType)
			->setParameter('param', is_object($param) ? $param->getId() : $param)
			->getResult();
	}
}
