<?php

namespace Dof\Bundle\CMSBundle\Entity;

/**
* CollectionArticleRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class CollectionArticleRepository extends ArticleRepository
{
}
