<?php

namespace Dof\Bundle\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DungeonArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DungeonArticleRepository extends ArticleRepository
{
}
