<?php

namespace Dof\Bundle\CMSBundle\Entity;

/**
 * QuestArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestArticleRepository extends ArticleRepository
{
}
