<?php

namespace Dof\Bundle\CMSBundle\Entity;

/**
 * TutorialArticleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorialArticleRepository extends ArticleRepository
{
}
