dof_items_json_itemtemplate:
    pattern:  /json/item-template/{l1id}/data.json
    defaults: { _controller: DofItemsBundle:ItemTemplateRest:fetch }
    requirements: { _method: GET, l1id: '[0-9a-z-]+' }
    options:  { expose: true }

dof_items_json_itemtemplate_store:
    pattern:  /json/item-template/{l1id}/data.json
    defaults: { _controller: DofItemsBundle:ItemTemplateRest:fetch }
    requirements: { _method: PUT, l1id: '[0-9a-z-]+' }

dof_items_json_itemtemplate_delete:
    pattern:  /json/item-template/{l1id}/data.json
    defaults: { _controller: DofItemsBundle:ItemTemplateRest:fetch }
    requirements: { _method: DELETE, l1id: '[0-9a-z-]+' }

dof_items_json_itemtemplate_searchequipment:
    pattern:  /json/item-template/search-equipment.json
    defaults: { _controller: DofItemsBundle:ItemTemplateRest:searchEquipment }
    requirements: { _method: GET }
    options:  { expose: true }

dof_items_qualitydiagram:
    pattern:  /quality-diagram
    defaults: { _controller: DofItemsBundle:QualityDiagram:index }

dof_items_qualitydiagram_pdf:
    pattern:  /quality-diagram.pdf
    defaults: { _controller: DofItemsBundle:QualityDiagram:pdf }
    requirements: { _method: POST }

dof_items_homepage:
    pattern:   /{page}
    defaults: { _controller: DofItemsBundle:Items:index, page: 1}
    requirements:
        page: \d+

dof_items_show:
    pattern: /{slug}
    defaults: { _controller: DofItemsBundle:Items:show }
    requirements:
        slug: '[0-9a-z-]+'

dof_set_homepage:
    pattern: /sets/
    defaults: { _controller: DofItemsBundle:Sets:index }

dof_set_show:
    pattern: /sets/{slug}
    defaults: { _controller: DofItemsBundle:Sets:show }
    requirements:
        slug: '[0-9a-z-]+'
