parameters:
#    dof_items.example.class: Dof\ItemsBundle\Example

services:
#    dof_items.example:
#        class: %dof_items.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    dof_items.admin.item_template:
        class: Dof\ItemsBundle\Admin\ItemTemplateAdmin
        arguments: [~, Dof\ItemsBundle\Entity\ItemTemplate, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Items, label: Item}

    dof_items.admin.skinned_equipment_template:
        class: Dof\ItemsBundle\Admin\SkinnedEquipmentTemplateAdmin
        arguments: [~, Dof\ItemsBundle\Entity\SkinnedEquipmentTemplate, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Items, label: Equipment}

    dof_items.admin.item_set:
        class: Dof\ItemsBundle\Admin\ItemSetAdmin
        arguments: [~, Dof\ItemsBundle\Entity\ItemSet, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Items, label: Set}

    dof_items.admin.animal_template:
        class: Dof\ItemsBundle\Admin\AnimalTemplateAdmin
        arguments: [~, Dof\ItemsBundle\Entity\AnimalTemplate, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Items, label: AnimalTemplate}

    dof_items.twig.element_extension:
        class: Dof\ItemsBundle\Twig\ElementExtension
        tags:
            - { name: twig.extension }

    # Criteria
    dof_items.criteria_loader:
        class: Dof\ItemsBundle\Criteria\CriteriaLoader
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
