dof_articles_view:
    pattern:  view/{type}/{slug}
    defaults: { _controller: DofArticlesBundle:Articles:view }

dof_articles_edit:
    pattern:  edit/{type}/{id}
    defaults: { _controller: DofArticlesBundle:Articles:edit }
    requirements:
      id: \d+

dof_articles_archive:
    pattern:  /{page}
    defaults: { _controller: DofArticlesBundle:Archive:archive, page: 1 }
    requirements:
      page: \d+

dof_articles_add:
    pattern:  /add/{type}
    defaults: { _controller: DofArticlesBundle:Articles:add }

dof_articles_viewType:
    pattern:  view/{type}
    defaults: { _controller: DofArticlesBundle:Articles:viewType }

dof_articles_addList:
    pattern:  /addListe/{type}/{page}
    defaults: { _controller: DofArticlesBundle:Archive:archive, page: 1 }
    requirements:
      page: \d+