dof_articles_view:
    pattern:  /view/{slug}
    defaults: { _controller: DofArticlesBundle:Articles:view }
    requirements:
      id: \d+

dof_articles_edit:
    pattern:  /edit/{id}
    defaults: { _controller: DofArticlesBundle:Articles:edit }
    requirements:
      id: \d+

dof_articles_edit:
    pattern:  /archive/
    defaults: { _controller: DofArticlesBundle:Archive:archive }
