dof_articles_view:
    pattern:  /{slug}
    defaults: { _controller: DofArticlesBundle:Articles:view }
    requirements:
      id: \d+

dof_articles_edit:
    pattern:  /edit/{id}
    defaults: { _controller: DofArticlesBundle:Articles:edit }
    requirements:
      id: \d+
