parameters:
#    dof_news.example.class: Dof\NewsBundle\Example

services:
#    dof_news.example:
#        class: %dof_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
