parameters:
    dof_articles.article.form.class: Dof\ArticlesBundle\Form\Type\ArticleFormType

services:
    dof_articles.profile.form.type:
        class: %dof_articles.article.form.class%
        tags:
            - { name: form.type, alias: dof_articles_main }
