<?php

namespace Dof\ItemsBundle\Entity;

use XN\Rest\FilterableEntityRepository;

use Doctrine\ORM\QueryBuilder;

/**
 * ItemTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemTemplateRepository extends FilterableEntityRepository
{
	protected function getFilterableExpr(QueryBuilder $qb, $alias, $locale = 'fr')
	{
		$primary = $alias . ".name" . ucfirst($locale);
		$secondary = $alias . ".nameFr";

		return  /*" COALESCE(" . */ $primary /*. ", " . $secondary .") "*/;
	}

    public function findByIdWithType($id) {
        return $this
                  ->createQueryBuilder('it')
                  ->join('it.type', 't')
                  ->where('it.id = :id')
                  ->getQuery()
                  ->setParameter('id', $id)
                  ->getResult();
              ;
    }

    public function findBySlot($slot, $locale) {
        return $this
                  ->createQueryBuilder('se')
                  ->select(array('se.id', 'se.name' . ucfirst($locale) . ' as name'))
                  ->join('se.type', 't')
                  ->where('t.slot = :slot')
                  ->getQuery()
                  ->setParameter('slot', $slot)
                  ->setResultCacheDriver(new \Doctrine\Common\Cache\FilesystemCache('../app/cache/'))
                  ->useResultCache(true, 3600)
                  ->getArrayResult()
              ;
    }

	public function findItemsWithJoins($criteria, $firstResult = null, $maxResults = null){
        $qb = $this
                  ->createQueryBuilder('i')
                  ->join('i.set', 's')
              ;

		$i = 0;
		foreach($criteria as $k => $v){
			$i++;
			$qb
				->andWhere($k . ' LIKE :filterWord' . $i)
				->setParameter('filterWord' . $i, $v)
			;
		}

		if($firstResult != null)
			$qb->setFirstResult($firstresult);
		if($maxResults != null)
			$qb->setMaxResults($maxResults);

		return $qb
        	->getQuery()
        	->getResult()
		;
	}
}
