services:
    dof_search.search_manager:
        class: Dof\SearchBundle\SearchManager
        arguments: [ "@cache", "%wit_private_key%" ]


    intent_dependencies:
        class: XN\DependencyInjection\ServiceArray
        arguments:
            - "@twig"
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
            - "@security.context"

    dof_search.intent.search_item:
        class: Dof\SearchBundle\Intent\ItemSearchIntent
        arguments: [ @intent_dependencies ]
        tags:
            - { name: dof_search.intent, intent: search_item }

    dof_search.intent.almanax:
        class: Dof\SearchBundle\Intent\AlmanaxSearchIntent
        arguments: [ @intent_dependencies ]
        tags:
            - { name: dof_search.intent, intent: search_almanax }

    dof_search.intent.search_user:
        class: Dof\SearchBundle\Intent\UserSearchIntent
        arguments: [ @intent_dependencies ]
        tags:
            - { name: dof_search.intent, intent: search_user }

    dof_search.intent.add_notification:
        class: Dof\SearchBundle\Intent\AddNotificationIntent
        arguments: [ @intent_dependencies ]
        tags:
            - { name: dof_search.intent, intent: add_notification }
