dof_build_homepage:
    path:     /
    defaults: { _controller: DofBuildBundle:Build:index }

# Affichage des builds
dof_build_show:
    path:     /{user}/{character}/{stuff}
    defaults: { _controller: DofBuildBundle:Build:show }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'


dof_build_show_characteristics:
    path:     /{user}/{character}/{stuff}/characteristics
    defaults: { _controller: DofBuildBundle:Build:showCharacteristics }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_build_show_weapondamages:
    path:     /{user}/{character}/{stuff}/weaponDamages
    defaults: { _controller: DofBuildBundle:Build:showWeaponDamages }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_build_show_spellsDamages:
    path:     /{user}/{character}/{stuff}/spell-damages
    defaults: { _controller: DofBuildBundle:Build:showSpellsDamages }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_build_edit:
    path:     /{user}/{character}/{stuff}/configuration
    defaults: { _controller: DofBuildBundle:Build:configuration }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

# Ajout dans les builds
dof_build_additem_post:
    path:     /add-items/
    defaults: { _controller: DofBuildBundle:Stuff:addItems}
    requirements:
        _method: POST

dof_build_additem:
    path:     /{user}/{character}/{stuff}/add/{type}/{slot}/{page}
    defaults: { _controller: DofItemsBundle:Items:showBuildItems, slot: 0, page: 1}
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'
        page: \d+


dof_build_create_stuff:
    path:     /create-stuff/{slug}/
    defaults: { _controller: DofBuildBundle:Stuff:createStuff}
    requirements:
        slug: '[0-9a-z-]+'
        _method: POST
