dof_build_homepage:
    path:     /
    defaults: { _controller: DofBuildBundle:Build:index }

dof_build_show:
    path:     /{user}/{character}/{stuff}
    defaults: { _controller: DofBuildBundle:Build:show }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_build_additem:
    path:     /{user}/{character}/{stuff}/add/{type}/{page}
    defaults: { _controller: DofItemsBundle:Items:addItem, page: 1}
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'
        page: \d+
