parameters:
#    dof_build.example.class: Dof\BuildBundle\Example

services:
#    dof_build.example:
#        class: %dof_build.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
