parameters:
    dof_build.playerCharacter.form.class: Dof\BuildBundle\Form\PlayerCharacterType
    dof_build.stuff_look_loader.class: Dof\BuildBundle\StuffLookLoader

services:
    dof_build.playerCharacter.form.type:
        class: '%dof_build.playerCharacter.form.class%'
        tags:
            - { name: form.type, alias: dof_buildbundle_playercharacter }

    dof_build.stuff_converter:
        class: Dof\BuildBundle\ParamConverter\BuildParamConverter
        arguments: ['@service_container']
        tags:
            - { name: request.param_converter, priority: 1}

    build_manager:
        class: Dof\BuildBundle\BuildManager
        arguments: ['@service_container']
