imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @DofAdminBundle/Resources/config/admin.yml }

parameters:
  locales: [fr, en, de, it, es, pt, ru, ja]
  current_release_number: '2.22'
  beta_release_number: '2.23'
  current_release_database: dofawa2
  beta_release_database: dofus2beta

jms_i18n_routing:
    default_locale: en
    locales: %locales%
    strategy: prefix

framework:
    #esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    translator:
        fallback: default
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        storage_id:  session.storage.php_bridge
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        csrf_serv: "@form.csrf_provider"
        locales: %locales%
    form:
        resources:
            - DofMainBundle:Form:fields.html.twig


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ FOSUserBundle, DofUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            # Formatter options: compressed, lessjs, classic
            formatter: "compressed"
            preserve_comments: false
            presets:
                my_variable: "#000"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Dof\UserBundle\Entity\User
    profile:
        form:
            type: dof_user_profile
    registration:
        form:
            type: dof_user_registration

fos_message:
    db_driver: orm
    thread_class: Dof\MessageBundle\Entity\Thread
    message_class: Dof\MessageBundle\Entity\Message

# app/config/config.yml
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks

sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
    security:
        handler: sonata.admin.security.handler.role
        acl_user_manager: fos_user.user_manager # Name of the user manager service used to retrieve ACL users
        information:
            EDIT: EDIT
            EDITFULL: EDITFULL
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    options:
        pager_links:    15     # pager max links to display

braincrafted_bootstrap:
    less_filter: none
    auto_configure:
        assetic: false
        twig: false
        knp_menu: false
        knp_paginator: false

ewz_recaptcha:
    public_key:   6Lc4ZfYSAAAAAG10vxtJkhBO0xCcPfqm9fAT_Qg8
    private_key:  6Lc4ZfYSAAAAAD5Bg-xjfAlFmZBFUeqgJEJqGGmC
    locale_key:   %kernel.default_locale%

knp_snappy:
    pdf:
        enabled: true
        binary: %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options: []
    image:
        enabled: true
        binary: %kernel.root_dir%/../vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64
        options: []

bazinga_js_translation:
    locale_fallback: fr
