imports:
    - { resource: parameters.yml }
    - { resource: release_parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @DofAdminBundle/Resources/config/admin.yml }

parameters:
  locales: [fr, en, de, it, es, pt, ru, ja]
  current_release_database: dofawa2
  beta_release_database: dofawa3
  wit_private_key: "DQCNE665II22LYW3SA7TTZ7GWR7NXLBI"

framework:
    serializer:
        enable_annotations: true
    esi: { enabled: true }
    #esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    translator:
        fallback: default
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        storage_id:  session.storage.php_bridge
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ FOSUserBundle, DofUserBundle ]
    filters:
        cssrewrite: ~
        lessphp:
            formatter: "compressed"
            preserve_comments: false
            presets:
                my_variable: "#000"

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        metadata_cache_driver: apc
        query_cache_driver: apc
        result_cache_driver: apc
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Dof\Bundle\UserBundle\Entity\User

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
    security:
        handler: sonata.admin.security.handler.role
        acl_user_manager: fos_user.user_manager # Name of the user manager service used to retrieve ACL users
        information:
            EDIT: EDIT
            EDITFULL: EDITFULL
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    options:
        pager_links:    15

knp_snappy:
    pdf:
        enabled: true
        binary: %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options: []
    image:
        enabled: true
        binary: %kernel.root_dir%/../vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64
        options: []

liip_imagine:
    filter_sets:
        50x50:
            quality: 85
            filters:
                thumbnail: { size: [50, 50], mode: outbound, allow_upscale: true }

stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            timestampable: true
            sluggable: true
            blameable: true
            translatable: true

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

nelmio_cors:
    defaults:
        allow_origin:  ["%cors_allow_origin%"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers: ["content-type", "authorization"]
        max_age:       3600
    paths:
        '^/': ~

nelmio_api_doc:
    sandbox:
        authentication:
            name: Authorization
            delivery: header
            type:     bearer
        body_format:
            formats: [ json ]
