imports:
    - { resource: parameters.yml }
    - { resource: release_parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
  locales: [fr, en, de, it, es, pt, ru, ja]
  wit_private_key: "DQCNE665II22LYW3SA7TTZ7GWR7NXLBI"

framework:
    assets: ~
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session: ~
    form:            ~
    fragments:       ~
    http_method_override: true
    serializer:      { enable_annotations: true }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: login
    user_class: Dof\Bundle\UserBundle\Entity\User

knp_snappy:
    pdf:
        enabled: true
        binary: %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options: []
    image:
        enabled: true
        binary: %kernel.root_dir%/../vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64
        options: []

liip_imagine:
    filter_sets:
        50x50:
            quality: 85
            filters:
                thumbnail: { size: [50, 50], mode: outbound, allow_upscale: true }

stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            timestampable: true
            sluggable: true
            blameable: true
            translatable: true

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
    '^/':
        allow_origin: ["%cors_allow_origin%"]
        allow_headers: ['origin', 'content-type', 'authorization']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
        max_age: 3600

fos_rest:
    routing_loader:
        default_format:       json
        include_format:       false
    view:
        view_response_listener:
            enabled:              true
        formats:
            json: true
        templating_formats:
            html: false
    param_fetcher_listener: true
