dof_quest:
    resource: "@DofQuestBundle/Resources/config/routing.yml"
    prefix:   /quests

dof_monster:
    resource: "@DofMonsterBundle/Resources/config/routing.yml"
    prefix:   /monsters

dof_user_character:
    resource: "@DofUserCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters/u

dof_characters:
    resource: "@DofCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters

dof_graphics:
    resource: "@DofGraphicsBundle/Resources/config/routing.yml"
    prefix:   /graphics

#dof_map:
#    resource: "@DofMapBundle/Resources/config/routing.yml"
#    prefix:   /map

dof_main:
    resource: "@DofMainBundle/Resources/config/routing.yml"
    prefix:   /

dof_items:
    type:     rest
    resource: Dof\Bundle\ItemBundle\Controller\ItemsController

dof_servers:
    type:     rest
    resource: Dof\Bundle\MainBundle\Controller\ServersController

login:
    path: /login

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
