dof_quest:
    resource: "@DofQuestBundle/Resources/config/routing.yml"
    prefix:   /quests

dof_monster:
    resource: "@DofMonsterBundle/Resources/config/routing.yml"
    prefix:   /monsters

dof_user_character:
    resource: "@DofUserCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters/u

dof_characters:
    resource: "@DofCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters

dof_graphics:
    resource: "@DofGraphicsBundle/Resources/config/routing.yml"
    prefix:   /graphics

#dof_map:
#    resource: "@DofMapBundle/Resources/config/routing.yml"
#    prefix:   /map

dof_main:
    resource: "@DofMainBundle/Resources/config/routing.yml"
    prefix:   /

dof_users:
    resource: "@DofUserBundle/Resources/config/routing.yml"
    prefix:   /users

dof_items:
    resource: "@DofItemBundle/Resources/config/routing.yml"
    prefix:   /items

dof_trades:
    resource: "@DofTradingBundle/Resources/config/routing.yml"
    prefix:   /trades

dof_servers:
    resource: "@DofMainBundle/Resources/config/routing/servers.yml"
    prefix:   /servers

dof_login:
    path: /login
    defaults: { _controller: DofUserBundle:Login:login }
    methods: [ POST ]

dof_registration:
    path: /register
    defaults: { _controller: DofUserBundle:Registration:register }
    methods: [ POST ]

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
