dof_quest:
    resource: "@DofQuestBundle/Resources/config/routing.yml"
    prefix:   /quests

dof_monster:
    resource: "@DofMonsterBundle/Resources/config/routing.yml"
    prefix:   /monsters

dof_user_character:
    resource: "@DofUserCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters/u

dof_characters:
    resource: "@DofCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#dof_admin:
#    resource: "@DofAdminBundle/Resources/config/routing.yml"
#    prefix:   /admin

dof_graphics:
    resource: "@DofGraphicsBundle/Resources/config/routing.yml"
    prefix:   /graphics

#dof_map:
#    resource: "@DofMapBundle/Resources/config/routing.yml"
#    prefix:   /map

dof_main:
    resource: "@DofMainBundle/Resources/config/routing.yml"
    prefix:   /

dof_item:
    resource: "@DofItemBundle/Resources/config/routing.yml"
    prefix:   /items

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@DofUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
