dof_main:
    resource: "@DofMainBundle/Resources/config/routing.yml"
    prefix:   /

dof_items:
    resource: "@DofItemsBundle/Resources/config/routing.yml"
    prefix:   /

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

dof_articles:
    resource: "@DofArticlesBundle/Resources/config/routing.yml"
    prefix:   /news

dof_user:
    resource: "@DofUserBundle/Resources/config/routing.yml"
    prefix: /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile