dof_quest:
    resource: "@DofQuestBundle/Resources/config/routing.yml"
    prefix:   /quests

dof_monster:
    resource: "@DofMonsterBundle/Resources/config/routing.yml"
    prefix:   /monsters

dof_user_character:
    resource: "@DofUserCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters/u

dof_characters:
    resource: "@DofCharacterBundle/Resources/config/routing.yml"
    prefix:   /characters

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#dof_admin:
#    resource: "@DofAdminBundle/Resources/config/routing.yml"
#    prefix:   /admin

dof_graphics:
    resource: "@DofGraphicsBundle/Resources/config/routing.yml"
    prefix:   /graphics

#dof_map:
#    resource: "@DofMapBundle/Resources/config/routing.yml"
#    prefix:   /map

dof_main:
    resource: "@DofMainBundle/Resources/config/routing.yml"
    prefix:   /

dof_item:
    resource: "@DofItemBundle/Resources/config/routing.yml"
    prefix:   /items

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
