services:
    doctrine.repository:
        abstract: true
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]

    # Validator cache
    # See https://github.com/symfony/symfony/pull/16822
    # validator.mapping.cache.doctrine.apc:
    #     class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
    #     arguments: [ '@validator.mapping.cache.apc' ]
    #     public: false
    #
    # validator.mapping.cache.apc:
    #     class: Doctrine\Common\Cache\ApcCache
    #     calls:
    #         - [ setNamespace, [ %validator.mapping.cache.prefix% ]]
    #     public: false
