dof_characters_show:
    pattern:  /{slug}
    defaults: { _controller: DofCharactersBundle:Breed:show }
    requirements:
       slug: '[0-9a-z-]+'


dof_spell_show:
    pattern:  /spell/{slug}
    defaults: { _controller: DofCharactersBundle:Spell:show }
    requirements:
       slug: '[0-9a-z-]+'
