dof_characters_show:
    pattern:  /{slug}
    defaults: { _controller: DofCharactersBundle:Breed:show }
    requirements:
       slug: '[0-9a-z-]+'


dof_spell_show:
    pattern:  /spell/{slug}
    defaults: { _controller: DofCharactersBundle:Spell:show }
    requirements:
       slug: '[0-9a-z-]+'

dof_area_render_glyphtrap:
    pattern:  /area/{area}/{color}.svg
    defaults: { _controller: DofCharactersBundle:Area:renderGlyphTrap }
    requirements:
        area: '[0-9A-Za-z_-]+'
        color: '[0-9a-f]{6}'

dof_area_render_normal:
    pattern:  /area/{area}/{type}.svg
    defaults: { _controller: DofCharactersBundle:Area:renderNormal }
    requirements:
        area: '[0-9A-Za-z_-]+'
        color: 'cast|effect'
