parameters:
    dof_characters.effect_param_loader.class: Dof\CharactersBundle\EffectParamLoader

services:
    dof_characters.effect_param_loader:
        class: %dof_characters.effect_param_loader.class%
        arguments: [ @translator ]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
