parameters:
#    dof_characters.example.class: Dof\CharactersBundle\Example

services:
#    dof_characters.example:
#        class: %dof_characters.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
