<?php

namespace Dof\BuildBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerCharacterRepository extends EntityRepository
{
}
