dof_items_manager_homepage:
    pattern:   /{page}
    defaults: { _controller: DofItemsManagerBundle:ItemsManager:index, page: 1}
    requirements:
        page: \d+

dof_items_manager_pets:
    pattern:   /petsManager
    defaults: { _controller: DofItemsManagerBundle:PetsManager:show }