dof_items_manager_homepage:
    pattern:   /{page}/
    defaults: { _controller: DofItemsManagerBundle:ItemsManager:index, page: 1}
    requirements:
        page: \d+

dof_items_manager_pets:
    pattern:   /pets-manager
    defaults: { _controller: DofItemsManagerBundle:PetsManager:show }

dof_items_manager_pets_feed:
    pattern:   /pets-manager/feed
    defaults: { _controller: DofItemsManagerBundle:PetsManager:feed }

dof_items_manager_pets_add:
    pattern:   /pets-manager/add/{id}
    defaults: { _controller: DofItemsManagerBundle:PetsManager:add}
    requirements:
        id: \d+

dof_items_manager_pets_del:
    pattern:   /pets-manager/del/{id}
    defaults: { _controller: DofItemsManagerBundle:PetsManager:del}
    requirements:
        id: \d+

dof_items_manager_pets_raise:
    pattern:   /pets-manager/raise/{id}
    defaults: { _controller: DofItemsManagerBundle:PetsManager:raise}
    requirements:
        id: \d+