parameters:
#    dof_generator.example.class: Dof\GeneratorBundle\Example

services:
#    dof_generator.example:
#        class: %dof_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
