dof_admin_users_homepage:
    pattern:  /{page}
    defaults: { _controller: DofAdminBundle:Users:index, page: 1}
    requirements:
        page: \d+

dof_admin_users_delete:
    pattern:  /delete/{id}
    defaults: { _controller: DofAdminBundle:Users:delete}
    requirements:
        _method: DELETE