<?php

// This code is automatically generated by a tool

// You can regenerate it using the command :
// php app/console generate:dof:characteristic

// The template is at :
// src/Dof/GeneratorBundle/Resources/views/ItemBundle/CharacteristicsRangeTrait.php.twig


namespace Dof\Bundle\ItemBundle;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

trait CharacteristicsRangeTrait
{
    /**
     * @var int
     *
     * @ORM\Column(name="min_vitality", type="integer")
     */
    protected $minVitality;

    /**
     * @var int
     *
     * @ORM\Column(name="max_vitality", type="integer")
     */
    protected $maxVitality;

    /**
     * @var int
     *
     * @ORM\Column(name="min_strength", type="integer")
     */
    protected $minStrength;

    /**
     * @var int
     *
     * @ORM\Column(name="max_strength", type="integer")
     */
    protected $maxStrength;

    /**
     * @var int
     *
     * @ORM\Column(name="min_intelligence", type="integer")
     */
    protected $minIntelligence;

    /**
     * @var int
     *
     * @ORM\Column(name="max_intelligence", type="integer")
     */
    protected $maxIntelligence;

    /**
     * @var int
     *
     * @ORM\Column(name="min_chance", type="integer")
     */
    protected $minChance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_chance", type="integer")
     */
    protected $maxChance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_agility", type="integer")
     */
    protected $minAgility;

    /**
     * @var int
     *
     * @ORM\Column(name="max_agility", type="integer")
     */
    protected $maxAgility;

    /**
     * @var int
     *
     * @ORM\Column(name="min_wisdom", type="integer")
     */
    protected $minWisdom;

    /**
     * @var int
     *
     * @ORM\Column(name="max_wisdom", type="integer")
     */
    protected $maxWisdom;

    /**
     * @var int
     *
     * @ORM\Column(name="min_power", type="integer")
     */
    protected $minPower;

    /**
     * @var int
     *
     * @ORM\Column(name="max_power", type="integer")
     */
    protected $maxPower;

    /**
     * @var int
     *
     * @ORM\Column(name="min_ap", type="integer")
     */
    protected $minAp;

    /**
     * @var int
     *
     * @ORM\Column(name="max_ap", type="integer")
     */
    protected $maxAp;

    /**
     * @var int
     *
     * @ORM\Column(name="min_mp", type="integer")
     */
    protected $minMp;

    /**
     * @var int
     *
     * @ORM\Column(name="max_mp", type="integer")
     */
    protected $maxMp;

    /**
     * @var int
     *
     * @ORM\Column(name="min_range", type="integer")
     */
    protected $minRange;

    /**
     * @var int
     *
     * @ORM\Column(name="max_range", type="integer")
     */
    protected $maxRange;

    /**
     * @var int
     *
     * @ORM\Column(name="min_summons", type="integer")
     */
    protected $minSummons;

    /**
     * @var int
     *
     * @ORM\Column(name="max_summons", type="integer")
     */
    protected $maxSummons;

    /**
     * @var int
     *
     * @ORM\Column(name="min_damage", type="integer")
     */
    protected $minDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_damage", type="integer")
     */
    protected $maxDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_neutral_damage", type="integer")
     */
    protected $minNeutralDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_neutral_damage", type="integer")
     */
    protected $maxNeutralDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_earth_damage", type="integer")
     */
    protected $minEarthDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_earth_damage", type="integer")
     */
    protected $maxEarthDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_fire_damage", type="integer")
     */
    protected $minFireDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_fire_damage", type="integer")
     */
    protected $maxFireDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_water_damage", type="integer")
     */
    protected $minWaterDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_water_damage", type="integer")
     */
    protected $maxWaterDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_air_damage", type="integer")
     */
    protected $minAirDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_air_damage", type="integer")
     */
    protected $maxAirDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_heals", type="integer")
     */
    protected $minHeals;

    /**
     * @var int
     *
     * @ORM\Column(name="max_heals", type="integer")
     */
    protected $maxHeals;

    /**
     * @var int
     *
     * @ORM\Column(name="min_prospecting", type="integer")
     */
    protected $minProspecting;

    /**
     * @var int
     *
     * @ORM\Column(name="max_prospecting", type="integer")
     */
    protected $maxProspecting;

    /**
     * @var int
     *
     * @ORM\Column(name="min_initiative", type="integer")
     */
    protected $minInitiative;

    /**
     * @var int
     *
     * @ORM\Column(name="max_initiative", type="integer")
     */
    protected $maxInitiative;

    /**
     * @var int
     *
     * @ORM\Column(name="min_reflected_damage", type="integer")
     */
    protected $minReflectedDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_reflected_damage", type="integer")
     */
    protected $maxReflectedDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_percent_neutral_resistance", type="integer")
     */
    protected $minPercentNeutralResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_percent_neutral_resistance", type="integer")
     */
    protected $maxPercentNeutralResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_percent_water_resistance", type="integer")
     */
    protected $minPercentWaterResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_percent_water_resistance", type="integer")
     */
    protected $maxPercentWaterResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_neutral_resistance", type="integer")
     */
    protected $minNeutralResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_neutral_resistance", type="integer")
     */
    protected $maxNeutralResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_earth_resistance", type="integer")
     */
    protected $minEarthResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_earth_resistance", type="integer")
     */
    protected $maxEarthResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_fire_resistance", type="integer")
     */
    protected $minFireResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_fire_resistance", type="integer")
     */
    protected $maxFireResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_water_resistance", type="integer")
     */
    protected $minWaterResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_water_resistance", type="integer")
     */
    protected $maxWaterResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_air_resistance", type="integer")
     */
    protected $minAirResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_air_resistance", type="integer")
     */
    protected $maxAirResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_neutral_resistance_in_pvp", type="integer")
     */
    protected $minNeutralResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="max_neutral_resistance_in_pvp", type="integer")
     */
    protected $maxNeutralResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="min_earth_resistance_in_pvp", type="integer")
     */
    protected $minEarthResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="max_earth_resistance_in_pvp", type="integer")
     */
    protected $maxEarthResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="min_fire_resistance_in_pvp", type="integer")
     */
    protected $minFireResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="max_fire_resistance_in_pvp", type="integer")
     */
    protected $maxFireResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="min_water_resistance_in_pvp", type="integer")
     */
    protected $minWaterResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="max_water_resistance_in_pvp", type="integer")
     */
    protected $maxWaterResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="min_air_resistance_in_pvp", type="integer")
     */
    protected $minAirResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="max_air_resistance_in_pvp", type="integer")
     */
    protected $maxAirResistanceInPvp;

    /**
     * @var int
     *
     * @ORM\Column(name="min_lock", type="integer")
     */
    protected $minLock;

    /**
     * @var int
     *
     * @ORM\Column(name="max_lock", type="integer")
     */
    protected $maxLock;

    /**
     * @var int
     *
     * @ORM\Column(name="min_dodge", type="integer")
     */
    protected $minDodge;

    /**
     * @var int
     *
     * @ORM\Column(name="max_dodge", type="integer")
     */
    protected $maxDodge;

    /**
     * @var int
     *
     * @ORM\Column(name="min_ap_reduction", type="integer")
     */
    protected $minApReduction;

    /**
     * @var int
     *
     * @ORM\Column(name="max_ap_reduction", type="integer")
     */
    protected $maxApReduction;

    /**
     * @var int
     *
     * @ORM\Column(name="min_mp_reduction", type="integer")
     */
    protected $minMpReduction;

    /**
     * @var int
     *
     * @ORM\Column(name="max_mp_reduction", type="integer")
     */
    protected $maxMpReduction;

    /**
     * @var int
     *
     * @ORM\Column(name="min_ap_loss_resistance", type="integer")
     */
    protected $minApLossResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_ap_loss_resistance", type="integer")
     */
    protected $maxApLossResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_mp_loss_resistance", type="integer")
     */
    protected $minMpLossResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_mp_loss_resistance", type="integer")
     */
    protected $maxMpLossResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_critical_damage", type="integer")
     */
    protected $minCriticalDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_critical_damage", type="integer")
     */
    protected $maxCriticalDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_critical_resistance", type="integer")
     */
    protected $minCriticalResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_critical_resistance", type="integer")
     */
    protected $maxCriticalResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_pushback_damage", type="integer")
     */
    protected $minPushbackDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_pushback_damage", type="integer")
     */
    protected $maxPushbackDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="min_pushback_resistance", type="integer")
     */
    protected $minPushbackResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="max_pushback_resistance", type="integer")
     */
    protected $maxPushbackResistance;

    /**
     * @var int
     *
     * @ORM\Column(name="min_trap_power", type="integer")
     */
    protected $minTrapPower;

    /**
     * @var int
     *
     * @ORM\Column(name="max_trap_power", type="integer")
     */
    protected $maxTrapPower;

    /**
     * @var int
     *
     * @ORM\Column(name="min_trap_damage", type="integer")
     */
    protected $minTrapDamage;

    /**
     * @var int
     *
     * @ORM\Column(name="max_trap_damage", type="integer")
     */
    protected $maxTrapDamage;

    /**
     * Set minVitality.
     *
     * @param int $minVitality
     *
     * @return object
     */
    public function setMinVitality($minVitality)
    {
        $this->minVitality = $minVitality;

        return $this;
    }

    /**
     * Get minVitality.
     *
     * @return int
     */
    public function getMinVitality()
    {
        return $this->minVitality;
    }

    /**
     * Set maxVitality.
     *
     * @param int $maxVitality
     *
     * @return object
     */
    public function setMaxVitality($maxVitality)
    {
        $this->maxVitality = $maxVitality;

        return $this;
    }

    /**
     * Get maxVitality.
     *
     * @return int
     */
    public function getMaxVitality()
    {
        return $this->maxVitality;
    }

    /**
     * Set vitality.
     *
     * @param array $vitality
     *
     * @return object
     */
    public function setVitality(array $vitality)
    {
        $this->minVitality = $vitality['min'];
        $this->maxVitality = $vitality['max'];

        return $this;
    }

    /**
     * Get vitality.
     *
     * @return array
     */
    public function getVitality()
    {
        return ['min' => $this->minVitality, 'max' => $this->maxVitality];
    }

    /**
     * Set minStrength.
     *
     * @param int $minStrength
     *
     * @return object
     */
    public function setMinStrength($minStrength)
    {
        $this->minStrength = $minStrength;

        return $this;
    }

    /**
     * Get minStrength.
     *
     * @return int
     */
    public function getMinStrength()
    {
        return $this->minStrength;
    }

    /**
     * Set maxStrength.
     *
     * @param int $maxStrength
     *
     * @return object
     */
    public function setMaxStrength($maxStrength)
    {
        $this->maxStrength = $maxStrength;

        return $this;
    }

    /**
     * Get maxStrength.
     *
     * @return int
     */
    public function getMaxStrength()
    {
        return $this->maxStrength;
    }

    /**
     * Set strength.
     *
     * @param array $strength
     *
     * @return object
     */
    public function setStrength(array $strength)
    {
        $this->minStrength = $strength['min'];
        $this->maxStrength = $strength['max'];

        return $this;
    }

    /**
     * Get strength.
     *
     * @return array
     */
    public function getStrength()
    {
        return ['min' => $this->minStrength, 'max' => $this->maxStrength];
    }

    /**
     * Set minIntelligence.
     *
     * @param int $minIntelligence
     *
     * @return object
     */
    public function setMinIntelligence($minIntelligence)
    {
        $this->minIntelligence = $minIntelligence;

        return $this;
    }

    /**
     * Get minIntelligence.
     *
     * @return int
     */
    public function getMinIntelligence()
    {
        return $this->minIntelligence;
    }

    /**
     * Set maxIntelligence.
     *
     * @param int $maxIntelligence
     *
     * @return object
     */
    public function setMaxIntelligence($maxIntelligence)
    {
        $this->maxIntelligence = $maxIntelligence;

        return $this;
    }

    /**
     * Get maxIntelligence.
     *
     * @return int
     */
    public function getMaxIntelligence()
    {
        return $this->maxIntelligence;
    }

    /**
     * Set intelligence.
     *
     * @param array $intelligence
     *
     * @return object
     */
    public function setIntelligence(array $intelligence)
    {
        $this->minIntelligence = $intelligence['min'];
        $this->maxIntelligence = $intelligence['max'];

        return $this;
    }

    /**
     * Get intelligence.
     *
     * @return array
     */
    public function getIntelligence()
    {
        return ['min' => $this->minIntelligence, 'max' => $this->maxIntelligence];
    }

    /**
     * Set minChance.
     *
     * @param int $minChance
     *
     * @return object
     */
    public function setMinChance($minChance)
    {
        $this->minChance = $minChance;

        return $this;
    }

    /**
     * Get minChance.
     *
     * @return int
     */
    public function getMinChance()
    {
        return $this->minChance;
    }

    /**
     * Set maxChance.
     *
     * @param int $maxChance
     *
     * @return object
     */
    public function setMaxChance($maxChance)
    {
        $this->maxChance = $maxChance;

        return $this;
    }

    /**
     * Get maxChance.
     *
     * @return int
     */
    public function getMaxChance()
    {
        return $this->maxChance;
    }

    /**
     * Set chance.
     *
     * @param array $chance
     *
     * @return object
     */
    public function setChance(array $chance)
    {
        $this->minChance = $chance['min'];
        $this->maxChance = $chance['max'];

        return $this;
    }

    /**
     * Get chance.
     *
     * @return array
     */
    public function getChance()
    {
        return ['min' => $this->minChance, 'max' => $this->maxChance];
    }

    /**
     * Set minAgility.
     *
     * @param int $minAgility
     *
     * @return object
     */
    public function setMinAgility($minAgility)
    {
        $this->minAgility = $minAgility;

        return $this;
    }

    /**
     * Get minAgility.
     *
     * @return int
     */
    public function getMinAgility()
    {
        return $this->minAgility;
    }

    /**
     * Set maxAgility.
     *
     * @param int $maxAgility
     *
     * @return object
     */
    public function setMaxAgility($maxAgility)
    {
        $this->maxAgility = $maxAgility;

        return $this;
    }

    /**
     * Get maxAgility.
     *
     * @return int
     */
    public function getMaxAgility()
    {
        return $this->maxAgility;
    }

    /**
     * Set agility.
     *
     * @param array $agility
     *
     * @return object
     */
    public function setAgility(array $agility)
    {
        $this->minAgility = $agility['min'];
        $this->maxAgility = $agility['max'];

        return $this;
    }

    /**
     * Get agility.
     *
     * @return array
     */
    public function getAgility()
    {
        return ['min' => $this->minAgility, 'max' => $this->maxAgility];
    }

    /**
     * Set minWisdom.
     *
     * @param int $minWisdom
     *
     * @return object
     */
    public function setMinWisdom($minWisdom)
    {
        $this->minWisdom = $minWisdom;

        return $this;
    }

    /**
     * Get minWisdom.
     *
     * @return int
     */
    public function getMinWisdom()
    {
        return $this->minWisdom;
    }

    /**
     * Set maxWisdom.
     *
     * @param int $maxWisdom
     *
     * @return object
     */
    public function setMaxWisdom($maxWisdom)
    {
        $this->maxWisdom = $maxWisdom;

        return $this;
    }

    /**
     * Get maxWisdom.
     *
     * @return int
     */
    public function getMaxWisdom()
    {
        return $this->maxWisdom;
    }

    /**
     * Set wisdom.
     *
     * @param array $wisdom
     *
     * @return object
     */
    public function setWisdom(array $wisdom)
    {
        $this->minWisdom = $wisdom['min'];
        $this->maxWisdom = $wisdom['max'];

        return $this;
    }

    /**
     * Get wisdom.
     *
     * @return array
     */
    public function getWisdom()
    {
        return ['min' => $this->minWisdom, 'max' => $this->maxWisdom];
    }

    /**
     * Set minPower.
     *
     * @param int $minPower
     *
     * @return object
     */
    public function setMinPower($minPower)
    {
        $this->minPower = $minPower;

        return $this;
    }

    /**
     * Get minPower.
     *
     * @return int
     */
    public function getMinPower()
    {
        return $this->minPower;
    }

    /**
     * Set maxPower.
     *
     * @param int $maxPower
     *
     * @return object
     */
    public function setMaxPower($maxPower)
    {
        $this->maxPower = $maxPower;

        return $this;
    }

    /**
     * Get maxPower.
     *
     * @return int
     */
    public function getMaxPower()
    {
        return $this->maxPower;
    }

    /**
     * Set power.
     *
     * @param array $power
     *
     * @return object
     */
    public function setPower(array $power)
    {
        $this->minPower = $power['min'];
        $this->maxPower = $power['max'];

        return $this;
    }

    /**
     * Get power.
     *
     * @return array
     */
    public function getPower()
    {
        return ['min' => $this->minPower, 'max' => $this->maxPower];
    }

    /**
     * Set minAp.
     *
     * @param int $minAp
     *
     * @return object
     */
    public function setMinAp($minAp)
    {
        $this->minAp = $minAp;

        return $this;
    }

    /**
     * Get minAp.
     *
     * @return int
     */
    public function getMinAp()
    {
        return $this->minAp;
    }

    /**
     * Set maxAp.
     *
     * @param int $maxAp
     *
     * @return object
     */
    public function setMaxAp($maxAp)
    {
        $this->maxAp = $maxAp;

        return $this;
    }

    /**
     * Get maxAp.
     *
     * @return int
     */
    public function getMaxAp()
    {
        return $this->maxAp;
    }

    /**
     * Set ap.
     *
     * @param array $ap
     *
     * @return object
     */
    public function setAp(array $ap)
    {
        $this->minAp = $ap['min'];
        $this->maxAp = $ap['max'];

        return $this;
    }

    /**
     * Get ap.
     *
     * @return array
     */
    public function getAp()
    {
        return ['min' => $this->minAp, 'max' => $this->maxAp];
    }

    /**
     * Set minMp.
     *
     * @param int $minMp
     *
     * @return object
     */
    public function setMinMp($minMp)
    {
        $this->minMp = $minMp;

        return $this;
    }

    /**
     * Get minMp.
     *
     * @return int
     */
    public function getMinMp()
    {
        return $this->minMp;
    }

    /**
     * Set maxMp.
     *
     * @param int $maxMp
     *
     * @return object
     */
    public function setMaxMp($maxMp)
    {
        $this->maxMp = $maxMp;

        return $this;
    }

    /**
     * Get maxMp.
     *
     * @return int
     */
    public function getMaxMp()
    {
        return $this->maxMp;
    }

    /**
     * Set mp.
     *
     * @param array $mp
     *
     * @return object
     */
    public function setMp(array $mp)
    {
        $this->minMp = $mp['min'];
        $this->maxMp = $mp['max'];

        return $this;
    }

    /**
     * Get mp.
     *
     * @return array
     */
    public function getMp()
    {
        return ['min' => $this->minMp, 'max' => $this->maxMp];
    }

    /**
     * Set minRange.
     *
     * @param int $minRange
     *
     * @return object
     */
    public function setMinRange($minRange)
    {
        $this->minRange = $minRange;

        return $this;
    }

    /**
     * Get minRange.
     *
     * @return int
     */
    public function getMinRange()
    {
        return $this->minRange;
    }

    /**
     * Set maxRange.
     *
     * @param int $maxRange
     *
     * @return object
     */
    public function setMaxRange($maxRange)
    {
        $this->maxRange = $maxRange;

        return $this;
    }

    /**
     * Get maxRange.
     *
     * @return int
     */
    public function getMaxRange()
    {
        return $this->maxRange;
    }

    /**
     * Set range.
     *
     * @param array $range
     *
     * @return object
     */
    public function setRange(array $range)
    {
        $this->minRange = $range['min'];
        $this->maxRange = $range['max'];

        return $this;
    }

    /**
     * Get range.
     *
     * @return array
     */
    public function getRange()
    {
        return ['min' => $this->minRange, 'max' => $this->maxRange];
    }

    /**
     * Set minSummons.
     *
     * @param int $minSummons
     *
     * @return object
     */
    public function setMinSummons($minSummons)
    {
        $this->minSummons = $minSummons;

        return $this;
    }

    /**
     * Get minSummons.
     *
     * @return int
     */
    public function getMinSummons()
    {
        return $this->minSummons;
    }

    /**
     * Set maxSummons.
     *
     * @param int $maxSummons
     *
     * @return object
     */
    public function setMaxSummons($maxSummons)
    {
        $this->maxSummons = $maxSummons;

        return $this;
    }

    /**
     * Get maxSummons.
     *
     * @return int
     */
    public function getMaxSummons()
    {
        return $this->maxSummons;
    }

    /**
     * Set summons.
     *
     * @param array $summons
     *
     * @return object
     */
    public function setSummons(array $summons)
    {
        $this->minSummons = $summons['min'];
        $this->maxSummons = $summons['max'];

        return $this;
    }

    /**
     * Get summons.
     *
     * @return array
     */
    public function getSummons()
    {
        return ['min' => $this->minSummons, 'max' => $this->maxSummons];
    }

    /**
     * Set minDamage.
     *
     * @param int $minDamage
     *
     * @return object
     */
    public function setMinDamage($minDamage)
    {
        $this->minDamage = $minDamage;

        return $this;
    }

    /**
     * Get minDamage.
     *
     * @return int
     */
    public function getMinDamage()
    {
        return $this->minDamage;
    }

    /**
     * Set maxDamage.
     *
     * @param int $maxDamage
     *
     * @return object
     */
    public function setMaxDamage($maxDamage)
    {
        $this->maxDamage = $maxDamage;

        return $this;
    }

    /**
     * Get maxDamage.
     *
     * @return int
     */
    public function getMaxDamage()
    {
        return $this->maxDamage;
    }

    /**
     * Set damage.
     *
     * @param array $damage
     *
     * @return object
     */
    public function setDamage(array $damage)
    {
        $this->minDamage = $damage['min'];
        $this->maxDamage = $damage['max'];

        return $this;
    }

    /**
     * Get damage.
     *
     * @return array
     */
    public function getDamage()
    {
        return ['min' => $this->minDamage, 'max' => $this->maxDamage];
    }

    /**
     * Set minNeutralDamage.
     *
     * @param int $minNeutralDamage
     *
     * @return object
     */
    public function setMinNeutralDamage($minNeutralDamage)
    {
        $this->minNeutralDamage = $minNeutralDamage;

        return $this;
    }

    /**
     * Get minNeutralDamage.
     *
     * @return int
     */
    public function getMinNeutralDamage()
    {
        return $this->minNeutralDamage;
    }

    /**
     * Set maxNeutralDamage.
     *
     * @param int $maxNeutralDamage
     *
     * @return object
     */
    public function setMaxNeutralDamage($maxNeutralDamage)
    {
        $this->maxNeutralDamage = $maxNeutralDamage;

        return $this;
    }

    /**
     * Get maxNeutralDamage.
     *
     * @return int
     */
    public function getMaxNeutralDamage()
    {
        return $this->maxNeutralDamage;
    }

    /**
     * Set neutralDamage.
     *
     * @param array $neutralDamage
     *
     * @return object
     */
    public function setNeutralDamage(array $neutralDamage)
    {
        $this->minNeutralDamage = $neutralDamage['min'];
        $this->maxNeutralDamage = $neutralDamage['max'];

        return $this;
    }

    /**
     * Get neutralDamage.
     *
     * @return array
     */
    public function getNeutralDamage()
    {
        return ['min' => $this->minNeutralDamage, 'max' => $this->maxNeutralDamage];
    }

    /**
     * Set minEarthDamage.
     *
     * @param int $minEarthDamage
     *
     * @return object
     */
    public function setMinEarthDamage($minEarthDamage)
    {
        $this->minEarthDamage = $minEarthDamage;

        return $this;
    }

    /**
     * Get minEarthDamage.
     *
     * @return int
     */
    public function getMinEarthDamage()
    {
        return $this->minEarthDamage;
    }

    /**
     * Set maxEarthDamage.
     *
     * @param int $maxEarthDamage
     *
     * @return object
     */
    public function setMaxEarthDamage($maxEarthDamage)
    {
        $this->maxEarthDamage = $maxEarthDamage;

        return $this;
    }

    /**
     * Get maxEarthDamage.
     *
     * @return int
     */
    public function getMaxEarthDamage()
    {
        return $this->maxEarthDamage;
    }

    /**
     * Set earthDamage.
     *
     * @param array $earthDamage
     *
     * @return object
     */
    public function setEarthDamage(array $earthDamage)
    {
        $this->minEarthDamage = $earthDamage['min'];
        $this->maxEarthDamage = $earthDamage['max'];

        return $this;
    }

    /**
     * Get earthDamage.
     *
     * @return array
     */
    public function getEarthDamage()
    {
        return ['min' => $this->minEarthDamage, 'max' => $this->maxEarthDamage];
    }

    /**
     * Set minFireDamage.
     *
     * @param int $minFireDamage
     *
     * @return object
     */
    public function setMinFireDamage($minFireDamage)
    {
        $this->minFireDamage = $minFireDamage;

        return $this;
    }

    /**
     * Get minFireDamage.
     *
     * @return int
     */
    public function getMinFireDamage()
    {
        return $this->minFireDamage;
    }

    /**
     * Set maxFireDamage.
     *
     * @param int $maxFireDamage
     *
     * @return object
     */
    public function setMaxFireDamage($maxFireDamage)
    {
        $this->maxFireDamage = $maxFireDamage;

        return $this;
    }

    /**
     * Get maxFireDamage.
     *
     * @return int
     */
    public function getMaxFireDamage()
    {
        return $this->maxFireDamage;
    }

    /**
     * Set fireDamage.
     *
     * @param array $fireDamage
     *
     * @return object
     */
    public function setFireDamage(array $fireDamage)
    {
        $this->minFireDamage = $fireDamage['min'];
        $this->maxFireDamage = $fireDamage['max'];

        return $this;
    }

    /**
     * Get fireDamage.
     *
     * @return array
     */
    public function getFireDamage()
    {
        return ['min' => $this->minFireDamage, 'max' => $this->maxFireDamage];
    }

    /**
     * Set minWaterDamage.
     *
     * @param int $minWaterDamage
     *
     * @return object
     */
    public function setMinWaterDamage($minWaterDamage)
    {
        $this->minWaterDamage = $minWaterDamage;

        return $this;
    }

    /**
     * Get minWaterDamage.
     *
     * @return int
     */
    public function getMinWaterDamage()
    {
        return $this->minWaterDamage;
    }

    /**
     * Set maxWaterDamage.
     *
     * @param int $maxWaterDamage
     *
     * @return object
     */
    public function setMaxWaterDamage($maxWaterDamage)
    {
        $this->maxWaterDamage = $maxWaterDamage;

        return $this;
    }

    /**
     * Get maxWaterDamage.
     *
     * @return int
     */
    public function getMaxWaterDamage()
    {
        return $this->maxWaterDamage;
    }

    /**
     * Set waterDamage.
     *
     * @param array $waterDamage
     *
     * @return object
     */
    public function setWaterDamage(array $waterDamage)
    {
        $this->minWaterDamage = $waterDamage['min'];
        $this->maxWaterDamage = $waterDamage['max'];

        return $this;
    }

    /**
     * Get waterDamage.
     *
     * @return array
     */
    public function getWaterDamage()
    {
        return ['min' => $this->minWaterDamage, 'max' => $this->maxWaterDamage];
    }

    /**
     * Set minAirDamage.
     *
     * @param int $minAirDamage
     *
     * @return object
     */
    public function setMinAirDamage($minAirDamage)
    {
        $this->minAirDamage = $minAirDamage;

        return $this;
    }

    /**
     * Get minAirDamage.
     *
     * @return int
     */
    public function getMinAirDamage()
    {
        return $this->minAirDamage;
    }

    /**
     * Set maxAirDamage.
     *
     * @param int $maxAirDamage
     *
     * @return object
     */
    public function setMaxAirDamage($maxAirDamage)
    {
        $this->maxAirDamage = $maxAirDamage;

        return $this;
    }

    /**
     * Get maxAirDamage.
     *
     * @return int
     */
    public function getMaxAirDamage()
    {
        return $this->maxAirDamage;
    }

    /**
     * Set airDamage.
     *
     * @param array $airDamage
     *
     * @return object
     */
    public function setAirDamage(array $airDamage)
    {
        $this->minAirDamage = $airDamage['min'];
        $this->maxAirDamage = $airDamage['max'];

        return $this;
    }

    /**
     * Get airDamage.
     *
     * @return array
     */
    public function getAirDamage()
    {
        return ['min' => $this->minAirDamage, 'max' => $this->maxAirDamage];
    }

    /**
     * Set minHeals.
     *
     * @param int $minHeals
     *
     * @return object
     */
    public function setMinHeals($minHeals)
    {
        $this->minHeals = $minHeals;

        return $this;
    }

    /**
     * Get minHeals.
     *
     * @return int
     */
    public function getMinHeals()
    {
        return $this->minHeals;
    }

    /**
     * Set maxHeals.
     *
     * @param int $maxHeals
     *
     * @return object
     */
    public function setMaxHeals($maxHeals)
    {
        $this->maxHeals = $maxHeals;

        return $this;
    }

    /**
     * Get maxHeals.
     *
     * @return int
     */
    public function getMaxHeals()
    {
        return $this->maxHeals;
    }

    /**
     * Set heals.
     *
     * @param array $heals
     *
     * @return object
     */
    public function setHeals(array $heals)
    {
        $this->minHeals = $heals['min'];
        $this->maxHeals = $heals['max'];

        return $this;
    }

    /**
     * Get heals.
     *
     * @return array
     */
    public function getHeals()
    {
        return ['min' => $this->minHeals, 'max' => $this->maxHeals];
    }

    /**
     * Set minProspecting.
     *
     * @param int $minProspecting
     *
     * @return object
     */
    public function setMinProspecting($minProspecting)
    {
        $this->minProspecting = $minProspecting;

        return $this;
    }

    /**
     * Get minProspecting.
     *
     * @return int
     */
    public function getMinProspecting()
    {
        return $this->minProspecting;
    }

    /**
     * Set maxProspecting.
     *
     * @param int $maxProspecting
     *
     * @return object
     */
    public function setMaxProspecting($maxProspecting)
    {
        $this->maxProspecting = $maxProspecting;

        return $this;
    }

    /**
     * Get maxProspecting.
     *
     * @return int
     */
    public function getMaxProspecting()
    {
        return $this->maxProspecting;
    }

    /**
     * Set prospecting.
     *
     * @param array $prospecting
     *
     * @return object
     */
    public function setProspecting(array $prospecting)
    {
        $this->minProspecting = $prospecting['min'];
        $this->maxProspecting = $prospecting['max'];

        return $this;
    }

    /**
     * Get prospecting.
     *
     * @return array
     */
    public function getProspecting()
    {
        return ['min' => $this->minProspecting, 'max' => $this->maxProspecting];
    }

    /**
     * Set minInitiative.
     *
     * @param int $minInitiative
     *
     * @return object
     */
    public function setMinInitiative($minInitiative)
    {
        $this->minInitiative = $minInitiative;

        return $this;
    }

    /**
     * Get minInitiative.
     *
     * @return int
     */
    public function getMinInitiative()
    {
        return $this->minInitiative;
    }

    /**
     * Set maxInitiative.
     *
     * @param int $maxInitiative
     *
     * @return object
     */
    public function setMaxInitiative($maxInitiative)
    {
        $this->maxInitiative = $maxInitiative;

        return $this;
    }

    /**
     * Get maxInitiative.
     *
     * @return int
     */
    public function getMaxInitiative()
    {
        return $this->maxInitiative;
    }

    /**
     * Set initiative.
     *
     * @param array $initiative
     *
     * @return object
     */
    public function setInitiative(array $initiative)
    {
        $this->minInitiative = $initiative['min'];
        $this->maxInitiative = $initiative['max'];

        return $this;
    }

    /**
     * Get initiative.
     *
     * @return array
     */
    public function getInitiative()
    {
        return ['min' => $this->minInitiative, 'max' => $this->maxInitiative];
    }

    /**
     * Set minReflectedDamage.
     *
     * @param int $minReflectedDamage
     *
     * @return object
     */
    public function setMinReflectedDamage($minReflectedDamage)
    {
        $this->minReflectedDamage = $minReflectedDamage;

        return $this;
    }

    /**
     * Get minReflectedDamage.
     *
     * @return int
     */
    public function getMinReflectedDamage()
    {
        return $this->minReflectedDamage;
    }

    /**
     * Set maxReflectedDamage.
     *
     * @param int $maxReflectedDamage
     *
     * @return object
     */
    public function setMaxReflectedDamage($maxReflectedDamage)
    {
        $this->maxReflectedDamage = $maxReflectedDamage;

        return $this;
    }

    /**
     * Get maxReflectedDamage.
     *
     * @return int
     */
    public function getMaxReflectedDamage()
    {
        return $this->maxReflectedDamage;
    }

    /**
     * Set reflectedDamage.
     *
     * @param array $reflectedDamage
     *
     * @return object
     */
    public function setReflectedDamage(array $reflectedDamage)
    {
        $this->minReflectedDamage = $reflectedDamage['min'];
        $this->maxReflectedDamage = $reflectedDamage['max'];

        return $this;
    }

    /**
     * Get reflectedDamage.
     *
     * @return array
     */
    public function getReflectedDamage()
    {
        return ['min' => $this->minReflectedDamage, 'max' => $this->maxReflectedDamage];
    }

    /**
     * Set minPercentNeutralResistance.
     *
     * @param int $minPercentNeutralResistance
     *
     * @return object
     */
    public function setMinPercentNeutralResistance($minPercentNeutralResistance)
    {
        $this->minPercentNeutralResistance = $minPercentNeutralResistance;

        return $this;
    }

    /**
     * Get minPercentNeutralResistance.
     *
     * @return int
     */
    public function getMinPercentNeutralResistance()
    {
        return $this->minPercentNeutralResistance;
    }

    /**
     * Set maxPercentNeutralResistance.
     *
     * @param int $maxPercentNeutralResistance
     *
     * @return object
     */
    public function setMaxPercentNeutralResistance($maxPercentNeutralResistance)
    {
        $this->maxPercentNeutralResistance = $maxPercentNeutralResistance;

        return $this;
    }

    /**
     * Get maxPercentNeutralResistance.
     *
     * @return int
     */
    public function getMaxPercentNeutralResistance()
    {
        return $this->maxPercentNeutralResistance;
    }

    /**
     * Set percentNeutralResistance.
     *
     * @param array $percentNeutralResistance
     *
     * @return object
     */
    public function setPercentNeutralResistance(array $percentNeutralResistance)
    {
        $this->minPercentNeutralResistance = $percentNeutralResistance['min'];
        $this->maxPercentNeutralResistance = $percentNeutralResistance['max'];

        return $this;
    }

    /**
     * Get percentNeutralResistance.
     *
     * @return array
     */
    public function getPercentNeutralResistance()
    {
        return ['min' => $this->minPercentNeutralResistance, 'max' => $this->maxPercentNeutralResistance];
    }

    /**
     * Set minPercentWaterResistance.
     *
     * @param int $minPercentWaterResistance
     *
     * @return object
     */
    public function setMinPercentWaterResistance($minPercentWaterResistance)
    {
        $this->minPercentWaterResistance = $minPercentWaterResistance;

        return $this;
    }

    /**
     * Get minPercentWaterResistance.
     *
     * @return int
     */
    public function getMinPercentWaterResistance()
    {
        return $this->minPercentWaterResistance;
    }

    /**
     * Set maxPercentWaterResistance.
     *
     * @param int $maxPercentWaterResistance
     *
     * @return object
     */
    public function setMaxPercentWaterResistance($maxPercentWaterResistance)
    {
        $this->maxPercentWaterResistance = $maxPercentWaterResistance;

        return $this;
    }

    /**
     * Get maxPercentWaterResistance.
     *
     * @return int
     */
    public function getMaxPercentWaterResistance()
    {
        return $this->maxPercentWaterResistance;
    }

    /**
     * Set percentWaterResistance.
     *
     * @param array $percentWaterResistance
     *
     * @return object
     */
    public function setPercentWaterResistance(array $percentWaterResistance)
    {
        $this->minPercentWaterResistance = $percentWaterResistance['min'];
        $this->maxPercentWaterResistance = $percentWaterResistance['max'];

        return $this;
    }

    /**
     * Get percentWaterResistance.
     *
     * @return array
     */
    public function getPercentWaterResistance()
    {
        return ['min' => $this->minPercentWaterResistance, 'max' => $this->maxPercentWaterResistance];
    }

    /**
     * Set minNeutralResistance.
     *
     * @param int $minNeutralResistance
     *
     * @return object
     */
    public function setMinNeutralResistance($minNeutralResistance)
    {
        $this->minNeutralResistance = $minNeutralResistance;

        return $this;
    }

    /**
     * Get minNeutralResistance.
     *
     * @return int
     */
    public function getMinNeutralResistance()
    {
        return $this->minNeutralResistance;
    }

    /**
     * Set maxNeutralResistance.
     *
     * @param int $maxNeutralResistance
     *
     * @return object
     */
    public function setMaxNeutralResistance($maxNeutralResistance)
    {
        $this->maxNeutralResistance = $maxNeutralResistance;

        return $this;
    }

    /**
     * Get maxNeutralResistance.
     *
     * @return int
     */
    public function getMaxNeutralResistance()
    {
        return $this->maxNeutralResistance;
    }

    /**
     * Set neutralResistance.
     *
     * @param array $neutralResistance
     *
     * @return object
     */
    public function setNeutralResistance(array $neutralResistance)
    {
        $this->minNeutralResistance = $neutralResistance['min'];
        $this->maxNeutralResistance = $neutralResistance['max'];

        return $this;
    }

    /**
     * Get neutralResistance.
     *
     * @return array
     */
    public function getNeutralResistance()
    {
        return ['min' => $this->minNeutralResistance, 'max' => $this->maxNeutralResistance];
    }

    /**
     * Set minEarthResistance.
     *
     * @param int $minEarthResistance
     *
     * @return object
     */
    public function setMinEarthResistance($minEarthResistance)
    {
        $this->minEarthResistance = $minEarthResistance;

        return $this;
    }

    /**
     * Get minEarthResistance.
     *
     * @return int
     */
    public function getMinEarthResistance()
    {
        return $this->minEarthResistance;
    }

    /**
     * Set maxEarthResistance.
     *
     * @param int $maxEarthResistance
     *
     * @return object
     */
    public function setMaxEarthResistance($maxEarthResistance)
    {
        $this->maxEarthResistance = $maxEarthResistance;

        return $this;
    }

    /**
     * Get maxEarthResistance.
     *
     * @return int
     */
    public function getMaxEarthResistance()
    {
        return $this->maxEarthResistance;
    }

    /**
     * Set earthResistance.
     *
     * @param array $earthResistance
     *
     * @return object
     */
    public function setEarthResistance(array $earthResistance)
    {
        $this->minEarthResistance = $earthResistance['min'];
        $this->maxEarthResistance = $earthResistance['max'];

        return $this;
    }

    /**
     * Get earthResistance.
     *
     * @return array
     */
    public function getEarthResistance()
    {
        return ['min' => $this->minEarthResistance, 'max' => $this->maxEarthResistance];
    }

    /**
     * Set minFireResistance.
     *
     * @param int $minFireResistance
     *
     * @return object
     */
    public function setMinFireResistance($minFireResistance)
    {
        $this->minFireResistance = $minFireResistance;

        return $this;
    }

    /**
     * Get minFireResistance.
     *
     * @return int
     */
    public function getMinFireResistance()
    {
        return $this->minFireResistance;
    }

    /**
     * Set maxFireResistance.
     *
     * @param int $maxFireResistance
     *
     * @return object
     */
    public function setMaxFireResistance($maxFireResistance)
    {
        $this->maxFireResistance = $maxFireResistance;

        return $this;
    }

    /**
     * Get maxFireResistance.
     *
     * @return int
     */
    public function getMaxFireResistance()
    {
        return $this->maxFireResistance;
    }

    /**
     * Set fireResistance.
     *
     * @param array $fireResistance
     *
     * @return object
     */
    public function setFireResistance(array $fireResistance)
    {
        $this->minFireResistance = $fireResistance['min'];
        $this->maxFireResistance = $fireResistance['max'];

        return $this;
    }

    /**
     * Get fireResistance.
     *
     * @return array
     */
    public function getFireResistance()
    {
        return ['min' => $this->minFireResistance, 'max' => $this->maxFireResistance];
    }

    /**
     * Set minWaterResistance.
     *
     * @param int $minWaterResistance
     *
     * @return object
     */
    public function setMinWaterResistance($minWaterResistance)
    {
        $this->minWaterResistance = $minWaterResistance;

        return $this;
    }

    /**
     * Get minWaterResistance.
     *
     * @return int
     */
    public function getMinWaterResistance()
    {
        return $this->minWaterResistance;
    }

    /**
     * Set maxWaterResistance.
     *
     * @param int $maxWaterResistance
     *
     * @return object
     */
    public function setMaxWaterResistance($maxWaterResistance)
    {
        $this->maxWaterResistance = $maxWaterResistance;

        return $this;
    }

    /**
     * Get maxWaterResistance.
     *
     * @return int
     */
    public function getMaxWaterResistance()
    {
        return $this->maxWaterResistance;
    }

    /**
     * Set waterResistance.
     *
     * @param array $waterResistance
     *
     * @return object
     */
    public function setWaterResistance(array $waterResistance)
    {
        $this->minWaterResistance = $waterResistance['min'];
        $this->maxWaterResistance = $waterResistance['max'];

        return $this;
    }

    /**
     * Get waterResistance.
     *
     * @return array
     */
    public function getWaterResistance()
    {
        return ['min' => $this->minWaterResistance, 'max' => $this->maxWaterResistance];
    }

    /**
     * Set minAirResistance.
     *
     * @param int $minAirResistance
     *
     * @return object
     */
    public function setMinAirResistance($minAirResistance)
    {
        $this->minAirResistance = $minAirResistance;

        return $this;
    }

    /**
     * Get minAirResistance.
     *
     * @return int
     */
    public function getMinAirResistance()
    {
        return $this->minAirResistance;
    }

    /**
     * Set maxAirResistance.
     *
     * @param int $maxAirResistance
     *
     * @return object
     */
    public function setMaxAirResistance($maxAirResistance)
    {
        $this->maxAirResistance = $maxAirResistance;

        return $this;
    }

    /**
     * Get maxAirResistance.
     *
     * @return int
     */
    public function getMaxAirResistance()
    {
        return $this->maxAirResistance;
    }

    /**
     * Set airResistance.
     *
     * @param array $airResistance
     *
     * @return object
     */
    public function setAirResistance(array $airResistance)
    {
        $this->minAirResistance = $airResistance['min'];
        $this->maxAirResistance = $airResistance['max'];

        return $this;
    }

    /**
     * Get airResistance.
     *
     * @return array
     */
    public function getAirResistance()
    {
        return ['min' => $this->minAirResistance, 'max' => $this->maxAirResistance];
    }

    /**
     * Set minNeutralResistanceInPvp.
     *
     * @param int $minNeutralResistanceInPvp
     *
     * @return object
     */
    public function setMinNeutralResistanceInPvp($minNeutralResistanceInPvp)
    {
        $this->minNeutralResistanceInPvp = $minNeutralResistanceInPvp;

        return $this;
    }

    /**
     * Get minNeutralResistanceInPvp.
     *
     * @return int
     */
    public function getMinNeutralResistanceInPvp()
    {
        return $this->minNeutralResistanceInPvp;
    }

    /**
     * Set maxNeutralResistanceInPvp.
     *
     * @param int $maxNeutralResistanceInPvp
     *
     * @return object
     */
    public function setMaxNeutralResistanceInPvp($maxNeutralResistanceInPvp)
    {
        $this->maxNeutralResistanceInPvp = $maxNeutralResistanceInPvp;

        return $this;
    }

    /**
     * Get maxNeutralResistanceInPvp.
     *
     * @return int
     */
    public function getMaxNeutralResistanceInPvp()
    {
        return $this->maxNeutralResistanceInPvp;
    }

    /**
     * Set neutralResistanceInPvp.
     *
     * @param array $neutralResistanceInPvp
     *
     * @return object
     */
    public function setNeutralResistanceInPvp(array $neutralResistanceInPvp)
    {
        $this->minNeutralResistanceInPvp = $neutralResistanceInPvp['min'];
        $this->maxNeutralResistanceInPvp = $neutralResistanceInPvp['max'];

        return $this;
    }

    /**
     * Get neutralResistanceInPvp.
     *
     * @return array
     */
    public function getNeutralResistanceInPvp()
    {
        return ['min' => $this->minNeutralResistanceInPvp, 'max' => $this->maxNeutralResistanceInPvp];
    }

    /**
     * Set minEarthResistanceInPvp.
     *
     * @param int $minEarthResistanceInPvp
     *
     * @return object
     */
    public function setMinEarthResistanceInPvp($minEarthResistanceInPvp)
    {
        $this->minEarthResistanceInPvp = $minEarthResistanceInPvp;

        return $this;
    }

    /**
     * Get minEarthResistanceInPvp.
     *
     * @return int
     */
    public function getMinEarthResistanceInPvp()
    {
        return $this->minEarthResistanceInPvp;
    }

    /**
     * Set maxEarthResistanceInPvp.
     *
     * @param int $maxEarthResistanceInPvp
     *
     * @return object
     */
    public function setMaxEarthResistanceInPvp($maxEarthResistanceInPvp)
    {
        $this->maxEarthResistanceInPvp = $maxEarthResistanceInPvp;

        return $this;
    }

    /**
     * Get maxEarthResistanceInPvp.
     *
     * @return int
     */
    public function getMaxEarthResistanceInPvp()
    {
        return $this->maxEarthResistanceInPvp;
    }

    /**
     * Set earthResistanceInPvp.
     *
     * @param array $earthResistanceInPvp
     *
     * @return object
     */
    public function setEarthResistanceInPvp(array $earthResistanceInPvp)
    {
        $this->minEarthResistanceInPvp = $earthResistanceInPvp['min'];
        $this->maxEarthResistanceInPvp = $earthResistanceInPvp['max'];

        return $this;
    }

    /**
     * Get earthResistanceInPvp.
     *
     * @return array
     */
    public function getEarthResistanceInPvp()
    {
        return ['min' => $this->minEarthResistanceInPvp, 'max' => $this->maxEarthResistanceInPvp];
    }

    /**
     * Set minFireResistanceInPvp.
     *
     * @param int $minFireResistanceInPvp
     *
     * @return object
     */
    public function setMinFireResistanceInPvp($minFireResistanceInPvp)
    {
        $this->minFireResistanceInPvp = $minFireResistanceInPvp;

        return $this;
    }

    /**
     * Get minFireResistanceInPvp.
     *
     * @return int
     */
    public function getMinFireResistanceInPvp()
    {
        return $this->minFireResistanceInPvp;
    }

    /**
     * Set maxFireResistanceInPvp.
     *
     * @param int $maxFireResistanceInPvp
     *
     * @return object
     */
    public function setMaxFireResistanceInPvp($maxFireResistanceInPvp)
    {
        $this->maxFireResistanceInPvp = $maxFireResistanceInPvp;

        return $this;
    }

    /**
     * Get maxFireResistanceInPvp.
     *
     * @return int
     */
    public function getMaxFireResistanceInPvp()
    {
        return $this->maxFireResistanceInPvp;
    }

    /**
     * Set fireResistanceInPvp.
     *
     * @param array $fireResistanceInPvp
     *
     * @return object
     */
    public function setFireResistanceInPvp(array $fireResistanceInPvp)
    {
        $this->minFireResistanceInPvp = $fireResistanceInPvp['min'];
        $this->maxFireResistanceInPvp = $fireResistanceInPvp['max'];

        return $this;
    }

    /**
     * Get fireResistanceInPvp.
     *
     * @return array
     */
    public function getFireResistanceInPvp()
    {
        return ['min' => $this->minFireResistanceInPvp, 'max' => $this->maxFireResistanceInPvp];
    }

    /**
     * Set minWaterResistanceInPvp.
     *
     * @param int $minWaterResistanceInPvp
     *
     * @return object
     */
    public function setMinWaterResistanceInPvp($minWaterResistanceInPvp)
    {
        $this->minWaterResistanceInPvp = $minWaterResistanceInPvp;

        return $this;
    }

    /**
     * Get minWaterResistanceInPvp.
     *
     * @return int
     */
    public function getMinWaterResistanceInPvp()
    {
        return $this->minWaterResistanceInPvp;
    }

    /**
     * Set maxWaterResistanceInPvp.
     *
     * @param int $maxWaterResistanceInPvp
     *
     * @return object
     */
    public function setMaxWaterResistanceInPvp($maxWaterResistanceInPvp)
    {
        $this->maxWaterResistanceInPvp = $maxWaterResistanceInPvp;

        return $this;
    }

    /**
     * Get maxWaterResistanceInPvp.
     *
     * @return int
     */
    public function getMaxWaterResistanceInPvp()
    {
        return $this->maxWaterResistanceInPvp;
    }

    /**
     * Set waterResistanceInPvp.
     *
     * @param array $waterResistanceInPvp
     *
     * @return object
     */
    public function setWaterResistanceInPvp(array $waterResistanceInPvp)
    {
        $this->minWaterResistanceInPvp = $waterResistanceInPvp['min'];
        $this->maxWaterResistanceInPvp = $waterResistanceInPvp['max'];

        return $this;
    }

    /**
     * Get waterResistanceInPvp.
     *
     * @return array
     */
    public function getWaterResistanceInPvp()
    {
        return ['min' => $this->minWaterResistanceInPvp, 'max' => $this->maxWaterResistanceInPvp];
    }

    /**
     * Set minAirResistanceInPvp.
     *
     * @param int $minAirResistanceInPvp
     *
     * @return object
     */
    public function setMinAirResistanceInPvp($minAirResistanceInPvp)
    {
        $this->minAirResistanceInPvp = $minAirResistanceInPvp;

        return $this;
    }

    /**
     * Get minAirResistanceInPvp.
     *
     * @return int
     */
    public function getMinAirResistanceInPvp()
    {
        return $this->minAirResistanceInPvp;
    }

    /**
     * Set maxAirResistanceInPvp.
     *
     * @param int $maxAirResistanceInPvp
     *
     * @return object
     */
    public function setMaxAirResistanceInPvp($maxAirResistanceInPvp)
    {
        $this->maxAirResistanceInPvp = $maxAirResistanceInPvp;

        return $this;
    }

    /**
     * Get maxAirResistanceInPvp.
     *
     * @return int
     */
    public function getMaxAirResistanceInPvp()
    {
        return $this->maxAirResistanceInPvp;
    }

    /**
     * Set airResistanceInPvp.
     *
     * @param array $airResistanceInPvp
     *
     * @return object
     */
    public function setAirResistanceInPvp(array $airResistanceInPvp)
    {
        $this->minAirResistanceInPvp = $airResistanceInPvp['min'];
        $this->maxAirResistanceInPvp = $airResistanceInPvp['max'];

        return $this;
    }

    /**
     * Get airResistanceInPvp.
     *
     * @return array
     */
    public function getAirResistanceInPvp()
    {
        return ['min' => $this->minAirResistanceInPvp, 'max' => $this->maxAirResistanceInPvp];
    }

    /**
     * Set minLock.
     *
     * @param int $minLock
     *
     * @return object
     */
    public function setMinLock($minLock)
    {
        $this->minLock = $minLock;

        return $this;
    }

    /**
     * Get minLock.
     *
     * @return int
     */
    public function getMinLock()
    {
        return $this->minLock;
    }

    /**
     * Set maxLock.
     *
     * @param int $maxLock
     *
     * @return object
     */
    public function setMaxLock($maxLock)
    {
        $this->maxLock = $maxLock;

        return $this;
    }

    /**
     * Get maxLock.
     *
     * @return int
     */
    public function getMaxLock()
    {
        return $this->maxLock;
    }

    /**
     * Set lock.
     *
     * @param array $lock
     *
     * @return object
     */
    public function setLock(array $lock)
    {
        $this->minLock = $lock['min'];
        $this->maxLock = $lock['max'];

        return $this;
    }

    /**
     * Get lock.
     *
     * @return array
     */
    public function getLock()
    {
        return ['min' => $this->minLock, 'max' => $this->maxLock];
    }

    /**
     * Set minDodge.
     *
     * @param int $minDodge
     *
     * @return object
     */
    public function setMinDodge($minDodge)
    {
        $this->minDodge = $minDodge;

        return $this;
    }

    /**
     * Get minDodge.
     *
     * @return int
     */
    public function getMinDodge()
    {
        return $this->minDodge;
    }

    /**
     * Set maxDodge.
     *
     * @param int $maxDodge
     *
     * @return object
     */
    public function setMaxDodge($maxDodge)
    {
        $this->maxDodge = $maxDodge;

        return $this;
    }

    /**
     * Get maxDodge.
     *
     * @return int
     */
    public function getMaxDodge()
    {
        return $this->maxDodge;
    }

    /**
     * Set dodge.
     *
     * @param array $dodge
     *
     * @return object
     */
    public function setDodge(array $dodge)
    {
        $this->minDodge = $dodge['min'];
        $this->maxDodge = $dodge['max'];

        return $this;
    }

    /**
     * Get dodge.
     *
     * @return array
     */
    public function getDodge()
    {
        return ['min' => $this->minDodge, 'max' => $this->maxDodge];
    }

    /**
     * Set minApReduction.
     *
     * @param int $minApReduction
     *
     * @return object
     */
    public function setMinApReduction($minApReduction)
    {
        $this->minApReduction = $minApReduction;

        return $this;
    }

    /**
     * Get minApReduction.
     *
     * @return int
     */
    public function getMinApReduction()
    {
        return $this->minApReduction;
    }

    /**
     * Set maxApReduction.
     *
     * @param int $maxApReduction
     *
     * @return object
     */
    public function setMaxApReduction($maxApReduction)
    {
        $this->maxApReduction = $maxApReduction;

        return $this;
    }

    /**
     * Get maxApReduction.
     *
     * @return int
     */
    public function getMaxApReduction()
    {
        return $this->maxApReduction;
    }

    /**
     * Set apReduction.
     *
     * @param array $apReduction
     *
     * @return object
     */
    public function setApReduction(array $apReduction)
    {
        $this->minApReduction = $apReduction['min'];
        $this->maxApReduction = $apReduction['max'];

        return $this;
    }

    /**
     * Get apReduction.
     *
     * @return array
     */
    public function getApReduction()
    {
        return ['min' => $this->minApReduction, 'max' => $this->maxApReduction];
    }

    /**
     * Set minMpReduction.
     *
     * @param int $minMpReduction
     *
     * @return object
     */
    public function setMinMpReduction($minMpReduction)
    {
        $this->minMpReduction = $minMpReduction;

        return $this;
    }

    /**
     * Get minMpReduction.
     *
     * @return int
     */
    public function getMinMpReduction()
    {
        return $this->minMpReduction;
    }

    /**
     * Set maxMpReduction.
     *
     * @param int $maxMpReduction
     *
     * @return object
     */
    public function setMaxMpReduction($maxMpReduction)
    {
        $this->maxMpReduction = $maxMpReduction;

        return $this;
    }

    /**
     * Get maxMpReduction.
     *
     * @return int
     */
    public function getMaxMpReduction()
    {
        return $this->maxMpReduction;
    }

    /**
     * Set mpReduction.
     *
     * @param array $mpReduction
     *
     * @return object
     */
    public function setMpReduction(array $mpReduction)
    {
        $this->minMpReduction = $mpReduction['min'];
        $this->maxMpReduction = $mpReduction['max'];

        return $this;
    }

    /**
     * Get mpReduction.
     *
     * @return array
     */
    public function getMpReduction()
    {
        return ['min' => $this->minMpReduction, 'max' => $this->maxMpReduction];
    }

    /**
     * Set minApLossResistance.
     *
     * @param int $minApLossResistance
     *
     * @return object
     */
    public function setMinApLossResistance($minApLossResistance)
    {
        $this->minApLossResistance = $minApLossResistance;

        return $this;
    }

    /**
     * Get minApLossResistance.
     *
     * @return int
     */
    public function getMinApLossResistance()
    {
        return $this->minApLossResistance;
    }

    /**
     * Set maxApLossResistance.
     *
     * @param int $maxApLossResistance
     *
     * @return object
     */
    public function setMaxApLossResistance($maxApLossResistance)
    {
        $this->maxApLossResistance = $maxApLossResistance;

        return $this;
    }

    /**
     * Get maxApLossResistance.
     *
     * @return int
     */
    public function getMaxApLossResistance()
    {
        return $this->maxApLossResistance;
    }

    /**
     * Set apLossResistance.
     *
     * @param array $apLossResistance
     *
     * @return object
     */
    public function setApLossResistance(array $apLossResistance)
    {
        $this->minApLossResistance = $apLossResistance['min'];
        $this->maxApLossResistance = $apLossResistance['max'];

        return $this;
    }

    /**
     * Get apLossResistance.
     *
     * @return array
     */
    public function getApLossResistance()
    {
        return ['min' => $this->minApLossResistance, 'max' => $this->maxApLossResistance];
    }

    /**
     * Set minMpLossResistance.
     *
     * @param int $minMpLossResistance
     *
     * @return object
     */
    public function setMinMpLossResistance($minMpLossResistance)
    {
        $this->minMpLossResistance = $minMpLossResistance;

        return $this;
    }

    /**
     * Get minMpLossResistance.
     *
     * @return int
     */
    public function getMinMpLossResistance()
    {
        return $this->minMpLossResistance;
    }

    /**
     * Set maxMpLossResistance.
     *
     * @param int $maxMpLossResistance
     *
     * @return object
     */
    public function setMaxMpLossResistance($maxMpLossResistance)
    {
        $this->maxMpLossResistance = $maxMpLossResistance;

        return $this;
    }

    /**
     * Get maxMpLossResistance.
     *
     * @return int
     */
    public function getMaxMpLossResistance()
    {
        return $this->maxMpLossResistance;
    }

    /**
     * Set mpLossResistance.
     *
     * @param array $mpLossResistance
     *
     * @return object
     */
    public function setMpLossResistance(array $mpLossResistance)
    {
        $this->minMpLossResistance = $mpLossResistance['min'];
        $this->maxMpLossResistance = $mpLossResistance['max'];

        return $this;
    }

    /**
     * Get mpLossResistance.
     *
     * @return array
     */
    public function getMpLossResistance()
    {
        return ['min' => $this->minMpLossResistance, 'max' => $this->maxMpLossResistance];
    }

    /**
     * Set minCriticalDamage.
     *
     * @param int $minCriticalDamage
     *
     * @return object
     */
    public function setMinCriticalDamage($minCriticalDamage)
    {
        $this->minCriticalDamage = $minCriticalDamage;

        return $this;
    }

    /**
     * Get minCriticalDamage.
     *
     * @return int
     */
    public function getMinCriticalDamage()
    {
        return $this->minCriticalDamage;
    }

    /**
     * Set maxCriticalDamage.
     *
     * @param int $maxCriticalDamage
     *
     * @return object
     */
    public function setMaxCriticalDamage($maxCriticalDamage)
    {
        $this->maxCriticalDamage = $maxCriticalDamage;

        return $this;
    }

    /**
     * Get maxCriticalDamage.
     *
     * @return int
     */
    public function getMaxCriticalDamage()
    {
        return $this->maxCriticalDamage;
    }

    /**
     * Set criticalDamage.
     *
     * @param array $criticalDamage
     *
     * @return object
     */
    public function setCriticalDamage(array $criticalDamage)
    {
        $this->minCriticalDamage = $criticalDamage['min'];
        $this->maxCriticalDamage = $criticalDamage['max'];

        return $this;
    }

    /**
     * Get criticalDamage.
     *
     * @return array
     */
    public function getCriticalDamage()
    {
        return ['min' => $this->minCriticalDamage, 'max' => $this->maxCriticalDamage];
    }

    /**
     * Set minCriticalResistance.
     *
     * @param int $minCriticalResistance
     *
     * @return object
     */
    public function setMinCriticalResistance($minCriticalResistance)
    {
        $this->minCriticalResistance = $minCriticalResistance;

        return $this;
    }

    /**
     * Get minCriticalResistance.
     *
     * @return int
     */
    public function getMinCriticalResistance()
    {
        return $this->minCriticalResistance;
    }

    /**
     * Set maxCriticalResistance.
     *
     * @param int $maxCriticalResistance
     *
     * @return object
     */
    public function setMaxCriticalResistance($maxCriticalResistance)
    {
        $this->maxCriticalResistance = $maxCriticalResistance;

        return $this;
    }

    /**
     * Get maxCriticalResistance.
     *
     * @return int
     */
    public function getMaxCriticalResistance()
    {
        return $this->maxCriticalResistance;
    }

    /**
     * Set criticalResistance.
     *
     * @param array $criticalResistance
     *
     * @return object
     */
    public function setCriticalResistance(array $criticalResistance)
    {
        $this->minCriticalResistance = $criticalResistance['min'];
        $this->maxCriticalResistance = $criticalResistance['max'];

        return $this;
    }

    /**
     * Get criticalResistance.
     *
     * @return array
     */
    public function getCriticalResistance()
    {
        return ['min' => $this->minCriticalResistance, 'max' => $this->maxCriticalResistance];
    }

    /**
     * Set minPushbackDamage.
     *
     * @param int $minPushbackDamage
     *
     * @return object
     */
    public function setMinPushbackDamage($minPushbackDamage)
    {
        $this->minPushbackDamage = $minPushbackDamage;

        return $this;
    }

    /**
     * Get minPushbackDamage.
     *
     * @return int
     */
    public function getMinPushbackDamage()
    {
        return $this->minPushbackDamage;
    }

    /**
     * Set maxPushbackDamage.
     *
     * @param int $maxPushbackDamage
     *
     * @return object
     */
    public function setMaxPushbackDamage($maxPushbackDamage)
    {
        $this->maxPushbackDamage = $maxPushbackDamage;

        return $this;
    }

    /**
     * Get maxPushbackDamage.
     *
     * @return int
     */
    public function getMaxPushbackDamage()
    {
        return $this->maxPushbackDamage;
    }

    /**
     * Set pushbackDamage.
     *
     * @param array $pushbackDamage
     *
     * @return object
     */
    public function setPushbackDamage(array $pushbackDamage)
    {
        $this->minPushbackDamage = $pushbackDamage['min'];
        $this->maxPushbackDamage = $pushbackDamage['max'];

        return $this;
    }

    /**
     * Get pushbackDamage.
     *
     * @return array
     */
    public function getPushbackDamage()
    {
        return ['min' => $this->minPushbackDamage, 'max' => $this->maxPushbackDamage];
    }

    /**
     * Set minPushbackResistance.
     *
     * @param int $minPushbackResistance
     *
     * @return object
     */
    public function setMinPushbackResistance($minPushbackResistance)
    {
        $this->minPushbackResistance = $minPushbackResistance;

        return $this;
    }

    /**
     * Get minPushbackResistance.
     *
     * @return int
     */
    public function getMinPushbackResistance()
    {
        return $this->minPushbackResistance;
    }

    /**
     * Set maxPushbackResistance.
     *
     * @param int $maxPushbackResistance
     *
     * @return object
     */
    public function setMaxPushbackResistance($maxPushbackResistance)
    {
        $this->maxPushbackResistance = $maxPushbackResistance;

        return $this;
    }

    /**
     * Get maxPushbackResistance.
     *
     * @return int
     */
    public function getMaxPushbackResistance()
    {
        return $this->maxPushbackResistance;
    }

    /**
     * Set pushbackResistance.
     *
     * @param array $pushbackResistance
     *
     * @return object
     */
    public function setPushbackResistance(array $pushbackResistance)
    {
        $this->minPushbackResistance = $pushbackResistance['min'];
        $this->maxPushbackResistance = $pushbackResistance['max'];

        return $this;
    }

    /**
     * Get pushbackResistance.
     *
     * @return array
     */
    public function getPushbackResistance()
    {
        return ['min' => $this->minPushbackResistance, 'max' => $this->maxPushbackResistance];
    }

    /**
     * Set minTrapPower.
     *
     * @param int $minTrapPower
     *
     * @return object
     */
    public function setMinTrapPower($minTrapPower)
    {
        $this->minTrapPower = $minTrapPower;

        return $this;
    }

    /**
     * Get minTrapPower.
     *
     * @return int
     */
    public function getMinTrapPower()
    {
        return $this->minTrapPower;
    }

    /**
     * Set maxTrapPower.
     *
     * @param int $maxTrapPower
     *
     * @return object
     */
    public function setMaxTrapPower($maxTrapPower)
    {
        $this->maxTrapPower = $maxTrapPower;

        return $this;
    }

    /**
     * Get maxTrapPower.
     *
     * @return int
     */
    public function getMaxTrapPower()
    {
        return $this->maxTrapPower;
    }

    /**
     * Set trapPower.
     *
     * @param array $trapPower
     *
     * @return object
     */
    public function setTrapPower(array $trapPower)
    {
        $this->minTrapPower = $trapPower['min'];
        $this->maxTrapPower = $trapPower['max'];

        return $this;
    }

    /**
     * Get trapPower.
     *
     * @return array
     */
    public function getTrapPower()
    {
        return ['min' => $this->minTrapPower, 'max' => $this->maxTrapPower];
    }

    /**
     * Set minTrapDamage.
     *
     * @param int $minTrapDamage
     *
     * @return object
     */
    public function setMinTrapDamage($minTrapDamage)
    {
        $this->minTrapDamage = $minTrapDamage;

        return $this;
    }

    /**
     * Get minTrapDamage.
     *
     * @return int
     */
    public function getMinTrapDamage()
    {
        return $this->minTrapDamage;
    }

    /**
     * Set maxTrapDamage.
     *
     * @param int $maxTrapDamage
     *
     * @return object
     */
    public function setMaxTrapDamage($maxTrapDamage)
    {
        $this->maxTrapDamage = $maxTrapDamage;

        return $this;
    }

    /**
     * Get maxTrapDamage.
     *
     * @return int
     */
    public function getMaxTrapDamage()
    {
        return $this->maxTrapDamage;
    }

    /**
     * Set trapDamage.
     *
     * @param array $trapDamage
     *
     * @return object
     */
    public function setTrapDamage(array $trapDamage)
    {
        $this->minTrapDamage = $trapDamage['min'];
        $this->maxTrapDamage = $trapDamage['max'];

        return $this;
    }

    /**
     * Get trapDamage.
     *
     * @return array
     */
    public function getTrapDamage()
    {
        return ['min' => $this->minTrapDamage, 'max' => $this->maxTrapDamage];
    }

    /**
     * Set all characteristics.
     *
     * @param array $characteristics
     * @param bool  $zeroMissing
     *
     * @return object
     */
    public function setCharacteristics(array $characteristics, $zeroMissing = false)
    {
        if (isset($characteristics['vitality'])) {
            $this->minVitality = $characteristics['vitality']['min'];
            $this->maxVitality = $characteristics['vitality']['max'];
        } elseif ($zeroMissing) {
            $this->minVitality = 0;
            $this->maxVitality = 0;
        }
        if (isset($characteristics['strength'])) {
            $this->minStrength = $characteristics['strength']['min'];
            $this->maxStrength = $characteristics['strength']['max'];
        } elseif ($zeroMissing) {
            $this->minStrength = 0;
            $this->maxStrength = 0;
        }
        if (isset($characteristics['intelligence'])) {
            $this->minIntelligence = $characteristics['intelligence']['min'];
            $this->maxIntelligence = $characteristics['intelligence']['max'];
        } elseif ($zeroMissing) {
            $this->minIntelligence = 0;
            $this->maxIntelligence = 0;
        }
        if (isset($characteristics['chance'])) {
            $this->minChance = $characteristics['chance']['min'];
            $this->maxChance = $characteristics['chance']['max'];
        } elseif ($zeroMissing) {
            $this->minChance = 0;
            $this->maxChance = 0;
        }
        if (isset($characteristics['agility'])) {
            $this->minAgility = $characteristics['agility']['min'];
            $this->maxAgility = $characteristics['agility']['max'];
        } elseif ($zeroMissing) {
            $this->minAgility = 0;
            $this->maxAgility = 0;
        }
        if (isset($characteristics['wisdom'])) {
            $this->minWisdom = $characteristics['wisdom']['min'];
            $this->maxWisdom = $characteristics['wisdom']['max'];
        } elseif ($zeroMissing) {
            $this->minWisdom = 0;
            $this->maxWisdom = 0;
        }
        if (isset($characteristics['power'])) {
            $this->minPower = $characteristics['power']['min'];
            $this->maxPower = $characteristics['power']['max'];
        } elseif ($zeroMissing) {
            $this->minPower = 0;
            $this->maxPower = 0;
        }
        if (isset($characteristics['ap'])) {
            $this->minAp = $characteristics['ap']['min'];
            $this->maxAp = $characteristics['ap']['max'];
        } elseif ($zeroMissing) {
            $this->minAp = 0;
            $this->maxAp = 0;
        }
        if (isset($characteristics['mp'])) {
            $this->minMp = $characteristics['mp']['min'];
            $this->maxMp = $characteristics['mp']['max'];
        } elseif ($zeroMissing) {
            $this->minMp = 0;
            $this->maxMp = 0;
        }
        if (isset($characteristics['range'])) {
            $this->minRange = $characteristics['range']['min'];
            $this->maxRange = $characteristics['range']['max'];
        } elseif ($zeroMissing) {
            $this->minRange = 0;
            $this->maxRange = 0;
        }
        if (isset($characteristics['summons'])) {
            $this->minSummons = $characteristics['summons']['min'];
            $this->maxSummons = $characteristics['summons']['max'];
        } elseif ($zeroMissing) {
            $this->minSummons = 0;
            $this->maxSummons = 0;
        }
        if (isset($characteristics['damage'])) {
            $this->minDamage = $characteristics['damage']['min'];
            $this->maxDamage = $characteristics['damage']['max'];
        } elseif ($zeroMissing) {
            $this->minDamage = 0;
            $this->maxDamage = 0;
        }
        if (isset($characteristics['neutralDamage'])) {
            $this->minNeutralDamage = $characteristics['neutralDamage']['min'];
            $this->maxNeutralDamage = $characteristics['neutralDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minNeutralDamage = 0;
            $this->maxNeutralDamage = 0;
        }
        if (isset($characteristics['earthDamage'])) {
            $this->minEarthDamage = $characteristics['earthDamage']['min'];
            $this->maxEarthDamage = $characteristics['earthDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minEarthDamage = 0;
            $this->maxEarthDamage = 0;
        }
        if (isset($characteristics['fireDamage'])) {
            $this->minFireDamage = $characteristics['fireDamage']['min'];
            $this->maxFireDamage = $characteristics['fireDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minFireDamage = 0;
            $this->maxFireDamage = 0;
        }
        if (isset($characteristics['waterDamage'])) {
            $this->minWaterDamage = $characteristics['waterDamage']['min'];
            $this->maxWaterDamage = $characteristics['waterDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minWaterDamage = 0;
            $this->maxWaterDamage = 0;
        }
        if (isset($characteristics['airDamage'])) {
            $this->minAirDamage = $characteristics['airDamage']['min'];
            $this->maxAirDamage = $characteristics['airDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minAirDamage = 0;
            $this->maxAirDamage = 0;
        }
        if (isset($characteristics['heals'])) {
            $this->minHeals = $characteristics['heals']['min'];
            $this->maxHeals = $characteristics['heals']['max'];
        } elseif ($zeroMissing) {
            $this->minHeals = 0;
            $this->maxHeals = 0;
        }
        if (isset($characteristics['prospecting'])) {
            $this->minProspecting = $characteristics['prospecting']['min'];
            $this->maxProspecting = $characteristics['prospecting']['max'];
        } elseif ($zeroMissing) {
            $this->minProspecting = 0;
            $this->maxProspecting = 0;
        }
        if (isset($characteristics['initiative'])) {
            $this->minInitiative = $characteristics['initiative']['min'];
            $this->maxInitiative = $characteristics['initiative']['max'];
        } elseif ($zeroMissing) {
            $this->minInitiative = 0;
            $this->maxInitiative = 0;
        }
        if (isset($characteristics['reflectedDamage'])) {
            $this->minReflectedDamage = $characteristics['reflectedDamage']['min'];
            $this->maxReflectedDamage = $characteristics['reflectedDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minReflectedDamage = 0;
            $this->maxReflectedDamage = 0;
        }
        if (isset($characteristics['percentNeutralResistance'])) {
            $this->minPercentNeutralResistance = $characteristics['percentNeutralResistance']['min'];
            $this->maxPercentNeutralResistance = $characteristics['percentNeutralResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minPercentNeutralResistance = 0;
            $this->maxPercentNeutralResistance = 0;
        }
        if (isset($characteristics['percentWaterResistance'])) {
            $this->minPercentWaterResistance = $characteristics['percentWaterResistance']['min'];
            $this->maxPercentWaterResistance = $characteristics['percentWaterResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minPercentWaterResistance = 0;
            $this->maxPercentWaterResistance = 0;
        }
        if (isset($characteristics['neutralResistance'])) {
            $this->minNeutralResistance = $characteristics['neutralResistance']['min'];
            $this->maxNeutralResistance = $characteristics['neutralResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minNeutralResistance = 0;
            $this->maxNeutralResistance = 0;
        }
        if (isset($characteristics['earthResistance'])) {
            $this->minEarthResistance = $characteristics['earthResistance']['min'];
            $this->maxEarthResistance = $characteristics['earthResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minEarthResistance = 0;
            $this->maxEarthResistance = 0;
        }
        if (isset($characteristics['fireResistance'])) {
            $this->minFireResistance = $characteristics['fireResistance']['min'];
            $this->maxFireResistance = $characteristics['fireResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minFireResistance = 0;
            $this->maxFireResistance = 0;
        }
        if (isset($characteristics['waterResistance'])) {
            $this->minWaterResistance = $characteristics['waterResistance']['min'];
            $this->maxWaterResistance = $characteristics['waterResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minWaterResistance = 0;
            $this->maxWaterResistance = 0;
        }
        if (isset($characteristics['airResistance'])) {
            $this->minAirResistance = $characteristics['airResistance']['min'];
            $this->maxAirResistance = $characteristics['airResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minAirResistance = 0;
            $this->maxAirResistance = 0;
        }
        if (isset($characteristics['neutralResistanceInPvp'])) {
            $this->minNeutralResistanceInPvp = $characteristics['neutralResistanceInPvp']['min'];
            $this->maxNeutralResistanceInPvp = $characteristics['neutralResistanceInPvp']['max'];
        } elseif ($zeroMissing) {
            $this->minNeutralResistanceInPvp = 0;
            $this->maxNeutralResistanceInPvp = 0;
        }
        if (isset($characteristics['earthResistanceInPvp'])) {
            $this->minEarthResistanceInPvp = $characteristics['earthResistanceInPvp']['min'];
            $this->maxEarthResistanceInPvp = $characteristics['earthResistanceInPvp']['max'];
        } elseif ($zeroMissing) {
            $this->minEarthResistanceInPvp = 0;
            $this->maxEarthResistanceInPvp = 0;
        }
        if (isset($characteristics['fireResistanceInPvp'])) {
            $this->minFireResistanceInPvp = $characteristics['fireResistanceInPvp']['min'];
            $this->maxFireResistanceInPvp = $characteristics['fireResistanceInPvp']['max'];
        } elseif ($zeroMissing) {
            $this->minFireResistanceInPvp = 0;
            $this->maxFireResistanceInPvp = 0;
        }
        if (isset($characteristics['waterResistanceInPvp'])) {
            $this->minWaterResistanceInPvp = $characteristics['waterResistanceInPvp']['min'];
            $this->maxWaterResistanceInPvp = $characteristics['waterResistanceInPvp']['max'];
        } elseif ($zeroMissing) {
            $this->minWaterResistanceInPvp = 0;
            $this->maxWaterResistanceInPvp = 0;
        }
        if (isset($characteristics['airResistanceInPvp'])) {
            $this->minAirResistanceInPvp = $characteristics['airResistanceInPvp']['min'];
            $this->maxAirResistanceInPvp = $characteristics['airResistanceInPvp']['max'];
        } elseif ($zeroMissing) {
            $this->minAirResistanceInPvp = 0;
            $this->maxAirResistanceInPvp = 0;
        }
        if (isset($characteristics['lock'])) {
            $this->minLock = $characteristics['lock']['min'];
            $this->maxLock = $characteristics['lock']['max'];
        } elseif ($zeroMissing) {
            $this->minLock = 0;
            $this->maxLock = 0;
        }
        if (isset($characteristics['dodge'])) {
            $this->minDodge = $characteristics['dodge']['min'];
            $this->maxDodge = $characteristics['dodge']['max'];
        } elseif ($zeroMissing) {
            $this->minDodge = 0;
            $this->maxDodge = 0;
        }
        if (isset($characteristics['apReduction'])) {
            $this->minApReduction = $characteristics['apReduction']['min'];
            $this->maxApReduction = $characteristics['apReduction']['max'];
        } elseif ($zeroMissing) {
            $this->minApReduction = 0;
            $this->maxApReduction = 0;
        }
        if (isset($characteristics['mpReduction'])) {
            $this->minMpReduction = $characteristics['mpReduction']['min'];
            $this->maxMpReduction = $characteristics['mpReduction']['max'];
        } elseif ($zeroMissing) {
            $this->minMpReduction = 0;
            $this->maxMpReduction = 0;
        }
        if (isset($characteristics['apLossResistance'])) {
            $this->minApLossResistance = $characteristics['apLossResistance']['min'];
            $this->maxApLossResistance = $characteristics['apLossResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minApLossResistance = 0;
            $this->maxApLossResistance = 0;
        }
        if (isset($characteristics['mpLossResistance'])) {
            $this->minMpLossResistance = $characteristics['mpLossResistance']['min'];
            $this->maxMpLossResistance = $characteristics['mpLossResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minMpLossResistance = 0;
            $this->maxMpLossResistance = 0;
        }
        if (isset($characteristics['criticalDamage'])) {
            $this->minCriticalDamage = $characteristics['criticalDamage']['min'];
            $this->maxCriticalDamage = $characteristics['criticalDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minCriticalDamage = 0;
            $this->maxCriticalDamage = 0;
        }
        if (isset($characteristics['criticalResistance'])) {
            $this->minCriticalResistance = $characteristics['criticalResistance']['min'];
            $this->maxCriticalResistance = $characteristics['criticalResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minCriticalResistance = 0;
            $this->maxCriticalResistance = 0;
        }
        if (isset($characteristics['pushbackDamage'])) {
            $this->minPushbackDamage = $characteristics['pushbackDamage']['min'];
            $this->maxPushbackDamage = $characteristics['pushbackDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minPushbackDamage = 0;
            $this->maxPushbackDamage = 0;
        }
        if (isset($characteristics['pushbackResistance'])) {
            $this->minPushbackResistance = $characteristics['pushbackResistance']['min'];
            $this->maxPushbackResistance = $characteristics['pushbackResistance']['max'];
        } elseif ($zeroMissing) {
            $this->minPushbackResistance = 0;
            $this->maxPushbackResistance = 0;
        }
        if (isset($characteristics['trapPower'])) {
            $this->minTrapPower = $characteristics['trapPower']['min'];
            $this->maxTrapPower = $characteristics['trapPower']['max'];
        } elseif ($zeroMissing) {
            $this->minTrapPower = 0;
            $this->maxTrapPower = 0;
        }
        if (isset($characteristics['trapDamage'])) {
            $this->minTrapDamage = $characteristics['trapDamage']['min'];
            $this->maxTrapDamage = $characteristics['trapDamage']['max'];
        } elseif ($zeroMissing) {
            $this->minTrapDamage = 0;
            $this->maxTrapDamage = 0;
        }

        return $this;
    }

    /**
     * Get all characteristics.
     *
     * @Groups({"effects"})
     *
     * @return array
     */
    public function getCharacteristics()
    {
        $return = [];
        if (!empty($this->minVitality) || !empty($this->maxVitality)) {
            $return['vitality'] = ['min' => $this->minVitality, 'max' => $this->maxVitality];
        }

        if (!empty($this->minStrength) || !empty($this->maxStrength)) {
            $return['strength'] = ['min' => $this->minStrength, 'max' => $this->maxStrength];
        }

        if (!empty($this->minIntelligence) || !empty($this->maxIntelligence)) {
            $return['intelligence'] = ['min' => $this->minIntelligence, 'max' => $this->maxIntelligence];
        }

        if (!empty($this->minChance) || !empty($this->maxChance)) {
            $return['chance'] = ['min' => $this->minChance, 'max' => $this->maxChance];
        }

        if (!empty($this->minAgility) || !empty($this->maxAgility)) {
            $return['agility'] = ['min' => $this->minAgility, 'max' => $this->maxAgility];
        }

        if (!empty($this->minWisdom) || !empty($this->maxWisdom)) {
            $return['wisdom'] = ['min' => $this->minWisdom, 'max' => $this->maxWisdom];
        }

        if (!empty($this->minPower) || !empty($this->maxPower)) {
            $return['power'] = ['min' => $this->minPower, 'max' => $this->maxPower];
        }

        if (!empty($this->minAp) || !empty($this->maxAp)) {
            $return['ap'] = ['min' => $this->minAp, 'max' => $this->maxAp];
        }

        if (!empty($this->minMp) || !empty($this->maxMp)) {
            $return['mp'] = ['min' => $this->minMp, 'max' => $this->maxMp];
        }

        if (!empty($this->minRange) || !empty($this->maxRange)) {
            $return['range'] = ['min' => $this->minRange, 'max' => $this->maxRange];
        }

        if (!empty($this->minSummons) || !empty($this->maxSummons)) {
            $return['summons'] = ['min' => $this->minSummons, 'max' => $this->maxSummons];
        }

        if (!empty($this->minDamage) || !empty($this->maxDamage)) {
            $return['damage'] = ['min' => $this->minDamage, 'max' => $this->maxDamage];
        }

        if (!empty($this->minNeutralDamage) || !empty($this->maxNeutralDamage)) {
            $return['neutralDamage'] = ['min' => $this->minNeutralDamage, 'max' => $this->maxNeutralDamage];
        }

        if (!empty($this->minEarthDamage) || !empty($this->maxEarthDamage)) {
            $return['earthDamage'] = ['min' => $this->minEarthDamage, 'max' => $this->maxEarthDamage];
        }

        if (!empty($this->minFireDamage) || !empty($this->maxFireDamage)) {
            $return['fireDamage'] = ['min' => $this->minFireDamage, 'max' => $this->maxFireDamage];
        }

        if (!empty($this->minWaterDamage) || !empty($this->maxWaterDamage)) {
            $return['waterDamage'] = ['min' => $this->minWaterDamage, 'max' => $this->maxWaterDamage];
        }

        if (!empty($this->minAirDamage) || !empty($this->maxAirDamage)) {
            $return['airDamage'] = ['min' => $this->minAirDamage, 'max' => $this->maxAirDamage];
        }

        if (!empty($this->minHeals) || !empty($this->maxHeals)) {
            $return['heals'] = ['min' => $this->minHeals, 'max' => $this->maxHeals];
        }

        if (!empty($this->minProspecting) || !empty($this->maxProspecting)) {
            $return['prospecting'] = ['min' => $this->minProspecting, 'max' => $this->maxProspecting];
        }

        if (!empty($this->minInitiative) || !empty($this->maxInitiative)) {
            $return['initiative'] = ['min' => $this->minInitiative, 'max' => $this->maxInitiative];
        }

        if (!empty($this->minReflectedDamage) || !empty($this->maxReflectedDamage)) {
            $return['reflectedDamage'] = ['min' => $this->minReflectedDamage, 'max' => $this->maxReflectedDamage];
        }

        if (!empty($this->minPercentNeutralResistance) || !empty($this->maxPercentNeutralResistance)) {
            $return['percentNeutralResistance'] = ['min' => $this->minPercentNeutralResistance, 'max' => $this->maxPercentNeutralResistance];
        }

        if (!empty($this->minPercentWaterResistance) || !empty($this->maxPercentWaterResistance)) {
            $return['percentWaterResistance'] = ['min' => $this->minPercentWaterResistance, 'max' => $this->maxPercentWaterResistance];
        }

        if (!empty($this->minNeutralResistance) || !empty($this->maxNeutralResistance)) {
            $return['neutralResistance'] = ['min' => $this->minNeutralResistance, 'max' => $this->maxNeutralResistance];
        }

        if (!empty($this->minEarthResistance) || !empty($this->maxEarthResistance)) {
            $return['earthResistance'] = ['min' => $this->minEarthResistance, 'max' => $this->maxEarthResistance];
        }

        if (!empty($this->minFireResistance) || !empty($this->maxFireResistance)) {
            $return['fireResistance'] = ['min' => $this->minFireResistance, 'max' => $this->maxFireResistance];
        }

        if (!empty($this->minWaterResistance) || !empty($this->maxWaterResistance)) {
            $return['waterResistance'] = ['min' => $this->minWaterResistance, 'max' => $this->maxWaterResistance];
        }

        if (!empty($this->minAirResistance) || !empty($this->maxAirResistance)) {
            $return['airResistance'] = ['min' => $this->minAirResistance, 'max' => $this->maxAirResistance];
        }

        if (!empty($this->minNeutralResistanceInPvp) || !empty($this->maxNeutralResistanceInPvp)) {
            $return['neutralResistanceInPvp'] = ['min' => $this->minNeutralResistanceInPvp, 'max' => $this->maxNeutralResistanceInPvp];
        }

        if (!empty($this->minEarthResistanceInPvp) || !empty($this->maxEarthResistanceInPvp)) {
            $return['earthResistanceInPvp'] = ['min' => $this->minEarthResistanceInPvp, 'max' => $this->maxEarthResistanceInPvp];
        }

        if (!empty($this->minFireResistanceInPvp) || !empty($this->maxFireResistanceInPvp)) {
            $return['fireResistanceInPvp'] = ['min' => $this->minFireResistanceInPvp, 'max' => $this->maxFireResistanceInPvp];
        }

        if (!empty($this->minWaterResistanceInPvp) || !empty($this->maxWaterResistanceInPvp)) {
            $return['waterResistanceInPvp'] = ['min' => $this->minWaterResistanceInPvp, 'max' => $this->maxWaterResistanceInPvp];
        }

        if (!empty($this->minAirResistanceInPvp) || !empty($this->maxAirResistanceInPvp)) {
            $return['airResistanceInPvp'] = ['min' => $this->minAirResistanceInPvp, 'max' => $this->maxAirResistanceInPvp];
        }

        if (!empty($this->minLock) || !empty($this->maxLock)) {
            $return['lock'] = ['min' => $this->minLock, 'max' => $this->maxLock];
        }

        if (!empty($this->minDodge) || !empty($this->maxDodge)) {
            $return['dodge'] = ['min' => $this->minDodge, 'max' => $this->maxDodge];
        }

        if (!empty($this->minApReduction) || !empty($this->maxApReduction)) {
            $return['apReduction'] = ['min' => $this->minApReduction, 'max' => $this->maxApReduction];
        }

        if (!empty($this->minMpReduction) || !empty($this->maxMpReduction)) {
            $return['mpReduction'] = ['min' => $this->minMpReduction, 'max' => $this->maxMpReduction];
        }

        if (!empty($this->minApLossResistance) || !empty($this->maxApLossResistance)) {
            $return['apLossResistance'] = ['min' => $this->minApLossResistance, 'max' => $this->maxApLossResistance];
        }

        if (!empty($this->minMpLossResistance) || !empty($this->maxMpLossResistance)) {
            $return['mpLossResistance'] = ['min' => $this->minMpLossResistance, 'max' => $this->maxMpLossResistance];
        }

        if (!empty($this->minCriticalDamage) || !empty($this->maxCriticalDamage)) {
            $return['criticalDamage'] = ['min' => $this->minCriticalDamage, 'max' => $this->maxCriticalDamage];
        }

        if (!empty($this->minCriticalResistance) || !empty($this->maxCriticalResistance)) {
            $return['criticalResistance'] = ['min' => $this->minCriticalResistance, 'max' => $this->maxCriticalResistance];
        }

        if (!empty($this->minPushbackDamage) || !empty($this->maxPushbackDamage)) {
            $return['pushbackDamage'] = ['min' => $this->minPushbackDamage, 'max' => $this->maxPushbackDamage];
        }

        if (!empty($this->minPushbackResistance) || !empty($this->maxPushbackResistance)) {
            $return['pushbackResistance'] = ['min' => $this->minPushbackResistance, 'max' => $this->maxPushbackResistance];
        }

        if (!empty($this->minTrapPower) || !empty($this->maxTrapPower)) {
            $return['trapPower'] = ['min' => $this->minTrapPower, 'max' => $this->maxTrapPower];
        }

        if (!empty($this->minTrapDamage) || !empty($this->maxTrapDamage)) {
            $return['trapDamage'] = ['min' => $this->minTrapDamage, 'max' => $this->maxTrapDamage];
        }

        return $return;
    }
}
