dof_guild_home:
    path:     /{page}
    defaults: { _controller: DofGuildBundle:Guild:index, page: 1 }
    requirements:
      page: \d+

dof_guild_show:
    path:     /{slug}
    defaults: { _controller: DofGuildBundle:Guild:show }
    requirements:
       slug: '[0-9a-z-]+'

dof_guild_add:
    path:     /add/
    defaults: { _controller: DofGuildBundle:Guild:add }

dof_guild_register:
    path:     /register/{slug}
    defaults: { _controller: DofGuildBundle:Guild:register }
    requirements:
       slug: '[0-9a-z-]+'