<?php

namespace Dof\Bundle\MonsterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonsterGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterGradeRepository extends EntityRepository
{
}
