dof_translation_homepage:
    path: /{tLocale}
    defaults: { _controller: DofTranslationBundle:Translation:locale }
    requirements:
        tLocale: '[a-z]{2}'

dof_translation_create:
    path: /{tLocale}/{domain}/{label}/create
    defaults: { _controller: DofTranslationBundle:Translation:create }
    requirements:
        tLocale: '[a-z]{2}'
