<?php

namespace Dof\Bundle\CharacterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlignmentSideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlignmentSideRepository extends EntityRepository
{
}
