services:
#    dof_monster.example:
#        class: Dof\MonsterBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    dof_monster.admin.monster:
        class: Dof\MonsterBundle\Admin\MonsterAdmin
        arguments: [~, Dof\MonsterBundle\Entity\Monster, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Bestiaire, label: Monstres}
