services:
    # DofMapBundle:SuperArea and subclasses
    dof_imp_exp.importer.map_super_areas:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Map\SuperAreaImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: map_super_areas, groups: "map" }
            - { name: dof_imp_exp.importer, provides: beta_map_super_areas, groups: "map beta" }

    dof_imp_exp.importer.map_areas:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Map\AreaImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: map_areas, requires: map_super_areas, groups: "map" }
            - { name: dof_imp_exp.importer, provides: beta_map_areas, requires: beta_map_super_areas, groups: "map beta" }

    dof_imp_exp.importer.map_sub_areas:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Map\SubAreaImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: map_sub_areas, requires: map_areas, groups: "map" }
            - { name: dof_imp_exp.importer, provides: beta_map_sub_areas, requires: beta_map_areas, groups: "map beta" }

    dof_imp_exp.importer.map_positions:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Map\PositionImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: map_positions, requires: map_sub_areas, groups: "map" }
            - { name: dof_imp_exp.importer, provides: beta_map_positions, requires: beta_map_sub_areas, groups: "map beta" }
