services:
    # DofQuestBundle:Quest and subclasses
    dof_imp_exp.importer.quest_categories:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\QuestCategoryImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: quest_categories, groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_quest_categories, groups: "quests beta" }

    dof_imp_exp.importer.quests:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\QuestImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: quests, requires: quest_categories, groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_quests, requires: beta_quest_categories, groups: "quests beta" }

    dof_imp_exp.importer.quest_steps:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\QuestStepImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: quest_steps, requires: quests, groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_quest_steps, requires: beta_quests, groups: "quests beta" }

    dof_imp_exp.importer.quest_step_objectives:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\QuestObjectiveImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: quest_step_objectives, requires: "quest_steps quest_objective_templates map_positions", groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_quest_step_objectives, requires: "beta_quest_steps beta_quest_objective_templates beta_map_positions", groups: "quests beta" }

    dof_imp_exp.importer.quest_step_objective_params:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\QuestObjectiveParamImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: quest_step_objective_params, requires: quest_step_objectives, groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_quest_step_objective_params, requires: beta_quest_step_objectives, groups: "quests beta" }

    dof_imp_exp.importer.quest_objective_templates:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\QuestObjectiveTemplateImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: quest_objective_templates, groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_quest_objective_templates, groups: "quests beta" }

    # DofQuestBundle:Achievement and subclasses
    dof_imp_exp.importer.achievement_categories:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\AchievementCategoryImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: achievement_categories, groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_achievement_categories, groups: "quests beta" }

    dof_imp_exp.importer.achievements:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Quest\AchievementImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: achievements, requires: achievement_categories, groups: "quests" }
            - { name: dof_imp_exp.importer, provides: beta_achievements, requires: beta_achievement_categories, groups: "quests beta" }
