services:
    # DofCharacterBundle:Spell and subclasses
    dof_imp_exp.importer.spells:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: spells, requires: breeds, groups: "spells" }
            - { name: dof_imp_exp.importer, provides: beta_spells, requires: beta_breeds, groups: "spells beta" }

    dof_imp_exp.importer.spell_ranks:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellRankImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: spell_ranks, requires: spells, groups: "spells" }
            - { name: dof_imp_exp.importer, provides: beta_spell_ranks, requires: beta_spells, groups: "spells beta" }

    dof_imp_exp.importer.spell_rank_effects:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellRankEffectImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: spell_rank_effects, requires: "spell_ranks effect_templates", groups: "spells" }
            - { name: dof_imp_exp.importer, provides: beta_spell_rank_effects, requires: "beta_spell_ranks beta_effect_templates", groups: "spells beta" }
        calls:
            - [ setParamLoader, [ "@dof_characters.effect_param_loader" ] ]

    dof_imp_exp.importer.spell_rank_states:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellRankStateRequirementImporter
        parent: dof_imp_exp.importer.game_importer
        tags:
            - { name: dof_imp_exp.importer, provides: spell_rank_states, requires: states spell_ranks', groups: "spells" }
            - { name: dof_imp_exp.importer, provides: beta_spell_rank_states, requires: 'beta_states beta_spell_ranks', groups: "spells beta" }
