services:
    # DofCharacterBundle:Spell and subclasses
    dof_imp_exp.importer.spells:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: spells, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_spells, requires: 'spells beta_breeds' }

    dof_imp_exp.importer.spell_ranks:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellRankImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: spell_ranks, requires: spells }
            - { name: dof_imp_exp.importer, provides: beta_spell_ranks, requires: 'spell_ranks beta_spells' }

    dof_imp_exp.importer.spell_rank_effects:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellRankEffectImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: spell_rank_effects, requires: "spell_ranks effect_templates" }
            - { name: dof_imp_exp.importer, provides: beta_spell_rank_effects, requires: "beta_spell_ranks beta_effect_templates" }
        calls:
            - [ setParamLoader, [ "@dof_characters.effect_param_loader" ] ]

    dof_imp_exp.importer.spell_rank_states:
        class: Dof\Bundle\ImpExpBundle\Importer\GameData\Spell\SpellRankStateRequirementImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: spell_rank_states, requires: 'states spell_ranks' }
            - { name: dof_imp_exp.importer, provides: beta_spell_rank_states, requires: 'beta_states beta_spell_ranks' }
