parameters:
    wit.importer_arguments: [@doctrine.orm.entity_manager, %wit_private_key%]

services:
    # DofItemBundle:MountTemplate
    dof_imp_exp.wit_importer.mounts:
        class: Dof\Bundle\ImpExpBundle\Importer\WitData\MountImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: wit_mounts, requires: beta_item_templates }
