# Propositions
dof_cms_propositions_homepage:
    pattern: /propositions/{page}
    defaults: { _controller: DofCMSBundle:Proposition:index, page: 1 }

dof_cms_valid:
    pattern: /valid/{slug}
    defaults: { _controller: DofCMSBundle:Article:valid }

dof_cms_validate:
    pattern: /proposition/validate/{id}
    defaults: { _controller: DofCMSBundle:Proposition:validate }

# Articles
dof_cms_show:
    pattern: /{slug}
    defaults: { _controller: DofCMSBundle:Article:view }

dof_cms_create:
    pattern: /create/{type}
    defaults: { _controller: DofCMSBundle:Article:create }

dof_cms_edit:
    pattern: /edit/{id}
    defaults: { _controller: DofCMSBundle:Article:edit }
    requirements:
      id: \d+

dof_cms_archive:
    pattern: /archive/{page}
    defaults: { _controller: DofCMSBundle:Archive:archive, page: 1 }
    requirements:
      page: \d+
