<?php

namespace Dof\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgrammedNotificationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammedNotificationRepository extends EntityRepository
{
    public function findReadyNotifications(\Datetime $date = null)
    {
        if ($date === null) {
            $date = new \Datetime();
        }

        return $this
              ->createQueryBuilder('n')
              ->where('n.date < :date')
              ->getQuery()
              ->setParameter('date', $date)
              ->getResult();
    }
}
