<?php

namespace Dof\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dof\UserBundle\Entity\User;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends EntityRepository
{
	public function getBadgeUser(User $user)
	{
		return $this
                  ->createQueryBuilder('ub')
                  ->select('ub', 'b', 'l')
                  ->join('ub.badge', 'b')
                  ->join('b.levels', 'l')
                  ->where('ub.owner = :user')
                  ->getQuery()
                  ->setParameter('user', $user)
                  ->getSingleResult();
              ;
	}
}
