<?php
// This code is automatically generated by a tool

// You can regenerate it using the command :
// php app/console generate:dof:characteristic

// The template is at :
// src/Dof/GeneratorBundle/Resources/views/ItemBundle/CharacteristicsRangeTrait.php.twig

namespace Dof\ItemBundle;

use Doctrine\ORM\Mapping as ORM;

trait CharacteristicsRangeTrait
{
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_vitality", type="integer")
	 */
	protected $minVitality;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_vitality", type="integer")
	 */
	protected $maxVitality;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_strength", type="integer")
	 */
	protected $minStrength;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_strength", type="integer")
	 */
	protected $maxStrength;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_intelligence", type="integer")
	 */
	protected $minIntelligence;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_intelligence", type="integer")
	 */
	protected $maxIntelligence;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_chance", type="integer")
	 */
	protected $minChance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_chance", type="integer")
	 */
	protected $maxChance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_agility", type="integer")
	 */
	protected $minAgility;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_agility", type="integer")
	 */
	protected $maxAgility;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_wisdom", type="integer")
	 */
	protected $minWisdom;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_wisdom", type="integer")
	 */
	protected $maxWisdom;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_power", type="integer")
	 */
	protected $minPower;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_power", type="integer")
	 */
	protected $maxPower;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_critical_hits", type="integer")
	 */
	protected $minCriticalHits;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_critical_hits", type="integer")
	 */
	protected $maxCriticalHits;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_ap", type="integer")
	 */
	protected $minAp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_ap", type="integer")
	 */
	protected $maxAp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_mp", type="integer")
	 */
	protected $minMp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_mp", type="integer")
	 */
	protected $maxMp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_range", type="integer")
	 */
	protected $minRange;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_range", type="integer")
	 */
	protected $maxRange;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_summons", type="integer")
	 */
	protected $minSummons;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_summons", type="integer")
	 */
	protected $maxSummons;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_damage", type="integer")
	 */
	protected $minDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_damage", type="integer")
	 */
	protected $maxDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_neutral_damage", type="integer")
	 */
	protected $minNeutralDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_neutral_damage", type="integer")
	 */
	protected $maxNeutralDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_earth_damage", type="integer")
	 */
	protected $minEarthDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_earth_damage", type="integer")
	 */
	protected $maxEarthDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_fire_damage", type="integer")
	 */
	protected $minFireDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_fire_damage", type="integer")
	 */
	protected $maxFireDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_water_damage", type="integer")
	 */
	protected $minWaterDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_water_damage", type="integer")
	 */
	protected $maxWaterDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_air_damage", type="integer")
	 */
	protected $minAirDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_air_damage", type="integer")
	 */
	protected $maxAirDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_heals", type="integer")
	 */
	protected $minHeals;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_heals", type="integer")
	 */
	protected $maxHeals;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_prospecting", type="integer")
	 */
	protected $minProspecting;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_prospecting", type="integer")
	 */
	protected $maxProspecting;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_initiative", type="integer")
	 */
	protected $minInitiative;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_initiative", type="integer")
	 */
	protected $maxInitiative;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_reflected_damage", type="integer")
	 */
	protected $minReflectedDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_reflected_damage", type="integer")
	 */
	protected $maxReflectedDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_neutral_resistance", type="integer")
	 */
	protected $minPercentNeutralResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_neutral_resistance", type="integer")
	 */
	protected $maxPercentNeutralResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_earth_resistance", type="integer")
	 */
	protected $minPercentEarthResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_earth_resistance", type="integer")
	 */
	protected $maxPercentEarthResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_fire_resistance", type="integer")
	 */
	protected $minPercentFireResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_fire_resistance", type="integer")
	 */
	protected $maxPercentFireResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_water_resistance", type="integer")
	 */
	protected $minPercentWaterResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_water_resistance", type="integer")
	 */
	protected $maxPercentWaterResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_air_resistance", type="integer")
	 */
	protected $minPercentAirResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_air_resistance", type="integer")
	 */
	protected $maxPercentAirResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_neutral_resistance", type="integer")
	 */
	protected $minNeutralResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_neutral_resistance", type="integer")
	 */
	protected $maxNeutralResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_earth_resistance", type="integer")
	 */
	protected $minEarthResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_earth_resistance", type="integer")
	 */
	protected $maxEarthResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_fire_resistance", type="integer")
	 */
	protected $minFireResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_fire_resistance", type="integer")
	 */
	protected $maxFireResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_water_resistance", type="integer")
	 */
	protected $minWaterResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_water_resistance", type="integer")
	 */
	protected $maxWaterResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_air_resistance", type="integer")
	 */
	protected $minAirResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_air_resistance", type="integer")
	 */
	protected $maxAirResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_neutral_resistance_in_pvp", type="integer")
	 */
	protected $minPercentNeutralResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_neutral_resistance_in_pvp", type="integer")
	 */
	protected $maxPercentNeutralResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_earth_resistance_in_pvp", type="integer")
	 */
	protected $minPercentEarthResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_earth_resistance_in_pvp", type="integer")
	 */
	protected $maxPercentEarthResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_fire_resistance_in_pvp", type="integer")
	 */
	protected $minPercentFireResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_fire_resistance_in_pvp", type="integer")
	 */
	protected $maxPercentFireResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_water_resistance_in_pvp", type="integer")
	 */
	protected $minPercentWaterResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_water_resistance_in_pvp", type="integer")
	 */
	protected $maxPercentWaterResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_percent_air_resistance_in_pvp", type="integer")
	 */
	protected $minPercentAirResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_percent_air_resistance_in_pvp", type="integer")
	 */
	protected $maxPercentAirResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_neutral_resistance_in_pvp", type="integer")
	 */
	protected $minNeutralResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_neutral_resistance_in_pvp", type="integer")
	 */
	protected $maxNeutralResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_earth_resistance_in_pvp", type="integer")
	 */
	protected $minEarthResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_earth_resistance_in_pvp", type="integer")
	 */
	protected $maxEarthResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_fire_resistance_in_pvp", type="integer")
	 */
	protected $minFireResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_fire_resistance_in_pvp", type="integer")
	 */
	protected $maxFireResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_water_resistance_in_pvp", type="integer")
	 */
	protected $minWaterResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_water_resistance_in_pvp", type="integer")
	 */
	protected $maxWaterResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_air_resistance_in_pvp", type="integer")
	 */
	protected $minAirResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_air_resistance_in_pvp", type="integer")
	 */
	protected $maxAirResistanceInPvp;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_lock", type="integer")
	 */
	protected $minLock;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_lock", type="integer")
	 */
	protected $maxLock;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_dodge", type="integer")
	 */
	protected $minDodge;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_dodge", type="integer")
	 */
	protected $maxDodge;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_ap_reduction", type="integer")
	 */
	protected $minApReduction;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_ap_reduction", type="integer")
	 */
	protected $maxApReduction;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_mp_reduction", type="integer")
	 */
	protected $minMpReduction;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_mp_reduction", type="integer")
	 */
	protected $maxMpReduction;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_ap_loss_resistance", type="integer")
	 */
	protected $minApLossResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_ap_loss_resistance", type="integer")
	 */
	protected $maxApLossResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_mp_loss_resistance", type="integer")
	 */
	protected $minMpLossResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_mp_loss_resistance", type="integer")
	 */
	protected $maxMpLossResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_critical_damage", type="integer")
	 */
	protected $minCriticalDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_critical_damage", type="integer")
	 */
	protected $maxCriticalDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_critical_resistance", type="integer")
	 */
	protected $minCriticalResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_critical_resistance", type="integer")
	 */
	protected $maxCriticalResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_pushback_damage", type="integer")
	 */
	protected $minPushbackDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_pushback_damage", type="integer")
	 */
	protected $maxPushbackDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_pushback_resistance", type="integer")
	 */
	protected $minPushbackResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_pushback_resistance", type="integer")
	 */
	protected $maxPushbackResistance;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_trap_power", type="integer")
	 */
	protected $minTrapPower;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_trap_power", type="integer")
	 */
	protected $maxTrapPower;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="min_trap_damage", type="integer")
	 */
	protected $minTrapDamage;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="max_trap_damage", type="integer")
	 */
	protected $maxTrapDamage;

	/**
	 * Set minVitality
	 *
	 * @param integer $minVitality
	 * @return object
	 */
	public function setMinVitality($minVitality)
	{
		$this->minVitality = $minVitality;
		return $this;
	}
	
	/**
	 * Get minVitality
	 *
	 * @return integer
	 */
	public function getMinVitality()
	{
		return $this->minVitality;
	}

	/**
	 * Set maxVitality
	 *
	 * @param integer $maxVitality
	 * @return object
	 */
	public function setMaxVitality($maxVitality)
	{
		$this->maxVitality = $maxVitality;
		return $this;
	}
	
	/**
	 * Get maxVitality
	 *
	 * @return integer
	 */
	public function getMaxVitality()
	{
		return $this->maxVitality;
	}

	/**
	 * Set vitality
	 *
	 * @param array $vitality
	 * @return object
	 */
	public function setVitality(array $vitality)
	{
		$this->minVitality = $vitality['min'];
		$this->maxVitality = $vitality['max'];
		return $this;
	}
	
	/**
	 * Get vitality
	 *
	 * @return array
	 */
	public function getVitality()
	{
		return [ 'min' => $this->minVitality, 'max' => $this->maxVitality ];
	}

	/**
	 * Set minStrength
	 *
	 * @param integer $minStrength
	 * @return object
	 */
	public function setMinStrength($minStrength)
	{
		$this->minStrength = $minStrength;
		return $this;
	}
	
	/**
	 * Get minStrength
	 *
	 * @return integer
	 */
	public function getMinStrength()
	{
		return $this->minStrength;
	}

	/**
	 * Set maxStrength
	 *
	 * @param integer $maxStrength
	 * @return object
	 */
	public function setMaxStrength($maxStrength)
	{
		$this->maxStrength = $maxStrength;
		return $this;
	}
	
	/**
	 * Get maxStrength
	 *
	 * @return integer
	 */
	public function getMaxStrength()
	{
		return $this->maxStrength;
	}

	/**
	 * Set strength
	 *
	 * @param array $strength
	 * @return object
	 */
	public function setStrength(array $strength)
	{
		$this->minStrength = $strength['min'];
		$this->maxStrength = $strength['max'];
		return $this;
	}
	
	/**
	 * Get strength
	 *
	 * @return array
	 */
	public function getStrength()
	{
		return [ 'min' => $this->minStrength, 'max' => $this->maxStrength ];
	}

	/**
	 * Set minIntelligence
	 *
	 * @param integer $minIntelligence
	 * @return object
	 */
	public function setMinIntelligence($minIntelligence)
	{
		$this->minIntelligence = $minIntelligence;
		return $this;
	}
	
	/**
	 * Get minIntelligence
	 *
	 * @return integer
	 */
	public function getMinIntelligence()
	{
		return $this->minIntelligence;
	}

	/**
	 * Set maxIntelligence
	 *
	 * @param integer $maxIntelligence
	 * @return object
	 */
	public function setMaxIntelligence($maxIntelligence)
	{
		$this->maxIntelligence = $maxIntelligence;
		return $this;
	}
	
	/**
	 * Get maxIntelligence
	 *
	 * @return integer
	 */
	public function getMaxIntelligence()
	{
		return $this->maxIntelligence;
	}

	/**
	 * Set intelligence
	 *
	 * @param array $intelligence
	 * @return object
	 */
	public function setIntelligence(array $intelligence)
	{
		$this->minIntelligence = $intelligence['min'];
		$this->maxIntelligence = $intelligence['max'];
		return $this;
	}
	
	/**
	 * Get intelligence
	 *
	 * @return array
	 */
	public function getIntelligence()
	{
		return [ 'min' => $this->minIntelligence, 'max' => $this->maxIntelligence ];
	}

	/**
	 * Set minChance
	 *
	 * @param integer $minChance
	 * @return object
	 */
	public function setMinChance($minChance)
	{
		$this->minChance = $minChance;
		return $this;
	}
	
	/**
	 * Get minChance
	 *
	 * @return integer
	 */
	public function getMinChance()
	{
		return $this->minChance;
	}

	/**
	 * Set maxChance
	 *
	 * @param integer $maxChance
	 * @return object
	 */
	public function setMaxChance($maxChance)
	{
		$this->maxChance = $maxChance;
		return $this;
	}
	
	/**
	 * Get maxChance
	 *
	 * @return integer
	 */
	public function getMaxChance()
	{
		return $this->maxChance;
	}

	/**
	 * Set chance
	 *
	 * @param array $chance
	 * @return object
	 */
	public function setChance(array $chance)
	{
		$this->minChance = $chance['min'];
		$this->maxChance = $chance['max'];
		return $this;
	}
	
	/**
	 * Get chance
	 *
	 * @return array
	 */
	public function getChance()
	{
		return [ 'min' => $this->minChance, 'max' => $this->maxChance ];
	}

	/**
	 * Set minAgility
	 *
	 * @param integer $minAgility
	 * @return object
	 */
	public function setMinAgility($minAgility)
	{
		$this->minAgility = $minAgility;
		return $this;
	}
	
	/**
	 * Get minAgility
	 *
	 * @return integer
	 */
	public function getMinAgility()
	{
		return $this->minAgility;
	}

	/**
	 * Set maxAgility
	 *
	 * @param integer $maxAgility
	 * @return object
	 */
	public function setMaxAgility($maxAgility)
	{
		$this->maxAgility = $maxAgility;
		return $this;
	}
	
	/**
	 * Get maxAgility
	 *
	 * @return integer
	 */
	public function getMaxAgility()
	{
		return $this->maxAgility;
	}

	/**
	 * Set agility
	 *
	 * @param array $agility
	 * @return object
	 */
	public function setAgility(array $agility)
	{
		$this->minAgility = $agility['min'];
		$this->maxAgility = $agility['max'];
		return $this;
	}
	
	/**
	 * Get agility
	 *
	 * @return array
	 */
	public function getAgility()
	{
		return [ 'min' => $this->minAgility, 'max' => $this->maxAgility ];
	}

	/**
	 * Set minWisdom
	 *
	 * @param integer $minWisdom
	 * @return object
	 */
	public function setMinWisdom($minWisdom)
	{
		$this->minWisdom = $minWisdom;
		return $this;
	}
	
	/**
	 * Get minWisdom
	 *
	 * @return integer
	 */
	public function getMinWisdom()
	{
		return $this->minWisdom;
	}

	/**
	 * Set maxWisdom
	 *
	 * @param integer $maxWisdom
	 * @return object
	 */
	public function setMaxWisdom($maxWisdom)
	{
		$this->maxWisdom = $maxWisdom;
		return $this;
	}
	
	/**
	 * Get maxWisdom
	 *
	 * @return integer
	 */
	public function getMaxWisdom()
	{
		return $this->maxWisdom;
	}

	/**
	 * Set wisdom
	 *
	 * @param array $wisdom
	 * @return object
	 */
	public function setWisdom(array $wisdom)
	{
		$this->minWisdom = $wisdom['min'];
		$this->maxWisdom = $wisdom['max'];
		return $this;
	}
	
	/**
	 * Get wisdom
	 *
	 * @return array
	 */
	public function getWisdom()
	{
		return [ 'min' => $this->minWisdom, 'max' => $this->maxWisdom ];
	}

	/**
	 * Set minPower
	 *
	 * @param integer $minPower
	 * @return object
	 */
	public function setMinPower($minPower)
	{
		$this->minPower = $minPower;
		return $this;
	}
	
	/**
	 * Get minPower
	 *
	 * @return integer
	 */
	public function getMinPower()
	{
		return $this->minPower;
	}

	/**
	 * Set maxPower
	 *
	 * @param integer $maxPower
	 * @return object
	 */
	public function setMaxPower($maxPower)
	{
		$this->maxPower = $maxPower;
		return $this;
	}
	
	/**
	 * Get maxPower
	 *
	 * @return integer
	 */
	public function getMaxPower()
	{
		return $this->maxPower;
	}

	/**
	 * Set power
	 *
	 * @param array $power
	 * @return object
	 */
	public function setPower(array $power)
	{
		$this->minPower = $power['min'];
		$this->maxPower = $power['max'];
		return $this;
	}
	
	/**
	 * Get power
	 *
	 * @return array
	 */
	public function getPower()
	{
		return [ 'min' => $this->minPower, 'max' => $this->maxPower ];
	}

	/**
	 * Set minCriticalHits
	 *
	 * @param integer $minCriticalHits
	 * @return object
	 */
	public function setMinCriticalHits($minCriticalHits)
	{
		$this->minCriticalHits = $minCriticalHits;
		return $this;
	}
	
	/**
	 * Get minCriticalHits
	 *
	 * @return integer
	 */
	public function getMinCriticalHits()
	{
		return $this->minCriticalHits;
	}

	/**
	 * Set maxCriticalHits
	 *
	 * @param integer $maxCriticalHits
	 * @return object
	 */
	public function setMaxCriticalHits($maxCriticalHits)
	{
		$this->maxCriticalHits = $maxCriticalHits;
		return $this;
	}
	
	/**
	 * Get maxCriticalHits
	 *
	 * @return integer
	 */
	public function getMaxCriticalHits()
	{
		return $this->maxCriticalHits;
	}

	/**
	 * Set criticalHits
	 *
	 * @param array $criticalHits
	 * @return object
	 */
	public function setCriticalHits(array $criticalHits)
	{
		$this->minCriticalHits = $criticalHits['min'];
		$this->maxCriticalHits = $criticalHits['max'];
		return $this;
	}
	
	/**
	 * Get criticalHits
	 *
	 * @return array
	 */
	public function getCriticalHits()
	{
		return [ 'min' => $this->minCriticalHits, 'max' => $this->maxCriticalHits ];
	}

	/**
	 * Set minAp
	 *
	 * @param integer $minAp
	 * @return object
	 */
	public function setMinAp($minAp)
	{
		$this->minAp = $minAp;
		return $this;
	}
	
	/**
	 * Get minAp
	 *
	 * @return integer
	 */
	public function getMinAp()
	{
		return $this->minAp;
	}

	/**
	 * Set maxAp
	 *
	 * @param integer $maxAp
	 * @return object
	 */
	public function setMaxAp($maxAp)
	{
		$this->maxAp = $maxAp;
		return $this;
	}
	
	/**
	 * Get maxAp
	 *
	 * @return integer
	 */
	public function getMaxAp()
	{
		return $this->maxAp;
	}

	/**
	 * Set ap
	 *
	 * @param array $ap
	 * @return object
	 */
	public function setAp(array $ap)
	{
		$this->minAp = $ap['min'];
		$this->maxAp = $ap['max'];
		return $this;
	}
	
	/**
	 * Get ap
	 *
	 * @return array
	 */
	public function getAp()
	{
		return [ 'min' => $this->minAp, 'max' => $this->maxAp ];
	}

	/**
	 * Set minMp
	 *
	 * @param integer $minMp
	 * @return object
	 */
	public function setMinMp($minMp)
	{
		$this->minMp = $minMp;
		return $this;
	}
	
	/**
	 * Get minMp
	 *
	 * @return integer
	 */
	public function getMinMp()
	{
		return $this->minMp;
	}

	/**
	 * Set maxMp
	 *
	 * @param integer $maxMp
	 * @return object
	 */
	public function setMaxMp($maxMp)
	{
		$this->maxMp = $maxMp;
		return $this;
	}
	
	/**
	 * Get maxMp
	 *
	 * @return integer
	 */
	public function getMaxMp()
	{
		return $this->maxMp;
	}

	/**
	 * Set mp
	 *
	 * @param array $mp
	 * @return object
	 */
	public function setMp(array $mp)
	{
		$this->minMp = $mp['min'];
		$this->maxMp = $mp['max'];
		return $this;
	}
	
	/**
	 * Get mp
	 *
	 * @return array
	 */
	public function getMp()
	{
		return [ 'min' => $this->minMp, 'max' => $this->maxMp ];
	}

	/**
	 * Set minRange
	 *
	 * @param integer $minRange
	 * @return object
	 */
	public function setMinRange($minRange)
	{
		$this->minRange = $minRange;
		return $this;
	}
	
	/**
	 * Get minRange
	 *
	 * @return integer
	 */
	public function getMinRange()
	{
		return $this->minRange;
	}

	/**
	 * Set maxRange
	 *
	 * @param integer $maxRange
	 * @return object
	 */
	public function setMaxRange($maxRange)
	{
		$this->maxRange = $maxRange;
		return $this;
	}
	
	/**
	 * Get maxRange
	 *
	 * @return integer
	 */
	public function getMaxRange()
	{
		return $this->maxRange;
	}

	/**
	 * Set range
	 *
	 * @param array $range
	 * @return object
	 */
	public function setRange(array $range)
	{
		$this->minRange = $range['min'];
		$this->maxRange = $range['max'];
		return $this;
	}
	
	/**
	 * Get range
	 *
	 * @return array
	 */
	public function getRange()
	{
		return [ 'min' => $this->minRange, 'max' => $this->maxRange ];
	}

	/**
	 * Set minSummons
	 *
	 * @param integer $minSummons
	 * @return object
	 */
	public function setMinSummons($minSummons)
	{
		$this->minSummons = $minSummons;
		return $this;
	}
	
	/**
	 * Get minSummons
	 *
	 * @return integer
	 */
	public function getMinSummons()
	{
		return $this->minSummons;
	}

	/**
	 * Set maxSummons
	 *
	 * @param integer $maxSummons
	 * @return object
	 */
	public function setMaxSummons($maxSummons)
	{
		$this->maxSummons = $maxSummons;
		return $this;
	}
	
	/**
	 * Get maxSummons
	 *
	 * @return integer
	 */
	public function getMaxSummons()
	{
		return $this->maxSummons;
	}

	/**
	 * Set summons
	 *
	 * @param array $summons
	 * @return object
	 */
	public function setSummons(array $summons)
	{
		$this->minSummons = $summons['min'];
		$this->maxSummons = $summons['max'];
		return $this;
	}
	
	/**
	 * Get summons
	 *
	 * @return array
	 */
	public function getSummons()
	{
		return [ 'min' => $this->minSummons, 'max' => $this->maxSummons ];
	}

	/**
	 * Set minDamage
	 *
	 * @param integer $minDamage
	 * @return object
	 */
	public function setMinDamage($minDamage)
	{
		$this->minDamage = $minDamage;
		return $this;
	}
	
	/**
	 * Get minDamage
	 *
	 * @return integer
	 */
	public function getMinDamage()
	{
		return $this->minDamage;
	}

	/**
	 * Set maxDamage
	 *
	 * @param integer $maxDamage
	 * @return object
	 */
	public function setMaxDamage($maxDamage)
	{
		$this->maxDamage = $maxDamage;
		return $this;
	}
	
	/**
	 * Get maxDamage
	 *
	 * @return integer
	 */
	public function getMaxDamage()
	{
		return $this->maxDamage;
	}

	/**
	 * Set damage
	 *
	 * @param array $damage
	 * @return object
	 */
	public function setDamage(array $damage)
	{
		$this->minDamage = $damage['min'];
		$this->maxDamage = $damage['max'];
		return $this;
	}
	
	/**
	 * Get damage
	 *
	 * @return array
	 */
	public function getDamage()
	{
		return [ 'min' => $this->minDamage, 'max' => $this->maxDamage ];
	}

	/**
	 * Set minNeutralDamage
	 *
	 * @param integer $minNeutralDamage
	 * @return object
	 */
	public function setMinNeutralDamage($minNeutralDamage)
	{
		$this->minNeutralDamage = $minNeutralDamage;
		return $this;
	}
	
	/**
	 * Get minNeutralDamage
	 *
	 * @return integer
	 */
	public function getMinNeutralDamage()
	{
		return $this->minNeutralDamage;
	}

	/**
	 * Set maxNeutralDamage
	 *
	 * @param integer $maxNeutralDamage
	 * @return object
	 */
	public function setMaxNeutralDamage($maxNeutralDamage)
	{
		$this->maxNeutralDamage = $maxNeutralDamage;
		return $this;
	}
	
	/**
	 * Get maxNeutralDamage
	 *
	 * @return integer
	 */
	public function getMaxNeutralDamage()
	{
		return $this->maxNeutralDamage;
	}

	/**
	 * Set neutralDamage
	 *
	 * @param array $neutralDamage
	 * @return object
	 */
	public function setNeutralDamage(array $neutralDamage)
	{
		$this->minNeutralDamage = $neutralDamage['min'];
		$this->maxNeutralDamage = $neutralDamage['max'];
		return $this;
	}
	
	/**
	 * Get neutralDamage
	 *
	 * @return array
	 */
	public function getNeutralDamage()
	{
		return [ 'min' => $this->minNeutralDamage, 'max' => $this->maxNeutralDamage ];
	}

	/**
	 * Set minEarthDamage
	 *
	 * @param integer $minEarthDamage
	 * @return object
	 */
	public function setMinEarthDamage($minEarthDamage)
	{
		$this->minEarthDamage = $minEarthDamage;
		return $this;
	}
	
	/**
	 * Get minEarthDamage
	 *
	 * @return integer
	 */
	public function getMinEarthDamage()
	{
		return $this->minEarthDamage;
	}

	/**
	 * Set maxEarthDamage
	 *
	 * @param integer $maxEarthDamage
	 * @return object
	 */
	public function setMaxEarthDamage($maxEarthDamage)
	{
		$this->maxEarthDamage = $maxEarthDamage;
		return $this;
	}
	
	/**
	 * Get maxEarthDamage
	 *
	 * @return integer
	 */
	public function getMaxEarthDamage()
	{
		return $this->maxEarthDamage;
	}

	/**
	 * Set earthDamage
	 *
	 * @param array $earthDamage
	 * @return object
	 */
	public function setEarthDamage(array $earthDamage)
	{
		$this->minEarthDamage = $earthDamage['min'];
		$this->maxEarthDamage = $earthDamage['max'];
		return $this;
	}
	
	/**
	 * Get earthDamage
	 *
	 * @return array
	 */
	public function getEarthDamage()
	{
		return [ 'min' => $this->minEarthDamage, 'max' => $this->maxEarthDamage ];
	}

	/**
	 * Set minFireDamage
	 *
	 * @param integer $minFireDamage
	 * @return object
	 */
	public function setMinFireDamage($minFireDamage)
	{
		$this->minFireDamage = $minFireDamage;
		return $this;
	}
	
	/**
	 * Get minFireDamage
	 *
	 * @return integer
	 */
	public function getMinFireDamage()
	{
		return $this->minFireDamage;
	}

	/**
	 * Set maxFireDamage
	 *
	 * @param integer $maxFireDamage
	 * @return object
	 */
	public function setMaxFireDamage($maxFireDamage)
	{
		$this->maxFireDamage = $maxFireDamage;
		return $this;
	}
	
	/**
	 * Get maxFireDamage
	 *
	 * @return integer
	 */
	public function getMaxFireDamage()
	{
		return $this->maxFireDamage;
	}

	/**
	 * Set fireDamage
	 *
	 * @param array $fireDamage
	 * @return object
	 */
	public function setFireDamage(array $fireDamage)
	{
		$this->minFireDamage = $fireDamage['min'];
		$this->maxFireDamage = $fireDamage['max'];
		return $this;
	}
	
	/**
	 * Get fireDamage
	 *
	 * @return array
	 */
	public function getFireDamage()
	{
		return [ 'min' => $this->minFireDamage, 'max' => $this->maxFireDamage ];
	}

	/**
	 * Set minWaterDamage
	 *
	 * @param integer $minWaterDamage
	 * @return object
	 */
	public function setMinWaterDamage($minWaterDamage)
	{
		$this->minWaterDamage = $minWaterDamage;
		return $this;
	}
	
	/**
	 * Get minWaterDamage
	 *
	 * @return integer
	 */
	public function getMinWaterDamage()
	{
		return $this->minWaterDamage;
	}

	/**
	 * Set maxWaterDamage
	 *
	 * @param integer $maxWaterDamage
	 * @return object
	 */
	public function setMaxWaterDamage($maxWaterDamage)
	{
		$this->maxWaterDamage = $maxWaterDamage;
		return $this;
	}
	
	/**
	 * Get maxWaterDamage
	 *
	 * @return integer
	 */
	public function getMaxWaterDamage()
	{
		return $this->maxWaterDamage;
	}

	/**
	 * Set waterDamage
	 *
	 * @param array $waterDamage
	 * @return object
	 */
	public function setWaterDamage(array $waterDamage)
	{
		$this->minWaterDamage = $waterDamage['min'];
		$this->maxWaterDamage = $waterDamage['max'];
		return $this;
	}
	
	/**
	 * Get waterDamage
	 *
	 * @return array
	 */
	public function getWaterDamage()
	{
		return [ 'min' => $this->minWaterDamage, 'max' => $this->maxWaterDamage ];
	}

	/**
	 * Set minAirDamage
	 *
	 * @param integer $minAirDamage
	 * @return object
	 */
	public function setMinAirDamage($minAirDamage)
	{
		$this->minAirDamage = $minAirDamage;
		return $this;
	}
	
	/**
	 * Get minAirDamage
	 *
	 * @return integer
	 */
	public function getMinAirDamage()
	{
		return $this->minAirDamage;
	}

	/**
	 * Set maxAirDamage
	 *
	 * @param integer $maxAirDamage
	 * @return object
	 */
	public function setMaxAirDamage($maxAirDamage)
	{
		$this->maxAirDamage = $maxAirDamage;
		return $this;
	}
	
	/**
	 * Get maxAirDamage
	 *
	 * @return integer
	 */
	public function getMaxAirDamage()
	{
		return $this->maxAirDamage;
	}

	/**
	 * Set airDamage
	 *
	 * @param array $airDamage
	 * @return object
	 */
	public function setAirDamage(array $airDamage)
	{
		$this->minAirDamage = $airDamage['min'];
		$this->maxAirDamage = $airDamage['max'];
		return $this;
	}
	
	/**
	 * Get airDamage
	 *
	 * @return array
	 */
	public function getAirDamage()
	{
		return [ 'min' => $this->minAirDamage, 'max' => $this->maxAirDamage ];
	}

	/**
	 * Set minHeals
	 *
	 * @param integer $minHeals
	 * @return object
	 */
	public function setMinHeals($minHeals)
	{
		$this->minHeals = $minHeals;
		return $this;
	}
	
	/**
	 * Get minHeals
	 *
	 * @return integer
	 */
	public function getMinHeals()
	{
		return $this->minHeals;
	}

	/**
	 * Set maxHeals
	 *
	 * @param integer $maxHeals
	 * @return object
	 */
	public function setMaxHeals($maxHeals)
	{
		$this->maxHeals = $maxHeals;
		return $this;
	}
	
	/**
	 * Get maxHeals
	 *
	 * @return integer
	 */
	public function getMaxHeals()
	{
		return $this->maxHeals;
	}

	/**
	 * Set heals
	 *
	 * @param array $heals
	 * @return object
	 */
	public function setHeals(array $heals)
	{
		$this->minHeals = $heals['min'];
		$this->maxHeals = $heals['max'];
		return $this;
	}
	
	/**
	 * Get heals
	 *
	 * @return array
	 */
	public function getHeals()
	{
		return [ 'min' => $this->minHeals, 'max' => $this->maxHeals ];
	}

	/**
	 * Set minProspecting
	 *
	 * @param integer $minProspecting
	 * @return object
	 */
	public function setMinProspecting($minProspecting)
	{
		$this->minProspecting = $minProspecting;
		return $this;
	}
	
	/**
	 * Get minProspecting
	 *
	 * @return integer
	 */
	public function getMinProspecting()
	{
		return $this->minProspecting;
	}

	/**
	 * Set maxProspecting
	 *
	 * @param integer $maxProspecting
	 * @return object
	 */
	public function setMaxProspecting($maxProspecting)
	{
		$this->maxProspecting = $maxProspecting;
		return $this;
	}
	
	/**
	 * Get maxProspecting
	 *
	 * @return integer
	 */
	public function getMaxProspecting()
	{
		return $this->maxProspecting;
	}

	/**
	 * Set prospecting
	 *
	 * @param array $prospecting
	 * @return object
	 */
	public function setProspecting(array $prospecting)
	{
		$this->minProspecting = $prospecting['min'];
		$this->maxProspecting = $prospecting['max'];
		return $this;
	}
	
	/**
	 * Get prospecting
	 *
	 * @return array
	 */
	public function getProspecting()
	{
		return [ 'min' => $this->minProspecting, 'max' => $this->maxProspecting ];
	}

	/**
	 * Set minInitiative
	 *
	 * @param integer $minInitiative
	 * @return object
	 */
	public function setMinInitiative($minInitiative)
	{
		$this->minInitiative = $minInitiative;
		return $this;
	}
	
	/**
	 * Get minInitiative
	 *
	 * @return integer
	 */
	public function getMinInitiative()
	{
		return $this->minInitiative;
	}

	/**
	 * Set maxInitiative
	 *
	 * @param integer $maxInitiative
	 * @return object
	 */
	public function setMaxInitiative($maxInitiative)
	{
		$this->maxInitiative = $maxInitiative;
		return $this;
	}
	
	/**
	 * Get maxInitiative
	 *
	 * @return integer
	 */
	public function getMaxInitiative()
	{
		return $this->maxInitiative;
	}

	/**
	 * Set initiative
	 *
	 * @param array $initiative
	 * @return object
	 */
	public function setInitiative(array $initiative)
	{
		$this->minInitiative = $initiative['min'];
		$this->maxInitiative = $initiative['max'];
		return $this;
	}
	
	/**
	 * Get initiative
	 *
	 * @return array
	 */
	public function getInitiative()
	{
		return [ 'min' => $this->minInitiative, 'max' => $this->maxInitiative ];
	}

	/**
	 * Set minReflectedDamage
	 *
	 * @param integer $minReflectedDamage
	 * @return object
	 */
	public function setMinReflectedDamage($minReflectedDamage)
	{
		$this->minReflectedDamage = $minReflectedDamage;
		return $this;
	}
	
	/**
	 * Get minReflectedDamage
	 *
	 * @return integer
	 */
	public function getMinReflectedDamage()
	{
		return $this->minReflectedDamage;
	}

	/**
	 * Set maxReflectedDamage
	 *
	 * @param integer $maxReflectedDamage
	 * @return object
	 */
	public function setMaxReflectedDamage($maxReflectedDamage)
	{
		$this->maxReflectedDamage = $maxReflectedDamage;
		return $this;
	}
	
	/**
	 * Get maxReflectedDamage
	 *
	 * @return integer
	 */
	public function getMaxReflectedDamage()
	{
		return $this->maxReflectedDamage;
	}

	/**
	 * Set reflectedDamage
	 *
	 * @param array $reflectedDamage
	 * @return object
	 */
	public function setReflectedDamage(array $reflectedDamage)
	{
		$this->minReflectedDamage = $reflectedDamage['min'];
		$this->maxReflectedDamage = $reflectedDamage['max'];
		return $this;
	}
	
	/**
	 * Get reflectedDamage
	 *
	 * @return array
	 */
	public function getReflectedDamage()
	{
		return [ 'min' => $this->minReflectedDamage, 'max' => $this->maxReflectedDamage ];
	}

	/**
	 * Set minPercentNeutralResistance
	 *
	 * @param integer $minPercentNeutralResistance
	 * @return object
	 */
	public function setMinPercentNeutralResistance($minPercentNeutralResistance)
	{
		$this->minPercentNeutralResistance = $minPercentNeutralResistance;
		return $this;
	}
	
	/**
	 * Get minPercentNeutralResistance
	 *
	 * @return integer
	 */
	public function getMinPercentNeutralResistance()
	{
		return $this->minPercentNeutralResistance;
	}

	/**
	 * Set maxPercentNeutralResistance
	 *
	 * @param integer $maxPercentNeutralResistance
	 * @return object
	 */
	public function setMaxPercentNeutralResistance($maxPercentNeutralResistance)
	{
		$this->maxPercentNeutralResistance = $maxPercentNeutralResistance;
		return $this;
	}
	
	/**
	 * Get maxPercentNeutralResistance
	 *
	 * @return integer
	 */
	public function getMaxPercentNeutralResistance()
	{
		return $this->maxPercentNeutralResistance;
	}

	/**
	 * Set percentNeutralResistance
	 *
	 * @param array $percentNeutralResistance
	 * @return object
	 */
	public function setPercentNeutralResistance(array $percentNeutralResistance)
	{
		$this->minPercentNeutralResistance = $percentNeutralResistance['min'];
		$this->maxPercentNeutralResistance = $percentNeutralResistance['max'];
		return $this;
	}
	
	/**
	 * Get percentNeutralResistance
	 *
	 * @return array
	 */
	public function getPercentNeutralResistance()
	{
		return [ 'min' => $this->minPercentNeutralResistance, 'max' => $this->maxPercentNeutralResistance ];
	}

	/**
	 * Set minPercentEarthResistance
	 *
	 * @param integer $minPercentEarthResistance
	 * @return object
	 */
	public function setMinPercentEarthResistance($minPercentEarthResistance)
	{
		$this->minPercentEarthResistance = $minPercentEarthResistance;
		return $this;
	}
	
	/**
	 * Get minPercentEarthResistance
	 *
	 * @return integer
	 */
	public function getMinPercentEarthResistance()
	{
		return $this->minPercentEarthResistance;
	}

	/**
	 * Set maxPercentEarthResistance
	 *
	 * @param integer $maxPercentEarthResistance
	 * @return object
	 */
	public function setMaxPercentEarthResistance($maxPercentEarthResistance)
	{
		$this->maxPercentEarthResistance = $maxPercentEarthResistance;
		return $this;
	}
	
	/**
	 * Get maxPercentEarthResistance
	 *
	 * @return integer
	 */
	public function getMaxPercentEarthResistance()
	{
		return $this->maxPercentEarthResistance;
	}

	/**
	 * Set percentEarthResistance
	 *
	 * @param array $percentEarthResistance
	 * @return object
	 */
	public function setPercentEarthResistance(array $percentEarthResistance)
	{
		$this->minPercentEarthResistance = $percentEarthResistance['min'];
		$this->maxPercentEarthResistance = $percentEarthResistance['max'];
		return $this;
	}
	
	/**
	 * Get percentEarthResistance
	 *
	 * @return array
	 */
	public function getPercentEarthResistance()
	{
		return [ 'min' => $this->minPercentEarthResistance, 'max' => $this->maxPercentEarthResistance ];
	}

	/**
	 * Set minPercentFireResistance
	 *
	 * @param integer $minPercentFireResistance
	 * @return object
	 */
	public function setMinPercentFireResistance($minPercentFireResistance)
	{
		$this->minPercentFireResistance = $minPercentFireResistance;
		return $this;
	}
	
	/**
	 * Get minPercentFireResistance
	 *
	 * @return integer
	 */
	public function getMinPercentFireResistance()
	{
		return $this->minPercentFireResistance;
	}

	/**
	 * Set maxPercentFireResistance
	 *
	 * @param integer $maxPercentFireResistance
	 * @return object
	 */
	public function setMaxPercentFireResistance($maxPercentFireResistance)
	{
		$this->maxPercentFireResistance = $maxPercentFireResistance;
		return $this;
	}
	
	/**
	 * Get maxPercentFireResistance
	 *
	 * @return integer
	 */
	public function getMaxPercentFireResistance()
	{
		return $this->maxPercentFireResistance;
	}

	/**
	 * Set percentFireResistance
	 *
	 * @param array $percentFireResistance
	 * @return object
	 */
	public function setPercentFireResistance(array $percentFireResistance)
	{
		$this->minPercentFireResistance = $percentFireResistance['min'];
		$this->maxPercentFireResistance = $percentFireResistance['max'];
		return $this;
	}
	
	/**
	 * Get percentFireResistance
	 *
	 * @return array
	 */
	public function getPercentFireResistance()
	{
		return [ 'min' => $this->minPercentFireResistance, 'max' => $this->maxPercentFireResistance ];
	}

	/**
	 * Set minPercentWaterResistance
	 *
	 * @param integer $minPercentWaterResistance
	 * @return object
	 */
	public function setMinPercentWaterResistance($minPercentWaterResistance)
	{
		$this->minPercentWaterResistance = $minPercentWaterResistance;
		return $this;
	}
	
	/**
	 * Get minPercentWaterResistance
	 *
	 * @return integer
	 */
	public function getMinPercentWaterResistance()
	{
		return $this->minPercentWaterResistance;
	}

	/**
	 * Set maxPercentWaterResistance
	 *
	 * @param integer $maxPercentWaterResistance
	 * @return object
	 */
	public function setMaxPercentWaterResistance($maxPercentWaterResistance)
	{
		$this->maxPercentWaterResistance = $maxPercentWaterResistance;
		return $this;
	}
	
	/**
	 * Get maxPercentWaterResistance
	 *
	 * @return integer
	 */
	public function getMaxPercentWaterResistance()
	{
		return $this->maxPercentWaterResistance;
	}

	/**
	 * Set percentWaterResistance
	 *
	 * @param array $percentWaterResistance
	 * @return object
	 */
	public function setPercentWaterResistance(array $percentWaterResistance)
	{
		$this->minPercentWaterResistance = $percentWaterResistance['min'];
		$this->maxPercentWaterResistance = $percentWaterResistance['max'];
		return $this;
	}
	
	/**
	 * Get percentWaterResistance
	 *
	 * @return array
	 */
	public function getPercentWaterResistance()
	{
		return [ 'min' => $this->minPercentWaterResistance, 'max' => $this->maxPercentWaterResistance ];
	}

	/**
	 * Set minPercentAirResistance
	 *
	 * @param integer $minPercentAirResistance
	 * @return object
	 */
	public function setMinPercentAirResistance($minPercentAirResistance)
	{
		$this->minPercentAirResistance = $minPercentAirResistance;
		return $this;
	}
	
	/**
	 * Get minPercentAirResistance
	 *
	 * @return integer
	 */
	public function getMinPercentAirResistance()
	{
		return $this->minPercentAirResistance;
	}

	/**
	 * Set maxPercentAirResistance
	 *
	 * @param integer $maxPercentAirResistance
	 * @return object
	 */
	public function setMaxPercentAirResistance($maxPercentAirResistance)
	{
		$this->maxPercentAirResistance = $maxPercentAirResistance;
		return $this;
	}
	
	/**
	 * Get maxPercentAirResistance
	 *
	 * @return integer
	 */
	public function getMaxPercentAirResistance()
	{
		return $this->maxPercentAirResistance;
	}

	/**
	 * Set percentAirResistance
	 *
	 * @param array $percentAirResistance
	 * @return object
	 */
	public function setPercentAirResistance(array $percentAirResistance)
	{
		$this->minPercentAirResistance = $percentAirResistance['min'];
		$this->maxPercentAirResistance = $percentAirResistance['max'];
		return $this;
	}
	
	/**
	 * Get percentAirResistance
	 *
	 * @return array
	 */
	public function getPercentAirResistance()
	{
		return [ 'min' => $this->minPercentAirResistance, 'max' => $this->maxPercentAirResistance ];
	}

	/**
	 * Set minNeutralResistance
	 *
	 * @param integer $minNeutralResistance
	 * @return object
	 */
	public function setMinNeutralResistance($minNeutralResistance)
	{
		$this->minNeutralResistance = $minNeutralResistance;
		return $this;
	}
	
	/**
	 * Get minNeutralResistance
	 *
	 * @return integer
	 */
	public function getMinNeutralResistance()
	{
		return $this->minNeutralResistance;
	}

	/**
	 * Set maxNeutralResistance
	 *
	 * @param integer $maxNeutralResistance
	 * @return object
	 */
	public function setMaxNeutralResistance($maxNeutralResistance)
	{
		$this->maxNeutralResistance = $maxNeutralResistance;
		return $this;
	}
	
	/**
	 * Get maxNeutralResistance
	 *
	 * @return integer
	 */
	public function getMaxNeutralResistance()
	{
		return $this->maxNeutralResistance;
	}

	/**
	 * Set neutralResistance
	 *
	 * @param array $neutralResistance
	 * @return object
	 */
	public function setNeutralResistance(array $neutralResistance)
	{
		$this->minNeutralResistance = $neutralResistance['min'];
		$this->maxNeutralResistance = $neutralResistance['max'];
		return $this;
	}
	
	/**
	 * Get neutralResistance
	 *
	 * @return array
	 */
	public function getNeutralResistance()
	{
		return [ 'min' => $this->minNeutralResistance, 'max' => $this->maxNeutralResistance ];
	}

	/**
	 * Set minEarthResistance
	 *
	 * @param integer $minEarthResistance
	 * @return object
	 */
	public function setMinEarthResistance($minEarthResistance)
	{
		$this->minEarthResistance = $minEarthResistance;
		return $this;
	}
	
	/**
	 * Get minEarthResistance
	 *
	 * @return integer
	 */
	public function getMinEarthResistance()
	{
		return $this->minEarthResistance;
	}

	/**
	 * Set maxEarthResistance
	 *
	 * @param integer $maxEarthResistance
	 * @return object
	 */
	public function setMaxEarthResistance($maxEarthResistance)
	{
		$this->maxEarthResistance = $maxEarthResistance;
		return $this;
	}
	
	/**
	 * Get maxEarthResistance
	 *
	 * @return integer
	 */
	public function getMaxEarthResistance()
	{
		return $this->maxEarthResistance;
	}

	/**
	 * Set earthResistance
	 *
	 * @param array $earthResistance
	 * @return object
	 */
	public function setEarthResistance(array $earthResistance)
	{
		$this->minEarthResistance = $earthResistance['min'];
		$this->maxEarthResistance = $earthResistance['max'];
		return $this;
	}
	
	/**
	 * Get earthResistance
	 *
	 * @return array
	 */
	public function getEarthResistance()
	{
		return [ 'min' => $this->minEarthResistance, 'max' => $this->maxEarthResistance ];
	}

	/**
	 * Set minFireResistance
	 *
	 * @param integer $minFireResistance
	 * @return object
	 */
	public function setMinFireResistance($minFireResistance)
	{
		$this->minFireResistance = $minFireResistance;
		return $this;
	}
	
	/**
	 * Get minFireResistance
	 *
	 * @return integer
	 */
	public function getMinFireResistance()
	{
		return $this->minFireResistance;
	}

	/**
	 * Set maxFireResistance
	 *
	 * @param integer $maxFireResistance
	 * @return object
	 */
	public function setMaxFireResistance($maxFireResistance)
	{
		$this->maxFireResistance = $maxFireResistance;
		return $this;
	}
	
	/**
	 * Get maxFireResistance
	 *
	 * @return integer
	 */
	public function getMaxFireResistance()
	{
		return $this->maxFireResistance;
	}

	/**
	 * Set fireResistance
	 *
	 * @param array $fireResistance
	 * @return object
	 */
	public function setFireResistance(array $fireResistance)
	{
		$this->minFireResistance = $fireResistance['min'];
		$this->maxFireResistance = $fireResistance['max'];
		return $this;
	}
	
	/**
	 * Get fireResistance
	 *
	 * @return array
	 */
	public function getFireResistance()
	{
		return [ 'min' => $this->minFireResistance, 'max' => $this->maxFireResistance ];
	}

	/**
	 * Set minWaterResistance
	 *
	 * @param integer $minWaterResistance
	 * @return object
	 */
	public function setMinWaterResistance($minWaterResistance)
	{
		$this->minWaterResistance = $minWaterResistance;
		return $this;
	}
	
	/**
	 * Get minWaterResistance
	 *
	 * @return integer
	 */
	public function getMinWaterResistance()
	{
		return $this->minWaterResistance;
	}

	/**
	 * Set maxWaterResistance
	 *
	 * @param integer $maxWaterResistance
	 * @return object
	 */
	public function setMaxWaterResistance($maxWaterResistance)
	{
		$this->maxWaterResistance = $maxWaterResistance;
		return $this;
	}
	
	/**
	 * Get maxWaterResistance
	 *
	 * @return integer
	 */
	public function getMaxWaterResistance()
	{
		return $this->maxWaterResistance;
	}

	/**
	 * Set waterResistance
	 *
	 * @param array $waterResistance
	 * @return object
	 */
	public function setWaterResistance(array $waterResistance)
	{
		$this->minWaterResistance = $waterResistance['min'];
		$this->maxWaterResistance = $waterResistance['max'];
		return $this;
	}
	
	/**
	 * Get waterResistance
	 *
	 * @return array
	 */
	public function getWaterResistance()
	{
		return [ 'min' => $this->minWaterResistance, 'max' => $this->maxWaterResistance ];
	}

	/**
	 * Set minAirResistance
	 *
	 * @param integer $minAirResistance
	 * @return object
	 */
	public function setMinAirResistance($minAirResistance)
	{
		$this->minAirResistance = $minAirResistance;
		return $this;
	}
	
	/**
	 * Get minAirResistance
	 *
	 * @return integer
	 */
	public function getMinAirResistance()
	{
		return $this->minAirResistance;
	}

	/**
	 * Set maxAirResistance
	 *
	 * @param integer $maxAirResistance
	 * @return object
	 */
	public function setMaxAirResistance($maxAirResistance)
	{
		$this->maxAirResistance = $maxAirResistance;
		return $this;
	}
	
	/**
	 * Get maxAirResistance
	 *
	 * @return integer
	 */
	public function getMaxAirResistance()
	{
		return $this->maxAirResistance;
	}

	/**
	 * Set airResistance
	 *
	 * @param array $airResistance
	 * @return object
	 */
	public function setAirResistance(array $airResistance)
	{
		$this->minAirResistance = $airResistance['min'];
		$this->maxAirResistance = $airResistance['max'];
		return $this;
	}
	
	/**
	 * Get airResistance
	 *
	 * @return array
	 */
	public function getAirResistance()
	{
		return [ 'min' => $this->minAirResistance, 'max' => $this->maxAirResistance ];
	}

	/**
	 * Set minPercentNeutralResistanceInPvp
	 *
	 * @param integer $minPercentNeutralResistanceInPvp
	 * @return object
	 */
	public function setMinPercentNeutralResistanceInPvp($minPercentNeutralResistanceInPvp)
	{
		$this->minPercentNeutralResistanceInPvp = $minPercentNeutralResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minPercentNeutralResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinPercentNeutralResistanceInPvp()
	{
		return $this->minPercentNeutralResistanceInPvp;
	}

	/**
	 * Set maxPercentNeutralResistanceInPvp
	 *
	 * @param integer $maxPercentNeutralResistanceInPvp
	 * @return object
	 */
	public function setMaxPercentNeutralResistanceInPvp($maxPercentNeutralResistanceInPvp)
	{
		$this->maxPercentNeutralResistanceInPvp = $maxPercentNeutralResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxPercentNeutralResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxPercentNeutralResistanceInPvp()
	{
		return $this->maxPercentNeutralResistanceInPvp;
	}

	/**
	 * Set percentNeutralResistanceInPvp
	 *
	 * @param array $percentNeutralResistanceInPvp
	 * @return object
	 */
	public function setPercentNeutralResistanceInPvp(array $percentNeutralResistanceInPvp)
	{
		$this->minPercentNeutralResistanceInPvp = $percentNeutralResistanceInPvp['min'];
		$this->maxPercentNeutralResistanceInPvp = $percentNeutralResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get percentNeutralResistanceInPvp
	 *
	 * @return array
	 */
	public function getPercentNeutralResistanceInPvp()
	{
		return [ 'min' => $this->minPercentNeutralResistanceInPvp, 'max' => $this->maxPercentNeutralResistanceInPvp ];
	}

	/**
	 * Set minPercentEarthResistanceInPvp
	 *
	 * @param integer $minPercentEarthResistanceInPvp
	 * @return object
	 */
	public function setMinPercentEarthResistanceInPvp($minPercentEarthResistanceInPvp)
	{
		$this->minPercentEarthResistanceInPvp = $minPercentEarthResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minPercentEarthResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinPercentEarthResistanceInPvp()
	{
		return $this->minPercentEarthResistanceInPvp;
	}

	/**
	 * Set maxPercentEarthResistanceInPvp
	 *
	 * @param integer $maxPercentEarthResistanceInPvp
	 * @return object
	 */
	public function setMaxPercentEarthResistanceInPvp($maxPercentEarthResistanceInPvp)
	{
		$this->maxPercentEarthResistanceInPvp = $maxPercentEarthResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxPercentEarthResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxPercentEarthResistanceInPvp()
	{
		return $this->maxPercentEarthResistanceInPvp;
	}

	/**
	 * Set percentEarthResistanceInPvp
	 *
	 * @param array $percentEarthResistanceInPvp
	 * @return object
	 */
	public function setPercentEarthResistanceInPvp(array $percentEarthResistanceInPvp)
	{
		$this->minPercentEarthResistanceInPvp = $percentEarthResistanceInPvp['min'];
		$this->maxPercentEarthResistanceInPvp = $percentEarthResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get percentEarthResistanceInPvp
	 *
	 * @return array
	 */
	public function getPercentEarthResistanceInPvp()
	{
		return [ 'min' => $this->minPercentEarthResistanceInPvp, 'max' => $this->maxPercentEarthResistanceInPvp ];
	}

	/**
	 * Set minPercentFireResistanceInPvp
	 *
	 * @param integer $minPercentFireResistanceInPvp
	 * @return object
	 */
	public function setMinPercentFireResistanceInPvp($minPercentFireResistanceInPvp)
	{
		$this->minPercentFireResistanceInPvp = $minPercentFireResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minPercentFireResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinPercentFireResistanceInPvp()
	{
		return $this->minPercentFireResistanceInPvp;
	}

	/**
	 * Set maxPercentFireResistanceInPvp
	 *
	 * @param integer $maxPercentFireResistanceInPvp
	 * @return object
	 */
	public function setMaxPercentFireResistanceInPvp($maxPercentFireResistanceInPvp)
	{
		$this->maxPercentFireResistanceInPvp = $maxPercentFireResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxPercentFireResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxPercentFireResistanceInPvp()
	{
		return $this->maxPercentFireResistanceInPvp;
	}

	/**
	 * Set percentFireResistanceInPvp
	 *
	 * @param array $percentFireResistanceInPvp
	 * @return object
	 */
	public function setPercentFireResistanceInPvp(array $percentFireResistanceInPvp)
	{
		$this->minPercentFireResistanceInPvp = $percentFireResistanceInPvp['min'];
		$this->maxPercentFireResistanceInPvp = $percentFireResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get percentFireResistanceInPvp
	 *
	 * @return array
	 */
	public function getPercentFireResistanceInPvp()
	{
		return [ 'min' => $this->minPercentFireResistanceInPvp, 'max' => $this->maxPercentFireResistanceInPvp ];
	}

	/**
	 * Set minPercentWaterResistanceInPvp
	 *
	 * @param integer $minPercentWaterResistanceInPvp
	 * @return object
	 */
	public function setMinPercentWaterResistanceInPvp($minPercentWaterResistanceInPvp)
	{
		$this->minPercentWaterResistanceInPvp = $minPercentWaterResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minPercentWaterResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinPercentWaterResistanceInPvp()
	{
		return $this->minPercentWaterResistanceInPvp;
	}

	/**
	 * Set maxPercentWaterResistanceInPvp
	 *
	 * @param integer $maxPercentWaterResistanceInPvp
	 * @return object
	 */
	public function setMaxPercentWaterResistanceInPvp($maxPercentWaterResistanceInPvp)
	{
		$this->maxPercentWaterResistanceInPvp = $maxPercentWaterResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxPercentWaterResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxPercentWaterResistanceInPvp()
	{
		return $this->maxPercentWaterResistanceInPvp;
	}

	/**
	 * Set percentWaterResistanceInPvp
	 *
	 * @param array $percentWaterResistanceInPvp
	 * @return object
	 */
	public function setPercentWaterResistanceInPvp(array $percentWaterResistanceInPvp)
	{
		$this->minPercentWaterResistanceInPvp = $percentWaterResistanceInPvp['min'];
		$this->maxPercentWaterResistanceInPvp = $percentWaterResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get percentWaterResistanceInPvp
	 *
	 * @return array
	 */
	public function getPercentWaterResistanceInPvp()
	{
		return [ 'min' => $this->minPercentWaterResistanceInPvp, 'max' => $this->maxPercentWaterResistanceInPvp ];
	}

	/**
	 * Set minPercentAirResistanceInPvp
	 *
	 * @param integer $minPercentAirResistanceInPvp
	 * @return object
	 */
	public function setMinPercentAirResistanceInPvp($minPercentAirResistanceInPvp)
	{
		$this->minPercentAirResistanceInPvp = $minPercentAirResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minPercentAirResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinPercentAirResistanceInPvp()
	{
		return $this->minPercentAirResistanceInPvp;
	}

	/**
	 * Set maxPercentAirResistanceInPvp
	 *
	 * @param integer $maxPercentAirResistanceInPvp
	 * @return object
	 */
	public function setMaxPercentAirResistanceInPvp($maxPercentAirResistanceInPvp)
	{
		$this->maxPercentAirResistanceInPvp = $maxPercentAirResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxPercentAirResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxPercentAirResistanceInPvp()
	{
		return $this->maxPercentAirResistanceInPvp;
	}

	/**
	 * Set percentAirResistanceInPvp
	 *
	 * @param array $percentAirResistanceInPvp
	 * @return object
	 */
	public function setPercentAirResistanceInPvp(array $percentAirResistanceInPvp)
	{
		$this->minPercentAirResistanceInPvp = $percentAirResistanceInPvp['min'];
		$this->maxPercentAirResistanceInPvp = $percentAirResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get percentAirResistanceInPvp
	 *
	 * @return array
	 */
	public function getPercentAirResistanceInPvp()
	{
		return [ 'min' => $this->minPercentAirResistanceInPvp, 'max' => $this->maxPercentAirResistanceInPvp ];
	}

	/**
	 * Set minNeutralResistanceInPvp
	 *
	 * @param integer $minNeutralResistanceInPvp
	 * @return object
	 */
	public function setMinNeutralResistanceInPvp($minNeutralResistanceInPvp)
	{
		$this->minNeutralResistanceInPvp = $minNeutralResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minNeutralResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinNeutralResistanceInPvp()
	{
		return $this->minNeutralResistanceInPvp;
	}

	/**
	 * Set maxNeutralResistanceInPvp
	 *
	 * @param integer $maxNeutralResistanceInPvp
	 * @return object
	 */
	public function setMaxNeutralResistanceInPvp($maxNeutralResistanceInPvp)
	{
		$this->maxNeutralResistanceInPvp = $maxNeutralResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxNeutralResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxNeutralResistanceInPvp()
	{
		return $this->maxNeutralResistanceInPvp;
	}

	/**
	 * Set neutralResistanceInPvp
	 *
	 * @param array $neutralResistanceInPvp
	 * @return object
	 */
	public function setNeutralResistanceInPvp(array $neutralResistanceInPvp)
	{
		$this->minNeutralResistanceInPvp = $neutralResistanceInPvp['min'];
		$this->maxNeutralResistanceInPvp = $neutralResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get neutralResistanceInPvp
	 *
	 * @return array
	 */
	public function getNeutralResistanceInPvp()
	{
		return [ 'min' => $this->minNeutralResistanceInPvp, 'max' => $this->maxNeutralResistanceInPvp ];
	}

	/**
	 * Set minEarthResistanceInPvp
	 *
	 * @param integer $minEarthResistanceInPvp
	 * @return object
	 */
	public function setMinEarthResistanceInPvp($minEarthResistanceInPvp)
	{
		$this->minEarthResistanceInPvp = $minEarthResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minEarthResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinEarthResistanceInPvp()
	{
		return $this->minEarthResistanceInPvp;
	}

	/**
	 * Set maxEarthResistanceInPvp
	 *
	 * @param integer $maxEarthResistanceInPvp
	 * @return object
	 */
	public function setMaxEarthResistanceInPvp($maxEarthResistanceInPvp)
	{
		$this->maxEarthResistanceInPvp = $maxEarthResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxEarthResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxEarthResistanceInPvp()
	{
		return $this->maxEarthResistanceInPvp;
	}

	/**
	 * Set earthResistanceInPvp
	 *
	 * @param array $earthResistanceInPvp
	 * @return object
	 */
	public function setEarthResistanceInPvp(array $earthResistanceInPvp)
	{
		$this->minEarthResistanceInPvp = $earthResistanceInPvp['min'];
		$this->maxEarthResistanceInPvp = $earthResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get earthResistanceInPvp
	 *
	 * @return array
	 */
	public function getEarthResistanceInPvp()
	{
		return [ 'min' => $this->minEarthResistanceInPvp, 'max' => $this->maxEarthResistanceInPvp ];
	}

	/**
	 * Set minFireResistanceInPvp
	 *
	 * @param integer $minFireResistanceInPvp
	 * @return object
	 */
	public function setMinFireResistanceInPvp($minFireResistanceInPvp)
	{
		$this->minFireResistanceInPvp = $minFireResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minFireResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinFireResistanceInPvp()
	{
		return $this->minFireResistanceInPvp;
	}

	/**
	 * Set maxFireResistanceInPvp
	 *
	 * @param integer $maxFireResistanceInPvp
	 * @return object
	 */
	public function setMaxFireResistanceInPvp($maxFireResistanceInPvp)
	{
		$this->maxFireResistanceInPvp = $maxFireResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxFireResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxFireResistanceInPvp()
	{
		return $this->maxFireResistanceInPvp;
	}

	/**
	 * Set fireResistanceInPvp
	 *
	 * @param array $fireResistanceInPvp
	 * @return object
	 */
	public function setFireResistanceInPvp(array $fireResistanceInPvp)
	{
		$this->minFireResistanceInPvp = $fireResistanceInPvp['min'];
		$this->maxFireResistanceInPvp = $fireResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get fireResistanceInPvp
	 *
	 * @return array
	 */
	public function getFireResistanceInPvp()
	{
		return [ 'min' => $this->minFireResistanceInPvp, 'max' => $this->maxFireResistanceInPvp ];
	}

	/**
	 * Set minWaterResistanceInPvp
	 *
	 * @param integer $minWaterResistanceInPvp
	 * @return object
	 */
	public function setMinWaterResistanceInPvp($minWaterResistanceInPvp)
	{
		$this->minWaterResistanceInPvp = $minWaterResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minWaterResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinWaterResistanceInPvp()
	{
		return $this->minWaterResistanceInPvp;
	}

	/**
	 * Set maxWaterResistanceInPvp
	 *
	 * @param integer $maxWaterResistanceInPvp
	 * @return object
	 */
	public function setMaxWaterResistanceInPvp($maxWaterResistanceInPvp)
	{
		$this->maxWaterResistanceInPvp = $maxWaterResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxWaterResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxWaterResistanceInPvp()
	{
		return $this->maxWaterResistanceInPvp;
	}

	/**
	 * Set waterResistanceInPvp
	 *
	 * @param array $waterResistanceInPvp
	 * @return object
	 */
	public function setWaterResistanceInPvp(array $waterResistanceInPvp)
	{
		$this->minWaterResistanceInPvp = $waterResistanceInPvp['min'];
		$this->maxWaterResistanceInPvp = $waterResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get waterResistanceInPvp
	 *
	 * @return array
	 */
	public function getWaterResistanceInPvp()
	{
		return [ 'min' => $this->minWaterResistanceInPvp, 'max' => $this->maxWaterResistanceInPvp ];
	}

	/**
	 * Set minAirResistanceInPvp
	 *
	 * @param integer $minAirResistanceInPvp
	 * @return object
	 */
	public function setMinAirResistanceInPvp($minAirResistanceInPvp)
	{
		$this->minAirResistanceInPvp = $minAirResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get minAirResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMinAirResistanceInPvp()
	{
		return $this->minAirResistanceInPvp;
	}

	/**
	 * Set maxAirResistanceInPvp
	 *
	 * @param integer $maxAirResistanceInPvp
	 * @return object
	 */
	public function setMaxAirResistanceInPvp($maxAirResistanceInPvp)
	{
		$this->maxAirResistanceInPvp = $maxAirResistanceInPvp;
		return $this;
	}
	
	/**
	 * Get maxAirResistanceInPvp
	 *
	 * @return integer
	 */
	public function getMaxAirResistanceInPvp()
	{
		return $this->maxAirResistanceInPvp;
	}

	/**
	 * Set airResistanceInPvp
	 *
	 * @param array $airResistanceInPvp
	 * @return object
	 */
	public function setAirResistanceInPvp(array $airResistanceInPvp)
	{
		$this->minAirResistanceInPvp = $airResistanceInPvp['min'];
		$this->maxAirResistanceInPvp = $airResistanceInPvp['max'];
		return $this;
	}
	
	/**
	 * Get airResistanceInPvp
	 *
	 * @return array
	 */
	public function getAirResistanceInPvp()
	{
		return [ 'min' => $this->minAirResistanceInPvp, 'max' => $this->maxAirResistanceInPvp ];
	}

	/**
	 * Set minLock
	 *
	 * @param integer $minLock
	 * @return object
	 */
	public function setMinLock($minLock)
	{
		$this->minLock = $minLock;
		return $this;
	}
	
	/**
	 * Get minLock
	 *
	 * @return integer
	 */
	public function getMinLock()
	{
		return $this->minLock;
	}

	/**
	 * Set maxLock
	 *
	 * @param integer $maxLock
	 * @return object
	 */
	public function setMaxLock($maxLock)
	{
		$this->maxLock = $maxLock;
		return $this;
	}
	
	/**
	 * Get maxLock
	 *
	 * @return integer
	 */
	public function getMaxLock()
	{
		return $this->maxLock;
	}

	/**
	 * Set lock
	 *
	 * @param array $lock
	 * @return object
	 */
	public function setLock(array $lock)
	{
		$this->minLock = $lock['min'];
		$this->maxLock = $lock['max'];
		return $this;
	}
	
	/**
	 * Get lock
	 *
	 * @return array
	 */
	public function getLock()
	{
		return [ 'min' => $this->minLock, 'max' => $this->maxLock ];
	}

	/**
	 * Set minDodge
	 *
	 * @param integer $minDodge
	 * @return object
	 */
	public function setMinDodge($minDodge)
	{
		$this->minDodge = $minDodge;
		return $this;
	}
	
	/**
	 * Get minDodge
	 *
	 * @return integer
	 */
	public function getMinDodge()
	{
		return $this->minDodge;
	}

	/**
	 * Set maxDodge
	 *
	 * @param integer $maxDodge
	 * @return object
	 */
	public function setMaxDodge($maxDodge)
	{
		$this->maxDodge = $maxDodge;
		return $this;
	}
	
	/**
	 * Get maxDodge
	 *
	 * @return integer
	 */
	public function getMaxDodge()
	{
		return $this->maxDodge;
	}

	/**
	 * Set dodge
	 *
	 * @param array $dodge
	 * @return object
	 */
	public function setDodge(array $dodge)
	{
		$this->minDodge = $dodge['min'];
		$this->maxDodge = $dodge['max'];
		return $this;
	}
	
	/**
	 * Get dodge
	 *
	 * @return array
	 */
	public function getDodge()
	{
		return [ 'min' => $this->minDodge, 'max' => $this->maxDodge ];
	}

	/**
	 * Set minApReduction
	 *
	 * @param integer $minApReduction
	 * @return object
	 */
	public function setMinApReduction($minApReduction)
	{
		$this->minApReduction = $minApReduction;
		return $this;
	}
	
	/**
	 * Get minApReduction
	 *
	 * @return integer
	 */
	public function getMinApReduction()
	{
		return $this->minApReduction;
	}

	/**
	 * Set maxApReduction
	 *
	 * @param integer $maxApReduction
	 * @return object
	 */
	public function setMaxApReduction($maxApReduction)
	{
		$this->maxApReduction = $maxApReduction;
		return $this;
	}
	
	/**
	 * Get maxApReduction
	 *
	 * @return integer
	 */
	public function getMaxApReduction()
	{
		return $this->maxApReduction;
	}

	/**
	 * Set apReduction
	 *
	 * @param array $apReduction
	 * @return object
	 */
	public function setApReduction(array $apReduction)
	{
		$this->minApReduction = $apReduction['min'];
		$this->maxApReduction = $apReduction['max'];
		return $this;
	}
	
	/**
	 * Get apReduction
	 *
	 * @return array
	 */
	public function getApReduction()
	{
		return [ 'min' => $this->minApReduction, 'max' => $this->maxApReduction ];
	}

	/**
	 * Set minMpReduction
	 *
	 * @param integer $minMpReduction
	 * @return object
	 */
	public function setMinMpReduction($minMpReduction)
	{
		$this->minMpReduction = $minMpReduction;
		return $this;
	}
	
	/**
	 * Get minMpReduction
	 *
	 * @return integer
	 */
	public function getMinMpReduction()
	{
		return $this->minMpReduction;
	}

	/**
	 * Set maxMpReduction
	 *
	 * @param integer $maxMpReduction
	 * @return object
	 */
	public function setMaxMpReduction($maxMpReduction)
	{
		$this->maxMpReduction = $maxMpReduction;
		return $this;
	}
	
	/**
	 * Get maxMpReduction
	 *
	 * @return integer
	 */
	public function getMaxMpReduction()
	{
		return $this->maxMpReduction;
	}

	/**
	 * Set mpReduction
	 *
	 * @param array $mpReduction
	 * @return object
	 */
	public function setMpReduction(array $mpReduction)
	{
		$this->minMpReduction = $mpReduction['min'];
		$this->maxMpReduction = $mpReduction['max'];
		return $this;
	}
	
	/**
	 * Get mpReduction
	 *
	 * @return array
	 */
	public function getMpReduction()
	{
		return [ 'min' => $this->minMpReduction, 'max' => $this->maxMpReduction ];
	}

	/**
	 * Set minApLossResistance
	 *
	 * @param integer $minApLossResistance
	 * @return object
	 */
	public function setMinApLossResistance($minApLossResistance)
	{
		$this->minApLossResistance = $minApLossResistance;
		return $this;
	}
	
	/**
	 * Get minApLossResistance
	 *
	 * @return integer
	 */
	public function getMinApLossResistance()
	{
		return $this->minApLossResistance;
	}

	/**
	 * Set maxApLossResistance
	 *
	 * @param integer $maxApLossResistance
	 * @return object
	 */
	public function setMaxApLossResistance($maxApLossResistance)
	{
		$this->maxApLossResistance = $maxApLossResistance;
		return $this;
	}
	
	/**
	 * Get maxApLossResistance
	 *
	 * @return integer
	 */
	public function getMaxApLossResistance()
	{
		return $this->maxApLossResistance;
	}

	/**
	 * Set apLossResistance
	 *
	 * @param array $apLossResistance
	 * @return object
	 */
	public function setApLossResistance(array $apLossResistance)
	{
		$this->minApLossResistance = $apLossResistance['min'];
		$this->maxApLossResistance = $apLossResistance['max'];
		return $this;
	}
	
	/**
	 * Get apLossResistance
	 *
	 * @return array
	 */
	public function getApLossResistance()
	{
		return [ 'min' => $this->minApLossResistance, 'max' => $this->maxApLossResistance ];
	}

	/**
	 * Set minMpLossResistance
	 *
	 * @param integer $minMpLossResistance
	 * @return object
	 */
	public function setMinMpLossResistance($minMpLossResistance)
	{
		$this->minMpLossResistance = $minMpLossResistance;
		return $this;
	}
	
	/**
	 * Get minMpLossResistance
	 *
	 * @return integer
	 */
	public function getMinMpLossResistance()
	{
		return $this->minMpLossResistance;
	}

	/**
	 * Set maxMpLossResistance
	 *
	 * @param integer $maxMpLossResistance
	 * @return object
	 */
	public function setMaxMpLossResistance($maxMpLossResistance)
	{
		$this->maxMpLossResistance = $maxMpLossResistance;
		return $this;
	}
	
	/**
	 * Get maxMpLossResistance
	 *
	 * @return integer
	 */
	public function getMaxMpLossResistance()
	{
		return $this->maxMpLossResistance;
	}

	/**
	 * Set mpLossResistance
	 *
	 * @param array $mpLossResistance
	 * @return object
	 */
	public function setMpLossResistance(array $mpLossResistance)
	{
		$this->minMpLossResistance = $mpLossResistance['min'];
		$this->maxMpLossResistance = $mpLossResistance['max'];
		return $this;
	}
	
	/**
	 * Get mpLossResistance
	 *
	 * @return array
	 */
	public function getMpLossResistance()
	{
		return [ 'min' => $this->minMpLossResistance, 'max' => $this->maxMpLossResistance ];
	}

	/**
	 * Set minCriticalDamage
	 *
	 * @param integer $minCriticalDamage
	 * @return object
	 */
	public function setMinCriticalDamage($minCriticalDamage)
	{
		$this->minCriticalDamage = $minCriticalDamage;
		return $this;
	}
	
	/**
	 * Get minCriticalDamage
	 *
	 * @return integer
	 */
	public function getMinCriticalDamage()
	{
		return $this->minCriticalDamage;
	}

	/**
	 * Set maxCriticalDamage
	 *
	 * @param integer $maxCriticalDamage
	 * @return object
	 */
	public function setMaxCriticalDamage($maxCriticalDamage)
	{
		$this->maxCriticalDamage = $maxCriticalDamage;
		return $this;
	}
	
	/**
	 * Get maxCriticalDamage
	 *
	 * @return integer
	 */
	public function getMaxCriticalDamage()
	{
		return $this->maxCriticalDamage;
	}

	/**
	 * Set criticalDamage
	 *
	 * @param array $criticalDamage
	 * @return object
	 */
	public function setCriticalDamage(array $criticalDamage)
	{
		$this->minCriticalDamage = $criticalDamage['min'];
		$this->maxCriticalDamage = $criticalDamage['max'];
		return $this;
	}
	
	/**
	 * Get criticalDamage
	 *
	 * @return array
	 */
	public function getCriticalDamage()
	{
		return [ 'min' => $this->minCriticalDamage, 'max' => $this->maxCriticalDamage ];
	}

	/**
	 * Set minCriticalResistance
	 *
	 * @param integer $minCriticalResistance
	 * @return object
	 */
	public function setMinCriticalResistance($minCriticalResistance)
	{
		$this->minCriticalResistance = $minCriticalResistance;
		return $this;
	}
	
	/**
	 * Get minCriticalResistance
	 *
	 * @return integer
	 */
	public function getMinCriticalResistance()
	{
		return $this->minCriticalResistance;
	}

	/**
	 * Set maxCriticalResistance
	 *
	 * @param integer $maxCriticalResistance
	 * @return object
	 */
	public function setMaxCriticalResistance($maxCriticalResistance)
	{
		$this->maxCriticalResistance = $maxCriticalResistance;
		return $this;
	}
	
	/**
	 * Get maxCriticalResistance
	 *
	 * @return integer
	 */
	public function getMaxCriticalResistance()
	{
		return $this->maxCriticalResistance;
	}

	/**
	 * Set criticalResistance
	 *
	 * @param array $criticalResistance
	 * @return object
	 */
	public function setCriticalResistance(array $criticalResistance)
	{
		$this->minCriticalResistance = $criticalResistance['min'];
		$this->maxCriticalResistance = $criticalResistance['max'];
		return $this;
	}
	
	/**
	 * Get criticalResistance
	 *
	 * @return array
	 */
	public function getCriticalResistance()
	{
		return [ 'min' => $this->minCriticalResistance, 'max' => $this->maxCriticalResistance ];
	}

	/**
	 * Set minPushbackDamage
	 *
	 * @param integer $minPushbackDamage
	 * @return object
	 */
	public function setMinPushbackDamage($minPushbackDamage)
	{
		$this->minPushbackDamage = $minPushbackDamage;
		return $this;
	}
	
	/**
	 * Get minPushbackDamage
	 *
	 * @return integer
	 */
	public function getMinPushbackDamage()
	{
		return $this->minPushbackDamage;
	}

	/**
	 * Set maxPushbackDamage
	 *
	 * @param integer $maxPushbackDamage
	 * @return object
	 */
	public function setMaxPushbackDamage($maxPushbackDamage)
	{
		$this->maxPushbackDamage = $maxPushbackDamage;
		return $this;
	}
	
	/**
	 * Get maxPushbackDamage
	 *
	 * @return integer
	 */
	public function getMaxPushbackDamage()
	{
		return $this->maxPushbackDamage;
	}

	/**
	 * Set pushbackDamage
	 *
	 * @param array $pushbackDamage
	 * @return object
	 */
	public function setPushbackDamage(array $pushbackDamage)
	{
		$this->minPushbackDamage = $pushbackDamage['min'];
		$this->maxPushbackDamage = $pushbackDamage['max'];
		return $this;
	}
	
	/**
	 * Get pushbackDamage
	 *
	 * @return array
	 */
	public function getPushbackDamage()
	{
		return [ 'min' => $this->minPushbackDamage, 'max' => $this->maxPushbackDamage ];
	}

	/**
	 * Set minPushbackResistance
	 *
	 * @param integer $minPushbackResistance
	 * @return object
	 */
	public function setMinPushbackResistance($minPushbackResistance)
	{
		$this->minPushbackResistance = $minPushbackResistance;
		return $this;
	}
	
	/**
	 * Get minPushbackResistance
	 *
	 * @return integer
	 */
	public function getMinPushbackResistance()
	{
		return $this->minPushbackResistance;
	}

	/**
	 * Set maxPushbackResistance
	 *
	 * @param integer $maxPushbackResistance
	 * @return object
	 */
	public function setMaxPushbackResistance($maxPushbackResistance)
	{
		$this->maxPushbackResistance = $maxPushbackResistance;
		return $this;
	}
	
	/**
	 * Get maxPushbackResistance
	 *
	 * @return integer
	 */
	public function getMaxPushbackResistance()
	{
		return $this->maxPushbackResistance;
	}

	/**
	 * Set pushbackResistance
	 *
	 * @param array $pushbackResistance
	 * @return object
	 */
	public function setPushbackResistance(array $pushbackResistance)
	{
		$this->minPushbackResistance = $pushbackResistance['min'];
		$this->maxPushbackResistance = $pushbackResistance['max'];
		return $this;
	}
	
	/**
	 * Get pushbackResistance
	 *
	 * @return array
	 */
	public function getPushbackResistance()
	{
		return [ 'min' => $this->minPushbackResistance, 'max' => $this->maxPushbackResistance ];
	}

	/**
	 * Set minTrapPower
	 *
	 * @param integer $minTrapPower
	 * @return object
	 */
	public function setMinTrapPower($minTrapPower)
	{
		$this->minTrapPower = $minTrapPower;
		return $this;
	}
	
	/**
	 * Get minTrapPower
	 *
	 * @return integer
	 */
	public function getMinTrapPower()
	{
		return $this->minTrapPower;
	}

	/**
	 * Set maxTrapPower
	 *
	 * @param integer $maxTrapPower
	 * @return object
	 */
	public function setMaxTrapPower($maxTrapPower)
	{
		$this->maxTrapPower = $maxTrapPower;
		return $this;
	}
	
	/**
	 * Get maxTrapPower
	 *
	 * @return integer
	 */
	public function getMaxTrapPower()
	{
		return $this->maxTrapPower;
	}

	/**
	 * Set trapPower
	 *
	 * @param array $trapPower
	 * @return object
	 */
	public function setTrapPower(array $trapPower)
	{
		$this->minTrapPower = $trapPower['min'];
		$this->maxTrapPower = $trapPower['max'];
		return $this;
	}
	
	/**
	 * Get trapPower
	 *
	 * @return array
	 */
	public function getTrapPower()
	{
		return [ 'min' => $this->minTrapPower, 'max' => $this->maxTrapPower ];
	}

	/**
	 * Set minTrapDamage
	 *
	 * @param integer $minTrapDamage
	 * @return object
	 */
	public function setMinTrapDamage($minTrapDamage)
	{
		$this->minTrapDamage = $minTrapDamage;
		return $this;
	}
	
	/**
	 * Get minTrapDamage
	 *
	 * @return integer
	 */
	public function getMinTrapDamage()
	{
		return $this->minTrapDamage;
	}

	/**
	 * Set maxTrapDamage
	 *
	 * @param integer $maxTrapDamage
	 * @return object
	 */
	public function setMaxTrapDamage($maxTrapDamage)
	{
		$this->maxTrapDamage = $maxTrapDamage;
		return $this;
	}
	
	/**
	 * Get maxTrapDamage
	 *
	 * @return integer
	 */
	public function getMaxTrapDamage()
	{
		return $this->maxTrapDamage;
	}

	/**
	 * Set trapDamage
	 *
	 * @param array $trapDamage
	 * @return object
	 */
	public function setTrapDamage(array $trapDamage)
	{
		$this->minTrapDamage = $trapDamage['min'];
		$this->maxTrapDamage = $trapDamage['max'];
		return $this;
	}
	
	/**
	 * Get trapDamage
	 *
	 * @return array
	 */
	public function getTrapDamage()
	{
		return [ 'min' => $this->minTrapDamage, 'max' => $this->maxTrapDamage ];
	}
	
	
	/**
	 * Set all characteristics
	 *
	 * @param array $characteristics
	 * @param boolean $zeroMissing
	 * @return object
	 */
	public function setCharacteristics(array $characteristics, $zeroMissing = false)
	{
		if (isset($characteristics['vitality'])) {
			$this->minVitality = $characteristics['vitality']['min'];
			$this->maxVitality = $characteristics['vitality']['max'];
		} elseif ($zeroMissing) {
			$this->minVitality = 0;
			$this->maxVitality = 0;
		}
		if (isset($characteristics['strength'])) {
			$this->minStrength = $characteristics['strength']['min'];
			$this->maxStrength = $characteristics['strength']['max'];
		} elseif ($zeroMissing) {
			$this->minStrength = 0;
			$this->maxStrength = 0;
		}
		if (isset($characteristics['intelligence'])) {
			$this->minIntelligence = $characteristics['intelligence']['min'];
			$this->maxIntelligence = $characteristics['intelligence']['max'];
		} elseif ($zeroMissing) {
			$this->minIntelligence = 0;
			$this->maxIntelligence = 0;
		}
		if (isset($characteristics['chance'])) {
			$this->minChance = $characteristics['chance']['min'];
			$this->maxChance = $characteristics['chance']['max'];
		} elseif ($zeroMissing) {
			$this->minChance = 0;
			$this->maxChance = 0;
		}
		if (isset($characteristics['agility'])) {
			$this->minAgility = $characteristics['agility']['min'];
			$this->maxAgility = $characteristics['agility']['max'];
		} elseif ($zeroMissing) {
			$this->minAgility = 0;
			$this->maxAgility = 0;
		}
		if (isset($characteristics['wisdom'])) {
			$this->minWisdom = $characteristics['wisdom']['min'];
			$this->maxWisdom = $characteristics['wisdom']['max'];
		} elseif ($zeroMissing) {
			$this->minWisdom = 0;
			$this->maxWisdom = 0;
		}
		if (isset($characteristics['power'])) {
			$this->minPower = $characteristics['power']['min'];
			$this->maxPower = $characteristics['power']['max'];
		} elseif ($zeroMissing) {
			$this->minPower = 0;
			$this->maxPower = 0;
		}
		if (isset($characteristics['criticalHits'])) {
			$this->minCriticalHits = $characteristics['criticalHits']['min'];
			$this->maxCriticalHits = $characteristics['criticalHits']['max'];
		} elseif ($zeroMissing) {
			$this->minCriticalHits = 0;
			$this->maxCriticalHits = 0;
		}
		if (isset($characteristics['ap'])) {
			$this->minAp = $characteristics['ap']['min'];
			$this->maxAp = $characteristics['ap']['max'];
		} elseif ($zeroMissing) {
			$this->minAp = 0;
			$this->maxAp = 0;
		}
		if (isset($characteristics['mp'])) {
			$this->minMp = $characteristics['mp']['min'];
			$this->maxMp = $characteristics['mp']['max'];
		} elseif ($zeroMissing) {
			$this->minMp = 0;
			$this->maxMp = 0;
		}
		if (isset($characteristics['range'])) {
			$this->minRange = $characteristics['range']['min'];
			$this->maxRange = $characteristics['range']['max'];
		} elseif ($zeroMissing) {
			$this->minRange = 0;
			$this->maxRange = 0;
		}
		if (isset($characteristics['summons'])) {
			$this->minSummons = $characteristics['summons']['min'];
			$this->maxSummons = $characteristics['summons']['max'];
		} elseif ($zeroMissing) {
			$this->minSummons = 0;
			$this->maxSummons = 0;
		}
		if (isset($characteristics['damage'])) {
			$this->minDamage = $characteristics['damage']['min'];
			$this->maxDamage = $characteristics['damage']['max'];
		} elseif ($zeroMissing) {
			$this->minDamage = 0;
			$this->maxDamage = 0;
		}
		if (isset($characteristics['neutralDamage'])) {
			$this->minNeutralDamage = $characteristics['neutralDamage']['min'];
			$this->maxNeutralDamage = $characteristics['neutralDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minNeutralDamage = 0;
			$this->maxNeutralDamage = 0;
		}
		if (isset($characteristics['earthDamage'])) {
			$this->minEarthDamage = $characteristics['earthDamage']['min'];
			$this->maxEarthDamage = $characteristics['earthDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minEarthDamage = 0;
			$this->maxEarthDamage = 0;
		}
		if (isset($characteristics['fireDamage'])) {
			$this->minFireDamage = $characteristics['fireDamage']['min'];
			$this->maxFireDamage = $characteristics['fireDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minFireDamage = 0;
			$this->maxFireDamage = 0;
		}
		if (isset($characteristics['waterDamage'])) {
			$this->minWaterDamage = $characteristics['waterDamage']['min'];
			$this->maxWaterDamage = $characteristics['waterDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minWaterDamage = 0;
			$this->maxWaterDamage = 0;
		}
		if (isset($characteristics['airDamage'])) {
			$this->minAirDamage = $characteristics['airDamage']['min'];
			$this->maxAirDamage = $characteristics['airDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minAirDamage = 0;
			$this->maxAirDamage = 0;
		}
		if (isset($characteristics['heals'])) {
			$this->minHeals = $characteristics['heals']['min'];
			$this->maxHeals = $characteristics['heals']['max'];
		} elseif ($zeroMissing) {
			$this->minHeals = 0;
			$this->maxHeals = 0;
		}
		if (isset($characteristics['prospecting'])) {
			$this->minProspecting = $characteristics['prospecting']['min'];
			$this->maxProspecting = $characteristics['prospecting']['max'];
		} elseif ($zeroMissing) {
			$this->minProspecting = 0;
			$this->maxProspecting = 0;
		}
		if (isset($characteristics['initiative'])) {
			$this->minInitiative = $characteristics['initiative']['min'];
			$this->maxInitiative = $characteristics['initiative']['max'];
		} elseif ($zeroMissing) {
			$this->minInitiative = 0;
			$this->maxInitiative = 0;
		}
		if (isset($characteristics['reflectedDamage'])) {
			$this->minReflectedDamage = $characteristics['reflectedDamage']['min'];
			$this->maxReflectedDamage = $characteristics['reflectedDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minReflectedDamage = 0;
			$this->maxReflectedDamage = 0;
		}
		if (isset($characteristics['percentNeutralResistance'])) {
			$this->minPercentNeutralResistance = $characteristics['percentNeutralResistance']['min'];
			$this->maxPercentNeutralResistance = $characteristics['percentNeutralResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentNeutralResistance = 0;
			$this->maxPercentNeutralResistance = 0;
		}
		if (isset($characteristics['percentEarthResistance'])) {
			$this->minPercentEarthResistance = $characteristics['percentEarthResistance']['min'];
			$this->maxPercentEarthResistance = $characteristics['percentEarthResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentEarthResistance = 0;
			$this->maxPercentEarthResistance = 0;
		}
		if (isset($characteristics['percentFireResistance'])) {
			$this->minPercentFireResistance = $characteristics['percentFireResistance']['min'];
			$this->maxPercentFireResistance = $characteristics['percentFireResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentFireResistance = 0;
			$this->maxPercentFireResistance = 0;
		}
		if (isset($characteristics['percentWaterResistance'])) {
			$this->minPercentWaterResistance = $characteristics['percentWaterResistance']['min'];
			$this->maxPercentWaterResistance = $characteristics['percentWaterResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentWaterResistance = 0;
			$this->maxPercentWaterResistance = 0;
		}
		if (isset($characteristics['percentAirResistance'])) {
			$this->minPercentAirResistance = $characteristics['percentAirResistance']['min'];
			$this->maxPercentAirResistance = $characteristics['percentAirResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentAirResistance = 0;
			$this->maxPercentAirResistance = 0;
		}
		if (isset($characteristics['neutralResistance'])) {
			$this->minNeutralResistance = $characteristics['neutralResistance']['min'];
			$this->maxNeutralResistance = $characteristics['neutralResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minNeutralResistance = 0;
			$this->maxNeutralResistance = 0;
		}
		if (isset($characteristics['earthResistance'])) {
			$this->minEarthResistance = $characteristics['earthResistance']['min'];
			$this->maxEarthResistance = $characteristics['earthResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minEarthResistance = 0;
			$this->maxEarthResistance = 0;
		}
		if (isset($characteristics['fireResistance'])) {
			$this->minFireResistance = $characteristics['fireResistance']['min'];
			$this->maxFireResistance = $characteristics['fireResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minFireResistance = 0;
			$this->maxFireResistance = 0;
		}
		if (isset($characteristics['waterResistance'])) {
			$this->minWaterResistance = $characteristics['waterResistance']['min'];
			$this->maxWaterResistance = $characteristics['waterResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minWaterResistance = 0;
			$this->maxWaterResistance = 0;
		}
		if (isset($characteristics['airResistance'])) {
			$this->minAirResistance = $characteristics['airResistance']['min'];
			$this->maxAirResistance = $characteristics['airResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minAirResistance = 0;
			$this->maxAirResistance = 0;
		}
		if (isset($characteristics['percentNeutralResistanceInPvp'])) {
			$this->minPercentNeutralResistanceInPvp = $characteristics['percentNeutralResistanceInPvp']['min'];
			$this->maxPercentNeutralResistanceInPvp = $characteristics['percentNeutralResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentNeutralResistanceInPvp = 0;
			$this->maxPercentNeutralResistanceInPvp = 0;
		}
		if (isset($characteristics['percentEarthResistanceInPvp'])) {
			$this->minPercentEarthResistanceInPvp = $characteristics['percentEarthResistanceInPvp']['min'];
			$this->maxPercentEarthResistanceInPvp = $characteristics['percentEarthResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentEarthResistanceInPvp = 0;
			$this->maxPercentEarthResistanceInPvp = 0;
		}
		if (isset($characteristics['percentFireResistanceInPvp'])) {
			$this->minPercentFireResistanceInPvp = $characteristics['percentFireResistanceInPvp']['min'];
			$this->maxPercentFireResistanceInPvp = $characteristics['percentFireResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentFireResistanceInPvp = 0;
			$this->maxPercentFireResistanceInPvp = 0;
		}
		if (isset($characteristics['percentWaterResistanceInPvp'])) {
			$this->minPercentWaterResistanceInPvp = $characteristics['percentWaterResistanceInPvp']['min'];
			$this->maxPercentWaterResistanceInPvp = $characteristics['percentWaterResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentWaterResistanceInPvp = 0;
			$this->maxPercentWaterResistanceInPvp = 0;
		}
		if (isset($characteristics['percentAirResistanceInPvp'])) {
			$this->minPercentAirResistanceInPvp = $characteristics['percentAirResistanceInPvp']['min'];
			$this->maxPercentAirResistanceInPvp = $characteristics['percentAirResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minPercentAirResistanceInPvp = 0;
			$this->maxPercentAirResistanceInPvp = 0;
		}
		if (isset($characteristics['neutralResistanceInPvp'])) {
			$this->minNeutralResistanceInPvp = $characteristics['neutralResistanceInPvp']['min'];
			$this->maxNeutralResistanceInPvp = $characteristics['neutralResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minNeutralResistanceInPvp = 0;
			$this->maxNeutralResistanceInPvp = 0;
		}
		if (isset($characteristics['earthResistanceInPvp'])) {
			$this->minEarthResistanceInPvp = $characteristics['earthResistanceInPvp']['min'];
			$this->maxEarthResistanceInPvp = $characteristics['earthResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minEarthResistanceInPvp = 0;
			$this->maxEarthResistanceInPvp = 0;
		}
		if (isset($characteristics['fireResistanceInPvp'])) {
			$this->minFireResistanceInPvp = $characteristics['fireResistanceInPvp']['min'];
			$this->maxFireResistanceInPvp = $characteristics['fireResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minFireResistanceInPvp = 0;
			$this->maxFireResistanceInPvp = 0;
		}
		if (isset($characteristics['waterResistanceInPvp'])) {
			$this->minWaterResistanceInPvp = $characteristics['waterResistanceInPvp']['min'];
			$this->maxWaterResistanceInPvp = $characteristics['waterResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minWaterResistanceInPvp = 0;
			$this->maxWaterResistanceInPvp = 0;
		}
		if (isset($characteristics['airResistanceInPvp'])) {
			$this->minAirResistanceInPvp = $characteristics['airResistanceInPvp']['min'];
			$this->maxAirResistanceInPvp = $characteristics['airResistanceInPvp']['max'];
		} elseif ($zeroMissing) {
			$this->minAirResistanceInPvp = 0;
			$this->maxAirResistanceInPvp = 0;
		}
		if (isset($characteristics['lock'])) {
			$this->minLock = $characteristics['lock']['min'];
			$this->maxLock = $characteristics['lock']['max'];
		} elseif ($zeroMissing) {
			$this->minLock = 0;
			$this->maxLock = 0;
		}
		if (isset($characteristics['dodge'])) {
			$this->minDodge = $characteristics['dodge']['min'];
			$this->maxDodge = $characteristics['dodge']['max'];
		} elseif ($zeroMissing) {
			$this->minDodge = 0;
			$this->maxDodge = 0;
		}
		if (isset($characteristics['apReduction'])) {
			$this->minApReduction = $characteristics['apReduction']['min'];
			$this->maxApReduction = $characteristics['apReduction']['max'];
		} elseif ($zeroMissing) {
			$this->minApReduction = 0;
			$this->maxApReduction = 0;
		}
		if (isset($characteristics['mpReduction'])) {
			$this->minMpReduction = $characteristics['mpReduction']['min'];
			$this->maxMpReduction = $characteristics['mpReduction']['max'];
		} elseif ($zeroMissing) {
			$this->minMpReduction = 0;
			$this->maxMpReduction = 0;
		}
		if (isset($characteristics['apLossResistance'])) {
			$this->minApLossResistance = $characteristics['apLossResistance']['min'];
			$this->maxApLossResistance = $characteristics['apLossResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minApLossResistance = 0;
			$this->maxApLossResistance = 0;
		}
		if (isset($characteristics['mpLossResistance'])) {
			$this->minMpLossResistance = $characteristics['mpLossResistance']['min'];
			$this->maxMpLossResistance = $characteristics['mpLossResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minMpLossResistance = 0;
			$this->maxMpLossResistance = 0;
		}
		if (isset($characteristics['criticalDamage'])) {
			$this->minCriticalDamage = $characteristics['criticalDamage']['min'];
			$this->maxCriticalDamage = $characteristics['criticalDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minCriticalDamage = 0;
			$this->maxCriticalDamage = 0;
		}
		if (isset($characteristics['criticalResistance'])) {
			$this->minCriticalResistance = $characteristics['criticalResistance']['min'];
			$this->maxCriticalResistance = $characteristics['criticalResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minCriticalResistance = 0;
			$this->maxCriticalResistance = 0;
		}
		if (isset($characteristics['pushbackDamage'])) {
			$this->minPushbackDamage = $characteristics['pushbackDamage']['min'];
			$this->maxPushbackDamage = $characteristics['pushbackDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minPushbackDamage = 0;
			$this->maxPushbackDamage = 0;
		}
		if (isset($characteristics['pushbackResistance'])) {
			$this->minPushbackResistance = $characteristics['pushbackResistance']['min'];
			$this->maxPushbackResistance = $characteristics['pushbackResistance']['max'];
		} elseif ($zeroMissing) {
			$this->minPushbackResistance = 0;
			$this->maxPushbackResistance = 0;
		}
		if (isset($characteristics['trapPower'])) {
			$this->minTrapPower = $characteristics['trapPower']['min'];
			$this->maxTrapPower = $characteristics['trapPower']['max'];
		} elseif ($zeroMissing) {
			$this->minTrapPower = 0;
			$this->maxTrapPower = 0;
		}
		if (isset($characteristics['trapDamage'])) {
			$this->minTrapDamage = $characteristics['trapDamage']['min'];
			$this->maxTrapDamage = $characteristics['trapDamage']['max'];
		} elseif ($zeroMissing) {
			$this->minTrapDamage = 0;
			$this->maxTrapDamage = 0;
		}
		return $this;
	}

	/**
	 * Get all characteristics
	 *
	 * @return array
	 */
	public function getCharacteristics()
	{
		return [
			'vitality' => [ 'min' => $this->minVitality, 'max' => $this->maxVitality ],
			'strength' => [ 'min' => $this->minStrength, 'max' => $this->maxStrength ],
			'intelligence' => [ 'min' => $this->minIntelligence, 'max' => $this->maxIntelligence ],
			'chance' => [ 'min' => $this->minChance, 'max' => $this->maxChance ],
			'agility' => [ 'min' => $this->minAgility, 'max' => $this->maxAgility ],
			'wisdom' => [ 'min' => $this->minWisdom, 'max' => $this->maxWisdom ],
			'power' => [ 'min' => $this->minPower, 'max' => $this->maxPower ],
			'criticalHits' => [ 'min' => $this->minCriticalHits, 'max' => $this->maxCriticalHits ],
			'ap' => [ 'min' => $this->minAp, 'max' => $this->maxAp ],
			'mp' => [ 'min' => $this->minMp, 'max' => $this->maxMp ],
			'range' => [ 'min' => $this->minRange, 'max' => $this->maxRange ],
			'summons' => [ 'min' => $this->minSummons, 'max' => $this->maxSummons ],
			'damage' => [ 'min' => $this->minDamage, 'max' => $this->maxDamage ],
			'neutralDamage' => [ 'min' => $this->minNeutralDamage, 'max' => $this->maxNeutralDamage ],
			'earthDamage' => [ 'min' => $this->minEarthDamage, 'max' => $this->maxEarthDamage ],
			'fireDamage' => [ 'min' => $this->minFireDamage, 'max' => $this->maxFireDamage ],
			'waterDamage' => [ 'min' => $this->minWaterDamage, 'max' => $this->maxWaterDamage ],
			'airDamage' => [ 'min' => $this->minAirDamage, 'max' => $this->maxAirDamage ],
			'heals' => [ 'min' => $this->minHeals, 'max' => $this->maxHeals ],
			'prospecting' => [ 'min' => $this->minProspecting, 'max' => $this->maxProspecting ],
			'initiative' => [ 'min' => $this->minInitiative, 'max' => $this->maxInitiative ],
			'reflectedDamage' => [ 'min' => $this->minReflectedDamage, 'max' => $this->maxReflectedDamage ],
			'percentNeutralResistance' => [ 'min' => $this->minPercentNeutralResistance, 'max' => $this->maxPercentNeutralResistance ],
			'percentEarthResistance' => [ 'min' => $this->minPercentEarthResistance, 'max' => $this->maxPercentEarthResistance ],
			'percentFireResistance' => [ 'min' => $this->minPercentFireResistance, 'max' => $this->maxPercentFireResistance ],
			'percentWaterResistance' => [ 'min' => $this->minPercentWaterResistance, 'max' => $this->maxPercentWaterResistance ],
			'percentAirResistance' => [ 'min' => $this->minPercentAirResistance, 'max' => $this->maxPercentAirResistance ],
			'neutralResistance' => [ 'min' => $this->minNeutralResistance, 'max' => $this->maxNeutralResistance ],
			'earthResistance' => [ 'min' => $this->minEarthResistance, 'max' => $this->maxEarthResistance ],
			'fireResistance' => [ 'min' => $this->minFireResistance, 'max' => $this->maxFireResistance ],
			'waterResistance' => [ 'min' => $this->minWaterResistance, 'max' => $this->maxWaterResistance ],
			'airResistance' => [ 'min' => $this->minAirResistance, 'max' => $this->maxAirResistance ],
			'percentNeutralResistanceInPvp' => [ 'min' => $this->minPercentNeutralResistanceInPvp, 'max' => $this->maxPercentNeutralResistanceInPvp ],
			'percentEarthResistanceInPvp' => [ 'min' => $this->minPercentEarthResistanceInPvp, 'max' => $this->maxPercentEarthResistanceInPvp ],
			'percentFireResistanceInPvp' => [ 'min' => $this->minPercentFireResistanceInPvp, 'max' => $this->maxPercentFireResistanceInPvp ],
			'percentWaterResistanceInPvp' => [ 'min' => $this->minPercentWaterResistanceInPvp, 'max' => $this->maxPercentWaterResistanceInPvp ],
			'percentAirResistanceInPvp' => [ 'min' => $this->minPercentAirResistanceInPvp, 'max' => $this->maxPercentAirResistanceInPvp ],
			'neutralResistanceInPvp' => [ 'min' => $this->minNeutralResistanceInPvp, 'max' => $this->maxNeutralResistanceInPvp ],
			'earthResistanceInPvp' => [ 'min' => $this->minEarthResistanceInPvp, 'max' => $this->maxEarthResistanceInPvp ],
			'fireResistanceInPvp' => [ 'min' => $this->minFireResistanceInPvp, 'max' => $this->maxFireResistanceInPvp ],
			'waterResistanceInPvp' => [ 'min' => $this->minWaterResistanceInPvp, 'max' => $this->maxWaterResistanceInPvp ],
			'airResistanceInPvp' => [ 'min' => $this->minAirResistanceInPvp, 'max' => $this->maxAirResistanceInPvp ],
			'lock' => [ 'min' => $this->minLock, 'max' => $this->maxLock ],
			'dodge' => [ 'min' => $this->minDodge, 'max' => $this->maxDodge ],
			'apReduction' => [ 'min' => $this->minApReduction, 'max' => $this->maxApReduction ],
			'mpReduction' => [ 'min' => $this->minMpReduction, 'max' => $this->maxMpReduction ],
			'apLossResistance' => [ 'min' => $this->minApLossResistance, 'max' => $this->maxApLossResistance ],
			'mpLossResistance' => [ 'min' => $this->minMpLossResistance, 'max' => $this->maxMpLossResistance ],
			'criticalDamage' => [ 'min' => $this->minCriticalDamage, 'max' => $this->maxCriticalDamage ],
			'criticalResistance' => [ 'min' => $this->minCriticalResistance, 'max' => $this->maxCriticalResistance ],
			'pushbackDamage' => [ 'min' => $this->minPushbackDamage, 'max' => $this->maxPushbackDamage ],
			'pushbackResistance' => [ 'min' => $this->minPushbackResistance, 'max' => $this->maxPushbackResistance ],
			'trapPower' => [ 'min' => $this->minTrapPower, 'max' => $this->maxTrapPower ],
			'trapDamage' => [ 'min' => $this->minTrapDamage, 'max' => $this->maxTrapDamage ]
		];
	}
}
