dof_main_homepage:
    pattern:  /
    defaults: { _controller: DofMainBundle:Default:index }

dof_main_calculateur:
    pattern:  /calculateur
    defaults: { _controller: DofMainBundle:Calculateur:index }

dof_notifications_get_notifications:
    pattern:  /notifications/get_notifications
    defaults: { _controller: DofMainBundle:Notification:ajax }
    options:  { expose: true }
