dof_main_homepage:
    pattern:  /
    defaults: { _controller: DofMainBundle:Default:index }

dof_search_engine:
    pattern:  /search
    defaults: { _controller: DofMainBundle:Default:searchEngine }

dof_intelligent_search_engine:
    pattern:  /intelligent-search
    defaults: { _controller: DofMainBundle:SearchEngine:index }

dof_main_calculateur:
    pattern:  /calculateur
    defaults: { _controller: DofMainBundle:Calculateur:index }

dof_notifications_ajax_list:
    pattern:  /notifications/ajax/list
    defaults: { _controller: DofMainBundle:Notification:ajax }
    options:  { expose: true }

dof_notifications_ajax_check_unread:
    pattern:  /notifications/ajax/check-unread
    defaults: { _controller: DofMainBundle:Notification:checkUnread }
    options:  { expose: true }

dof_notifications_show_all:
    pattern:  /notifications
    defaults: { _controller: DofMainBundle:Notification:showAll }

dof_is_in_update:
    pattern:  /in-update
    defaults: { _controller: DofMainBundle:Default:inUpdate }
    requirements: { _method: GET }
    options:  { expose: true }
