parameters:
#    dof_main.example.class: Dof\MainBundle\Example

services:
#    dof_main.example:
#        class: %dof_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
