parameters:
    dof.main.doctrine.primary_bonus_updater.class: Dof\MainBundle\Doctrine\PrimaryBonusUpdater
    dof.main.doctrine.message_notification.class: Dof\MainBundle\Doctrine\MessageNotification
    dof.main.doctrine.set_updater.class: Dof\MainBundle\Doctrine\SetUpdater

services:
    dof.twig.main_extension:
        class: Dof\MainBundle\Twig\MainExtension
        tags:
            - { name: twig.extension }

    dof_main.admin.badge:
        class: Dof\MainBundle\Admin\BadgeAdmin
        arguments: [~, Dof\MainBundle\Entity\Badge, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Badge, label: Badge}

    dof_main.admin.badge_level:
        class: Dof\MainBundle\Admin\BadgeLevelAdmin
        arguments: [~, Dof\MainBundle\Entity\BadgeLevel, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Badge, label: BadgeLevel}

    badge_manager:
        class: Dof\MainBundle\BadgeManager
        arguments: [ "@service_container" ]

    notification_manager:
        class: Dof\MainBundle\NotificationManager
        arguments: [ "@service_container" ]


    dof.main.doctrine.primary_bonus_updater:
        class: "%dof.main.doctrine.primary_bonus_updater.class%"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    dof.main.doctrine.message_notification:
        class: "%dof.main.doctrine.message_notification.class%"
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    dof.main.doctrine.set_updater:
        class: "%dof.main.doctrine.set_updater.class%"
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postPersist }
