dof_graphics_pipette_process:
    pattern:  /pipette
    defaults: { _controller: DofGraphicsBundle:Pipette:process }
    requirements: { _method: POST }

dof_graphics_pipette:
    pattern:  /pipette
    defaults: { _controller: DofGraphicsBundle:Pipette:index }
