parameters:
    dof_graphics.bpcl_hydrator.class: Dof\GraphicsBundle\BPCLHydrator
    dof_graphics.bpcl_identifier.class: Dof\GraphicsBundle\BPCLIdentifier
    dof_graphics.living_item_factory.class: Dof\GraphicsBundle\LivingItemFactory
    dof_graphics.chameleon_dragoturkey.class: Dof\GraphicsBundle\ChameleonDragoturkey
    dof_graphics.form.type.character_look.class: Dof\GraphicsBundle\Form\Type\CharacterLookType

services:
    dof_graphics.bpcl_hydrator:
        class: %dof_graphics.bpcl_hydrator.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
    dof_graphics.bpcl_identifier:
        class: %dof_graphics.bpcl_identifier.class%
        arguments: [@doctrine.orm.default_entity_manager, @dof_graphics.living_item_factory, @dof_graphics.chameleon_dragoturkey]
    dof_graphics.living_item_factory:
        class: %dof_graphics.living_item_factory.class%
        arguments: [@doctrine.orm.default_entity_manager]
    dof_graphics.chameleon_dragoturkey:
        class: %dof_graphics.chameleon_dragoturkey.class%
        arguments: [@translator, @doctrine.orm.entity_manager]

    # FORMS
    dof_graphics.form.type.character_look:
        class: %dof_graphics.form.type.character_look.class%
        tags:
            - { name: form.type, alias: character_look }
        arguments: [@security.context, "@request_stack"]
