<?php

namespace Dof\Bundle\ItemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemComponentRepository extends EntityRepository
{
}
