<?php

namespace Dof\Bundle\ItemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemSetCombinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemSetCombinationRepository extends EntityRepository
{
}
