services:
    # dof_user.registration_listener:
    #     class: Dof\Bundle\UserBundle\EventListener\RegistrationListener
    #     arguments: ["@service_container"]
    #     tags:
    #         - { name: kernel.event_subscriber }

    dof_user.role_helper:
        class: Dof\Bundle\UserBundle\RoleHelper
        arguments: ["@security.role_hierarchy", "@security.token_storage"]
