imports:
    - { resource: importers/item.yml }
    - { resource: importers/quest.yml }
    - { resource: importers/spell.yml }

services:
    importer_dependencies:
        class: XN\DependencyInjection\ServiceArray
        arguments: [ "@dof_imp_exp.game_data_provider", "@doctrine.orm.entity_manager", "xn.doctrine.sluggable_updater" ]

    # DofCharactersBundle:Breed
    dof_imp_exp.importer.breeds:
        class: Dof\ImpExpBundle\Importer\GameData\BreedImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breeds, requires: breeds }
    dof_imp_exp.importer.breed_default_colors:
        class: Dof\ImpExpBundle\Importer\GameData\BreedDefaultColorsImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_default_colors, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_default_colors, requires: beta_breeds }
    dof_imp_exp.importer.breed_lodef_skins:
        class: Dof\ImpExpBundle\Importer\GameData\BreedLodefSkinsImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_lodef_skins, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_lodef_skins, requires: beta_breeds }
    # DofCharactersBundle:Face
    dof_imp_exp.importer.breed_faces:
        class: Dof\ImpExpBundle\Importer\GameData\FaceImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_faces, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_faces, requires: beta_breeds }

    # DofCharactersBundle:SoftCap
    dof_imp_exp.importer.breed_soft_caps:
        class: Dof\ImpExpBundle\Importer\GameData\SoftCapImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_soft_caps, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_soft_caps, requires: beta_breeds }

    # DofItemsBundle:Job
    dof_imp_exp.importer.job:
        class: Dof\ImpExpBundle\Importer\GameData\JobImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: job }
            - { name: dof_imp_exp.importer, provides: beta_job }

    # DofMonsterBundle:Monster
    dof_imp_exp.importer.monsters:
        class: Dof\ImpExpBundle\Importer\GameData\MonsterImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: monsters }
            - { name: dof_imp_exp.importer, provides: beta_monsters }

    # DofCharactersBundle:EffectTemplate
    dof_imp_exp.importer.effect_templates:
        class: Dof\ImpExpBundle\Importer\GameData\EffectTemplateImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: effect_templates }
            - { name: dof_imp_exp.importer, provides: beta_effect_templates }

    # DofCharactersBundle:State
    dof_imp_exp.importer.states:
        class: Dof\ImpExpBundle\Importer\GameData\StateImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: states }
            - { name: dof_imp_exp.importer, provides: beta_states }

    # DofCharactersBundle:Emoticon
    dof_imp_exp.importer.emoticons:
        class: Dof\ImpExpBundle\Importer\GameData\EmoticonImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: emoticons }
            - { name: dof_imp_exp.importer, provides: beta_emoticons }

    # DofCharactersBundle:Titles
    dof_imp_exp.importer.titles:
        class: Dof\ImpExpBundle\Importer\GameData\TitleImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: titles }
            - { name: dof_imp_exp.importer, provides: beta_titles }

    # DofItemsBundle:Document
    dof_imp_exp.importer.documents:
        class: Dof\ImpExpBundle\Importer\GameData\DocumentImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: documents }
            - { name: dof_imp_exp.importer, provides: beta_documents }
