services:
    # DofCharactersBundle:Breed
    dof_imp_exp.importer.breeds:
        class: Dof\ImpExpBundle\Importer\GameData\BreedImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breeds, requires: breeds }
    dof_imp_exp.importer.breed_default_colors:
        class: Dof\ImpExpBundle\Importer\GameData\BreedDefaultColorsImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_default_colors, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_default_colors, requires: beta_breeds }
    dof_imp_exp.importer.breed_lodef_skins:
        class: Dof\ImpExpBundle\Importer\GameData\BreedLodefSkinsImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_lodef_skins, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_lodef_skins, requires: beta_breeds }
    # DofCharactersBundle:Face
    dof_imp_exp.importer.breed_faces:
        class: Dof\ImpExpBundle\Importer\GameData\FaceImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_faces, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_faces, requires: beta_breeds }
    # DofCharactersBundle:SoftCap
    dof_imp_exp.importer.breed_soft_caps:
        class: Dof\ImpExpBundle\Importer\GameData\SoftCapImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: breed_soft_caps, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breed_soft_caps, requires: beta_breeds }
    # DofItemsBundle:ItemSet
    dof_imp_exp.importer.item_sets:
        class: Dof\ImpExpBundle\Importer\GameData\ItemSetImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_sets }
            - { name: dof_imp_exp.importer, provides: beta_item_sets, requires: item_sets }

    # DofItemsBundle:ItemSetCombination, DofItemsBundle:ItemSetEffect
    dof_imp_exp.importer.item_set_effects:
        class: Dof\ImpExpBundle\Importer\GameData\ItemSetEffectImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_set_effects, requires: item_sets }
            - { name: dof_imp_exp.importer, provides: beta_item_set_effects, requires: beta_item_sets }
    # DofItemsBundle:ItemType
    dof_imp_exp.importer.item_types:
        class: Dof\ImpExpBundle\Importer\GameData\ItemTypeImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_types }
            - { name: dof_imp_exp.importer, provides: beta_item_types, requires: item_types }
    # DofItemsBundle:ItemTemplate and subclasses
    dof_imp_exp.importer.item_templates:
        class: Dof\ImpExpBundle\Importer\GameData\ItemTemplateImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_templates, requires: 'item_sets item_types' }
            - { name: dof_imp_exp.importer, provides: beta_item_templates, requires: 'item_templates beta_item_sets beta_item_types' }
    dof_imp_exp.importer.item_template_skins:
        class: Dof\ImpExpBundle\Importer\GameData\ItemTemplateSkinImporter
        arguments: [ "http://exter-n.fr/dofus/its.json", @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_template_skins, requires: item_templates }
    dof_imp_exp.importer.item_effects:
        class: Dof\ImpExpBundle\Importer\GameData\ItemEffectImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_template_effects, requires: "item_templates effect_templates" }
            - { name: dof_imp_exp.importer, provides: beta_item_template_effects, requires: "beta_item_templates beta_effect_templates" }
        calls:
            - [ setParamLoader, [ "@dof_characters.effect_param_loader" ] ]

    # DofItemsBundle:ItemComponent
    dof_imp_exp.importer.item_components:
        class: Dof\ImpExpBundle\Importer\GameData\ItemComponentImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_components, requires: item_templates }
            - { name: dof_imp_exp.importer, provides: beta_item_components, requires: beta_item_templates }

    # DofItemsBundle:Job
    dof_imp_exp.importer.job:
        class: Dof\ImpExpBundle\Importer\GameData\JobImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: job }
            - { name: dof_imp_exp.importer, provides: beta_job }

    # DofItemsBundle:PetTemplate and subclasses
    dof_imp_exp.importer.pet_food:
        class: Dof\ImpExpBundle\Importer\GameData\PetFoodImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: pet_food, requires: item_templates }
            - { name: dof_imp_exp.importer, provides: beta_pet_food, requires: beta_item_templates }

    # DofMonsterBundle:Monster
    dof_imp_exp.importer.monsters:
        class: Dof\ImpExpBundle\Importer\GameData\MonsterImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: monsters }
            - { name: dof_imp_exp.importer, provides: beta_monsters }

    # DofCharactersBundle:EffectTemplate
    dof_imp_exp.importer.effect_templates:
        class: Dof\ImpExpBundle\Importer\GameData\EffectTemplateImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: effect_templates }
            - { name: dof_imp_exp.importer, provides: beta_effect_templates }

    # DofCharactersBundle:Spell and subclasses
    dof_imp_exp.importer.spells:
        class: Dof\ImpExpBundle\Importer\GameData\SpellImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: spells, requires: breeds }
            - { name: dof_imp_exp.importer, provides: beta_spells, requires: beta_breeds }

    dof_imp_exp.importer.spell_ranks:
        class: Dof\ImpExpBundle\Importer\GameData\SpellRankImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: spell_ranks, requires: spells }
            - { name: dof_imp_exp.importer, provides: beta_spell_ranks, requires: beta_spells }

    dof_imp_exp.importer.spell_rank_effects:
        class: Dof\ImpExpBundle\Importer\GameData\SpellRankEffectImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: spell_rank_effects, requires: "spell_ranks effect_templates" }
            - { name: dof_imp_exp.importer, provides: beta_spell_rank_effects, requires: "beta_spell_ranks beta_effect_templates" }
        calls:
            - [ setParamLoader, [ "@dof_characters.effect_param_loader" ] ]

    dof_imp_exp.importer.states:
        class: Dof\ImpExpBundle\Importer\GameData\StateImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: states }
            - { name: dof_imp_exp.importer, provides: beta_states }

    dof_imp_exp.importer.spell_rank_states:
        class: Dof\ImpExpBundle\Importer\GameData\SpellRankStateRequirementImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: spell_rank_states, requires: 'states spell_ranks' }
            - { name: dof_imp_exp.importer, provides: beta_spell_rank_states, requires: 'beta_states beta_spell_ranks' }

    # DofCharactersBundle:Emoticon
    dof_imp_exp.importer.emoticons:
        class: Dof\ImpExpBundle\Importer\GameData\EmoticonImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: emoticons }
            - { name: dof_imp_exp.importer, provides: beta_emoticons }

    # DofCharactersBundle:Titles
    dof_imp_exp.importer.titles:
        class: Dof\ImpExpBundle\Importer\GameData\TitleImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: titles }
            - { name: dof_imp_exp.importer, provides: beta_titles }

    # DofItemsBundle:Document
    dof_imp_exp.importer.documents:
        class: Dof\ImpExpBundle\Importer\GameData\DocumentImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: documents }
            - { name: dof_imp_exp.importer, provides: beta_documents }

    # DofQuestBundle:Quest and subclasses
    dof_imp_exp.importer.quest_categories:
        class: Dof\ImpExpBundle\Importer\GameData\QuestCategoryImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: quest_categories }
            - { name: dof_imp_exp.importer, provides: beta_quest_categories }

    dof_imp_exp.importer.quests:
        class: Dof\ImpExpBundle\Importer\GameData\QuestImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: quests, requires: quest_categories }
            - { name: dof_imp_exp.importer, provides: beta_quests, requires: beta_quest_categories }
