services:
    dof_imp_exp.importer.item_sets:
        class: Dof\ImpExpBundle\Importer\GameData\ItemSetImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_sets }
            - { name: dof_imp_exp.importer, provides: beta_item_sets, requires: item_sets }
    dof_imp_exp.importer.breeds:
        class: Dof\ImpExpBundle\Importer\GameData\BreedImporter
        arguments: [ @dof_imp_exp.game_data_provider, @doctrine.orm.entity_manager ]
        tags:
            - { name: dof_imp_exp.importer, provides: breeds }
            - { name: dof_imp_exp.importer, provides: beta_breeds, requires: breeds }
