<?php

namespace Dof\ItemsManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* MountRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class MountRepository extends EntityRepository
{
}
