<?php

namespace Dof\ItemsManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* SkinnedItem
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class SkinnedItemRepository extends EntityRepository
{
}
