<?php

namespace Dof\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	function displayOrder()
	{
		$qb = $this->createQueryBuilder('s')
                   ->addOrderBy('s.index', 'ASC');

		return $qb;
	}
}
