<?php

namespace Dof\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
	function orderByDate()
	{
		$qb = $this->createQueryBuilder('f')
				->select('f', 't', 'm')
				->join('f.topics', 't')
				->join('t.messages', 'm')
                ->addOrderBy('m.createdAt', 'desc');

		return $qb->getQuery()
        	->getResult();
	}
}
