<?php

namespace Dof\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dof\UserBundle\Entity\User;
use Dof\ForumBundle\Entity\Topic;

/**
 * topicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{	
	function isReadByRepo(Topic $topic, User $user)
	{
		$qb = $this->createQueryBuilder('t')
				->select('t', 'r', 'r')
				->join('readBy', 'r')
				->where('r.id = :user')
				->andWhere('t.id = :topic')
				->setParameters(array('user' => $user->getId(), 'topic' => $topic->getId()))
				->getQuery()->getResult();
			
		if(!empty($qb))
			return true;

		return false;
	}
}
