<?php

namespace Dof\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dof\UserBundle\Entity\User;
use Dof\ForumBundle\Entity\Topic;

/**
 * topicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
}
