<?php

namespace Dof\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * topicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
	function orderByDate()
	{
		$qb = $this->createQueryBuilder('t')
				->select('t', 'm')
				->join('t.messages', 'm')
                ->addOrderBy('m.createdAt', 'desc');

		return $qb->getQuery()
        	->getResult();
	}
}
