<?php

namespace Dof\Bundle\User\CharacterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StuffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuffRepository extends EntityRepository
{
    public function findParamConverter($user, $character, $stuff) {
        $qb = $this
              ->createQueryBuilder('s')
              ->select(array('s', 'c', 'u'))
              ->join('s.character', 'c')
              ->join('c.owner', 'u')
              ->where('s.slug = :stuff and c.slug = :character and u.slug = :user')
              ->getQuery()
              ->setParameter('stuff', $stuff)
              ->setParameter('character', $character)
              ->setParameter('user', $user);

        try {
            $return = $qb->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $return = null;
        }

        return $return;
    }
}
