parameters:
#    dof_map.example.class: Dof\Bundle\MapBundle\Example

services:
#    dof_map.example:
#        class: %dof_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
