<?php

namespace Dof\QuestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestObjectiveTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestObjectiveTypeRepository extends EntityRepository
{
}
