<?php

namespace Dof\QuestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestObjectiveTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestObjectiveTemplateRepository extends EntityRepository
{
}
