services:
    dof_imp_exp.item_loaders:
        class: XN\DependencyInjection\ServiceArray
        arguments:
            - "@dof_characters.effect_param_loader"
            - "@dof_items.criteria_loader"

    # DofItemsBundle:ItemSet
    dof_imp_exp.importer.item_sets:
        class: Dof\ImpExpBundle\Importer\GameData\Item\ItemSetImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_sets }
            - { name: dof_imp_exp.importer, provides: beta_item_sets, requires: item_sets }

    # DofItemsBundle:ItemSetCombination, DofItemsBundle:ItemSetEffect
    dof_imp_exp.importer.item_set_effects:
        class: Dof\ImpExpBundle\Importer\GameData\Item\ItemSetEffectImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_set_effects, requires: item_sets }
            - { name: dof_imp_exp.importer, provides: beta_item_set_effects, requires: beta_item_sets }

    # DofItemsBundle:ItemType
    dof_imp_exp.importer.item_types:
        class: Dof\ImpExpBundle\Importer\GameData\Item\ItemTypeImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_types }
            - { name: dof_imp_exp.importer, provides: beta_item_types, requires: item_types }

    # DofItemsBundle:ItemTemplate and subclasses
    dof_imp_exp.importer.item_templates:
        class: Dof\ImpExpBundle\Importer\GameData\Item\ItemTemplateImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_templates, requires: 'item_sets item_types' }
            - { name: dof_imp_exp.importer, provides: beta_item_templates, requires: 'item_templates beta_item_sets beta_item_types' }
        calls:
            - [ setLoaders, [ "@dof_imp_exp.item_loaders" ] ]
            
    dof_imp_exp.importer.item_template_skins:
        class: Dof\ImpExpBundle\Importer\GameData\Item\ItemTemplateSkinImporter
        arguments: [ "http://exter-n.fr/dofus/its.json", "@doctrine.orm.entity_manager" ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_template_skins, requires: item_templates }

    dof_imp_exp.importer.item_effects:
        class: Dof\ImpExpBundle\Importer\GameData\Item\ItemEffectImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_template_effects, requires: "item_templates effect_templates" }
            - { name: dof_imp_exp.importer, provides: beta_item_template_effects, requires: "beta_item_templates beta_effect_templates" }
        calls:
            - [ setLoaders, [ "@dof_imp_exp.item_loaders" ] ]

    # DofItemsBundle:ItemComponent
    dof_imp_exp.importer.item_components:
        class: Dof\ImpExpBundle\Importer\GameData\Item\ItemComponentImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: item_components, requires: item_templates }
            - { name: dof_imp_exp.importer, provides: beta_item_components, requires: beta_item_templates }
        calls:
            - [ setLoaders, [ "@dof_imp_exp.item_loaders" ] ]

    # DofItemsBundle:PetTemplate and subclasses
    dof_imp_exp.importer.pet_food:
        class: Dof\ImpExpBundle\Importer\GameData\Item\PetFoodImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: pet_food, requires: item_templates }
            - { name: dof_imp_exp.importer, provides: beta_pet_food, requires: beta_item_templates }
        calls:
            - [ setLoaders, [ "@dof_imp_exp.item_loaders" ] ]
