services:
    # DofMonsterBundle:Monster
    dof_imp_exp.importer.monster_super_races:
        class: Dof\ImpExpBundle\Importer\GameData\Monster\MonsterSuperRaceImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: monster_super_races }
            - { name: dof_imp_exp.importer, provides: beta_monster_super_races }

    dof_imp_exp.importer.monster_races:
        class: Dof\ImpExpBundle\Importer\GameData\Monster\MonsterRaceImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: monster_races, requires: monster_super_races }
            - { name: dof_imp_exp.importer, provides: beta_monster_races, requires: beta_monster_super_races }

    dof_imp_exp.importer.monsters:
        class: Dof\ImpExpBundle\Importer\GameData\Monster\MonsterImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: monsters, requires: monster_races }
            - { name: dof_imp_exp.importer, provides: beta_monsters, requires: beta_monster_races }

    dof_imp_exp.importer.arch_monsters:
        class: Dof\ImpExpBundle\Importer\GameData\Monster\ArchMonsterImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: arch_monsters, requires: monsters }
            - { name: dof_imp_exp.importer, provides: beta_arch_monsters, requires: beta_monsters }

    dof_imp_exp.importer.monster_grades:
        class: Dof\ImpExpBundle\Importer\GameData\Monster\MonsterGradeImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: monster_grades, requires: monsters }
            - { name: dof_imp_exp.importer, provides: beta_monster_grades, requires: beta_monsters }

    dof_imp_exp.importer.monster_drops:
        class: Dof\ImpExpBundle\Importer\GameData\Monster\MonsterDropImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: monster_drops, requires: "monsters item_templates" }
            - { name: dof_imp_exp.importer, provides: beta_monster_drops, requires: "beta_monsters beta_item_templates" }


    dof_imp_exp.importer.monster_spells:
        class: Dof\ImpExpBundle\Importer\GameData\Monster\MonsterSpellImporter
        arguments: [ "@importer_dependencies" ]
        tags:
            - { name: dof_imp_exp.importer, provides: monster_spells, requires: "monsters spells" }
            - { name: dof_imp_exp.importer, provides: beta_monster_spells, requires: "beta_monsters beta_spells" }
