dof_notifications_ajax_list:
    path:  /notifications/ajax/list
    defaults: { _controller: DofMainBundle:Notification:ajax }
    options:  { expose: true }

dof_notifications_ajax_check_unread:
    path:  /notifications/ajax/check-unread
    defaults: { _controller: DofMainBundle:Notification:checkUnread }
    options:  { expose: true }

dof_notifications_show_all:
    path:  /notifications
    defaults: { _controller: DofMainBundle:Notification:showAll }
