services:
    dof_main.admin.badge:
        class: Dof\Bundle\MainBundle\Admin\BadgeAdmin
        arguments: [~, Dof\Bundle\MainBundle\Entity\Badge, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Badge, label: Badge}

    dof_main.admin.badge_level:
        class: Dof\Bundle\MainBundle\Admin\BadgeLevelAdmin
        arguments: [~, Dof\Bundle\MainBundle\Entity\BadgeLevel, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Badge, label: BadgeLevel}

    badge_manager:
        class: Dof\Bundle\MainBundle\BadgeManager
        arguments: [ "@service_container" ]

    dof_main.admin.notification:
        class: Dof\Bundle\MainBundle\Admin\NotificationAdmin
        arguments: [~, Dof\Bundle\MainBundle\Entity\Notification, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Utilisateurs, label: Notification}
    app_main.event.authentication_success_listener:
        class: App\MainBundle\EventListener\AuthenticationSuccessListener
        arguments: [@app_user.role_helper]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
