services:
    badge_manager:
        class: Dof\Bundle\MainBundle\BadgeManager
        arguments: [ "@service_container" ]

    dof_main.event.authentication_success_listener:
        class: Dof\Bundle\MainBundle\EventListener\AuthenticationSuccessListener
        arguments: [@dof_user.role_helper]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
