<?php

namespace Dof\Bundle\Social\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dof\Bundle\UserBundle\Entity\User;
use Dof\Bundle\Social\ForumBundle\Entity\Forum;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
	function getOrderByDate()
	{
		$qb = $this->createQueryBuilder('f')
				->select('f', 't', 'm')
				->leftjoin('f.topics', 't')
				->leftjoin('t.messages', 'm')
                ->addOrderBy('m.createdAt', 'desc');

		return $qb->getQuery()->getSingleResult();
	}
}
