<?php

namespace Dof\Bundle\Social\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * topicRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
}
