services:
    sonata.admin.post:
        class: Dof\AdminBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Articles" }
        arguments:
            - ~
            - Dof\ArticlesBundle\Entity\Article
            - ~
        calls:
            - [ setTranslationDomain, [DofArticlesBundle]]
