services:
    sonata.admin.user:
        class: Dof\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Utilisateurs" }
        arguments:
            - ~
            - Dof\UserBundle\Entity\User
            - ~

        calls:
            - [ setTranslationDomain, [DofUserBundle]]

    sonata.admin.article:
        class: Dof\AdminBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Articles" }
        arguments:
            - ~
            - Dof\ArticlesBundle\Entity\Article
            - DofAdminBundle:CRUDOwn
        calls:
            - [ setTranslationDomain, [DofArticlesBundle]]

    dof_admin.translation:
        class: Dof\AdminBundle\Admin\TranslationAdmin
        arguments: [~, Dof\TranslationBundle\Entity\Translation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contenu, label: Traductions}

    dof_admin.character_look:
        class: Dof\AdminBundle\Admin\CharacterLookAdmin
        arguments: [~, Dof\GraphicsBundle\Entity\CharacterLook, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Content, label: CharacterLook}
