services:
    dof_admin.users.profile.form.type:
        class: Dof\AdminBundle\Form\Type\ProfileAdminFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: dofadmin_users_profile }
