<?php

namespace Dof\Bundle\User\ItemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CraftRepository extends EntityRepository
{
}
