dof_monster_show:
    path:     /{slug}
    defaults: { _controller: DofMonsterBundle:Monster:show }

dof_monster_addskin:
    pattern: /add-skin/{id}
    defaults: { _controller: DofMonsterBundle:Skins:addImage }
