dof_monster_homepage:
    path:     /{page}
    defaults: { _controller: DofMonsterBundle:Monster:index, page: 1}
    requirements:
        page: \d+

dof_monster_show:
    path:     /{slug}
    defaults: { _controller: DofMonsterBundle:Monster:show }

dof_monster_addskin:
    path: /add-skin/{id}
    defaults: { _controller: DofMonsterBundle:Skins:addImage }
