dof_monster_homepage:
    path:     /{page}
    defaults: { _controller: Dof\Bundle\MonsterBundle\Controller\MonsterController:indexAction, page: 1}
    requirements:
        page: \d+

dof_monster_show:
    path:     /{slug}
    defaults: { _controller: Dof\Bundle\MonsterBundle\Controller\MonsterController:showAction }

dof_monster_addskin:
    path: /add-skin/{id}
    defaults: { _controller: Dof\Bundle\MonsterBundle\Controller\SkinsController:addImageAction }
