<?php

namespace Dof\Bundle\QuestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestStepRepository extends EntityRepository
{
}
