parameters:
#    dof_user.example.class: Dof\UserBundle\Example

services:
    dof_user.profile.form.type:
        class: Dof\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: dof_user_profile }