<?php

namespace Dof\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends EntityRepository
{
    public function findOneBySlugWithLevels($slug) {
        return $this
                  ->createQueryBuilder('i')
                  ->select(array('i', 'l'))
                  ->join('i.levels', 'l')
                  ->where('i.slug = :slug')
                  ->getQuery()
                  ->setParameter('slug', $slug)
                  ->getOneResult();
              ;
    }
}
