<?php

namespace Dof\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BadgeLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeLevelRepository extends EntityRepository
{
}
