<?php

namespace Dof\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dof\UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

    public function countUnread(User $user = null)
    {
        return $this->createQueryBuilder('id')
            ->select('COUNT(id)')
            ->where('id.owner = :owner and id.read = false')
            ->setParameter('owner', $user)
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
