<?php

namespace Dof\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dof\UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

    public function countUnread(User $user = null)
    {
        return $this->createQueryBuilder('id')
            ->select('COUNT(id)')
            ->where('id.owner = :owner and id.isRead = false')
            ->setParameter('owner', $user)
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

    public function delOldPetsNotifications(){
        $interval = new \DateTime();
        $interval->modify('-3 day');

        $count = $this->createQueryBuilder('id')
            ->select('COUNT(id)')
            ->where('id.created_at < :interval and id.isRead = true and type = "pets.hungry"')
            ->setParameter('interval', $interval)
            ->getQuery()
            ->getSingleScalarResult()
        ;
        
        $this->createQueryBuilder('id')
            ->delete('id')
            ->where('id.created_at < :interval and id.isRead = true and type = "pets.hungry"')
            ->setParameter('interval', $interval)
            ->getQuery()
            ->getSingleScalarResult()
        ;
        return $count; 
    }
}
