dof_items_manager_homepage:
    path:   /{page}
    defaults: { _controller: DofUserItemBundle:ItemsManager:index, page: 1}
    requirements:
        page: \d+

dof_items_manager_pets:
    path:   /pets-manager
    defaults: { _controller: DofUserItemBundle:PetsManager:index }

dof_items_manager_pets_feed:
    path:   /pets-manager/feed
    defaults: { _controller: DofUserItemBundle:PetsManager:feed }
    methods: [ POST ]

dof_items_manager_pets_add:
    path:   /pets-manager/add/{id}
    defaults: { _controller: DofUserItemBundle:PetsManager:add}
    requirements:
        id: \d+

dof_items_manager_pets_remove:
    path:   /pets-manager/remove/{id}
    defaults: { _controller: DofUserItemBundle:PetsManager:remove}
    requirements:
        id: \d+

dof_items_manager_pets_raise:
    path:   /pets-manager/raise/{id}
    defaults: { _controller: DofUserItemBundle:PetsManager:raise}
    requirements:
        id: \d+

dof_items_manager_pets_notif:
    path:   /pets-manager/notif
    defaults: { _controller: DofUserItemBundle:PetsManager:notif }
    methods: [ POST ]

dof_crafts_homepage:
    path:   /crafts
    defaults: { _controller: DofUserItemBundle:Craft:index }

dof_crafts_create:
    path:   /crafts/create/{id}
    defaults: { _controller: DofUserItemBundle:Craft:create }
    requirements:
        id: \d+
