dof_forum_homepage:
    path:     /
    defaults: { _controller: DofForumBundle:Forum:index }

dof_forum_show_forum:
    path:     /{slug}
    defaults: { _controller: DofForumBundle:Forum:showForum }
    requirements:
       slug: '[0-9a-z-]+'

dof_forum_show_topic:
    path:     /topic/{slug}
    defaults: { _controller: DofForumBundle:Forum:showTopic }
    requirements:
       slug: '[0-9a-z-]+'

dof_forum_add_message:
    path:     /topic/{slug}/add
    defaults: { _controller: DofForumBundle:Forum:addMessage }
    requirements:
       slug: '[0-9a-z-]+'