parameters:
#    dof_forum.example.class: Dof\ForumBundle\Example

services:
#    dof_forum.example:
#        class: %dof_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    dof_forum.admin.category:
        class: Dof\ForumBundle\Admin\CategoryAdmin
        arguments: [~, Dof\ForumBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Forum, label: Catégorie}

    dof_forum.admin.forum:
        class: Dof\ForumBundle\Admin\ForumAdmin
        arguments: [~, Dof\ForumBundle\Entity\Forum, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Forum, label: Forum}

    dof_forum.admin.topic:
        class: Dof\ForumBundle\Admin\TopicAdmin
        arguments: [~, Dof\ForumBundle\Entity\Topic, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Forum, label: Topic}

    dof_forum.admin.message:
        class: Dof\ForumBundle\Admin\MessageAdmin
        arguments: [~, Dof\ForumBundle\Entity\Message, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Forum, label: Message}

    dof_forum.controller:
        class: Dof\ForumBundle\Controller\ForumController
        arguments: [ "@service_container" ]