parameters:
#    dof_forum.example.class: Dof\ForumBundle\Example

services:
#    dof_forum.example:
#        class: %dof_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
