# REMOVE
dof_user_character_remove:
    path: /remove/character
    defaults: { _controller: DofUserCharacterBundle:Character:remove }
    requirements:
        _method: POST

dof_user_character_stuff_remove:
    path:     /remove/stuff
    defaults: { _controller: DofUserCharacterBundle:Build:remove }
    requirements:
        _method: POST

# CREATE
dof_user_character_create:
    path: /create/character/{slug}
    defaults: { _controller: DofUserCharacterBundle:Character:create }
    requirements:
        slug: '[0-9a-z-]+'
        _method: POST

dof_user_character_stuff_create:
    path:     /create/stuff
    defaults: { _controller: DofUserCharacterBundle:Build:createStuff}
    requirements:
        slug: '[0-9a-z-]+'
        _method: POST

# SHOW PAGE
dof_user_character_homepage:
    path:     /{slug}
    defaults: { _controller: DofUserCharacterBundle:Character:index, slug: ~ }

dof_user_character_show:
    path:     /{user}/{character}
    defaults: { _controller: DofUserCharacterBundle:Character:show}


dof_user_character_stuff:
    path:     /{user}/{character}/stuffs/{stuff}
    defaults: { _controller: DofUserCharacterBundle:Build:show }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_user_character_stuff_characteristics:
    path:     /{user}/{character}/stuffs/{stuff}/characteristics
    defaults: { _controller: DofUserCharacterBundle:Build:showCharacteristics }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_user_character_stuff_weapondamages:
    path:     /{user}/{character}/stuffs/{stuff}/weapon-damages
    defaults: { _controller: DofUserCharacterBundle:Build:showWeaponDamages }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_user_character_stuff_spellsDamages:
    path:     /{user}/{character}/stuffs/{stuff}/spell-damages
    defaults: { _controller: DofUserCharacterBundle:Build:showSpellsDamages }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

dof_user_character_edit:
    path:     /{user}/{character}/stuffs/{stuff}/configuration
    defaults: { _controller: DofUserCharacterBundle:Build:configuration }
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'

# Ajout dans les builds
dof_user_character_additem_post:
    path:     /add-items/
    defaults: { _controller: DofUserCharacterBundle:Stuff:addItems}
    requirements:
        _method: POST

dof_user_character_additem:
    path:     /{user}/{character}/stuffs/{stuff}/add/{type}/{slot}/{page}
    defaults: { _controller: DofItemBundle:Items:showBuildItems, slot: 0, page: 1}
    requirements:
        user: '[0-9a-z-]+'
        character: '[0-9a-z-]+'
        stuff: '[0-9a-z-]+'
        page: \d+
