services:
    dof_user_character.playerCharacter.form.type:
        class: Dof\Bundle\User\CharacterBundle\Form\PlayerCharacterType
        tags:
            - { name: form.type, alias: dof_user_characterbundle_playercharacter }

    dof_user_character.stuff_converter:
        class: Dof\Bundle\User\CharacterBundle\ParamConverter\BuildParamConverter
        arguments: ["@build_manager"]
        tags:
            - { name: request.param_converter, priority: 1}

    build_manager:
        class: Dof\Bundle\User\CharacterBundle\BuildManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    selected_character:
        class: Dof\Bundle\User\CharacterBundle\SelectedCharacter
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker" ]
