parameters:
    xn.utility.twig_extension.class: XN\UtilityBundle\Twig\UtilityExtension
    xn.utility.json_request_listener.class: XN\UtilityBundle\JsonRequestListener

    xn.utility.doctrine.identifiable_updater.class: XN\UtilityBundle\Doctrine\IdentifiableUpdater
    xn.utility.doctrine.ownable_updater.class: XN\UtilityBundle\Doctrine\OwnableUpdater
    xn.utility.doctrine.localized_origin_updater.class: XN\UtilityBundle\Doctrine\LocalizedOriginUpdater
    xn.utility.doctrine.sluggable_updater.class: XN\UtilityBundle\Doctrine\SluggableUpdater
    xn.utility.doctrine.timestampable_updater.class: XN\UtilityBundle\Doctrine\TimestampableUpdater
    xn.utility.doctrine.primary_bonus_updater.class: XN\UtilityBundle\Doctrine\PrimaryBonusUpdater

services:
    xn.utility.twig_extension:
        class: %xn.utility.twig_extension.class%
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }

    xn.utility.json_request_listener:
        class: %xn.utility.json_request_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

#    xn.utility.doctrine.identifiable_updater:
#        class:     "%xn.utility.doctrine.identifiable_updater.class%"
#        arguments: [ "@xn.utility.id_generator" ]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }

    xn.utility.doctrine.ownable_updater:
        class:     "%xn.utility.doctrine.ownable_updater.class%"
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }

    xn.utility.doctrine.localized_origin_updater:
        class:     "%xn.utility.doctrine.localized_origin_updater.class%"
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }

    xn.utility.doctrine.sluggable_updater:
        class: "%xn.utility.doctrine.sluggable_updater.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    xn.utility.doctrine.timestampable_updater:
        class: "%xn.utility.doctrine.timestampable_updater.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }

    xn.utility.doctrine.primary_bonus_updater:
        class: "%xn.utility.doctrine.primary_bonus_updater.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }
