parameters:
    lazy.class: XN\UtilityBundle\DependencyInjection\LazyDelegateContainer
    variables.class: XN\Common\VariableBag
    xn.twig_extension.class: XN\UtilityBundle\Twig\UtilityExtension
    xn.json_request_listener.class: XN\UtilityBundle\JsonRequestListener
    xn.totp_authentication_listener.class: XN\UtilityBundle\TOTPAuthenticationListener
    xn.grammar.class: XN\Grammar\ParserFactory

    xn.doctrine.entity_dependency_injection.class: XN\UtilityBundle\Doctrine\EntityDependencyInjection

    xn.secure_controller_listener.class: XN\UtilityBundle\Annotations\SecureControllerListener
    xn.lazy_field_listener.class: XN\UtilityBundle\Annotations\LazyFieldListener

services:
    lazy:
        class: %lazy.class%
        arguments: [ "@service_container" ]

    variables:
        class: %variables.class%

    cache:
        class: Doctrine\Common\Cache\ApcCache

    xn.twig_extension:
        class: %xn.twig_extension.class%
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }

    xn.json_request_listener:
        class: %xn.json_request_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    xn.totp_authentication_listener:
        class: %xn.totp_authentication_listener.class%
        arguments: [ "@doctrine.orm.default_entity_manager", 3 ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    xn.grammar:
        class: %xn.grammar.class%
        arguments: [ "@annotation_reader" ]

    xn.doctrine.entity_dependency_injection:
        class:     "%xn.doctrine.entity_dependency_injection.class%"
        arguments: [ @lazy\security.context ]
        tags:
            - { name: doctrine.event_listener, event: postLoad }


    xn.secure_controller_listener:
        class: %xn.secure_controller_listener.class%
        arguments: [ @security.context, @annotation_reader ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    xn.lazy_field_listener:
        class: %xn.lazy_field_listener.class%
        arguments: [ @cache, @annotation_reader ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: onFlush }
