services:
    variables:
        class: XN\Common\VariableBag

    cache:
        class: Doctrine\Common\Cache\ApcCache

    xn.twig_extension:
        class: XN\UtilityBundle\Twig\UtilityExtension
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }

    xn.json_request_listener:
        class: XN\UtilityBundle\JsonRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    xn.totp_authentication_listener:
        class: XN\UtilityBundle\TOTPAuthenticationListener
        arguments: [ "@doctrine.orm.default_entity_manager", 3 ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    xn.grammar:
        class: XN\Grammar\ParserFactory
        arguments: [ "@annotation_reader" ]

    xn.doctrine.file_updater:
        class: XN\UtilityBundle\Doctrine\FileUpdater
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    xn.secure_controller_listener:
        class: XN\UtilityBundle\Annotations\SecureControllerListener
        arguments: [ "@security.authorization_checker", "@annotation_reader"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    xn.lazy_field_listener:
        class: XN\UtilityBundle\Annotations\LazyFieldListener
        arguments: [ "@cache", "@annotation_reader" ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: onFlush }
