parameters:
    xn.twig_extension.class: XN\UtilityBundle\Twig\UtilityExtension
    xn.json_request_listener.class: XN\UtilityBundle\JsonRequestListener
    xn.totp_authentication_listener.class: XN\UtilityBundle\TOTPAuthenticationListener
    xn.grammar.class: XN\Grammar\ParserFactory
    xn.bbcode.simple_tag_template.class: XN\BBCode\TagTemplate\SimpleTagTemplate
    xn.bbcode.item_tag_template.class: XN\BBCode\TagTemplate\ItemTagTemplate

    xn.doctrine.identifiable_updater.class: XN\UtilityBundle\Doctrine\IdentifiableUpdater
    xn.doctrine.ownable_updater.class: XN\UtilityBundle\Doctrine\OwnableUpdater
    xn.doctrine.localized_origin_updater.class: XN\UtilityBundle\Doctrine\LocalizedOriginUpdater
    xn.doctrine.sluggable_updater.class: XN\UtilityBundle\Doctrine\SluggableUpdater
    xn.doctrine.timestampable_updater.class: XN\UtilityBundle\Doctrine\TimestampableUpdater
    xn.doctrine.primary_bonus_updater.class: XN\UtilityBundle\Doctrine\PrimaryBonusUpdater
    xn.doctrine.message_notification.class: XN\UtilityBundle\Doctrine\MessageNotification
    xn.doctrine.file_updater.class: XN\UtilityBundle\Doctrine\FileUpdater

    xn.session_controller_listener.class: XN\UtilityBundle\SessionControllerListener

services:
    lazy.doctrine.orm.default_entity_manager:
        class: XN\DependencyInjection\LazyServiceBox
        arguments: [ "@service_container", "doctrine.orm.default_entity_manager" ]

    xn.twig_extension:
        class: %xn.twig_extension.class%
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }

    xn.json_request_listener:
        class: %xn.json_request_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    xn.totp_authentication_listener:
        class: %xn.totp_authentication_listener.class%
        arguments: [ "@doctrine.orm.default_entity_manager", 3 ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    xn.grammar:
        class: %xn.grammar.class%
        arguments: [ "@annotation_reader" ]

    xn.bbcode.item_tag_template:
        class: %xn.bbcode.item_tag_template.class%
        tags:
            - { name: xn.bbcode.publish, module: lists }

    xn.bbcode.bold_simple_tag_template:
        class: %xn.bbcode.simple_tag_template.class%
        arguments: [ 'b', 'span', ~, 'font-weight: bold;' ]
        tags:
            - { name: xn.bbcode.publish, module: basics }

    xn.bbcode.italic_simple_tag_template:
        class: %xn.bbcode.simple_tag_template.class%
        arguments: [ 'i', 'span', ~, 'font-style: italic;' ]
        tags:
            - { name: xn.bbcode.publish, module: basics }

    xn.bbcode.underline_simple_tag_template:
        class: %xn.bbcode.simple_tag_template.class%
        arguments: [ 'u', 'span', ~, 'text-decoration: underline;' ]
        tags:
            - { name: xn.bbcode.publish, module: basics }

    xn.bbcode.strikethrough_simple_tag_template:
        class: %xn.bbcode.simple_tag_template.class%
        arguments: [ [ 's', 'stike' ], 'span', ~, 'text-decoration: line-through;' ]
        tags:
            - { name: xn.bbcode.publish, module: basics }

#    xn.doctrine.identifiable_updater:
#        class:     "%xn.doctrine.identifiable_updater.class%"
#        arguments: [ "@xn.id_generator" ]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }

    xn.doctrine.ownable_updater:
        class:     "%xn.doctrine.ownable_updater.class%"
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }

    xn.doctrine.localized_origin_updater:
        class:     "%xn.doctrine.localized_origin_updater.class%"
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }

    xn.doctrine.sluggable_updater:
        class: "%xn.doctrine.sluggable_updater.class%"
        arguments: [ "@lazy.doctrine.orm.default_entity_manager" ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    xn.doctrine.timestampable_updater:
        class: "%xn.doctrine.timestampable_updater.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }

    xn.doctrine.file_updater:
        class:     "%xn.doctrine.file_updater.class%"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }


    xn.session_controller_listener:
        class: %xn.session_controller_listener.class%
        arguments: [ @security.context, @session, @annotation_reader ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
